import type { Component } from "@/ir"

/*
 * proposal's 2026-10 board, its content pages as the showcase deck writes
 * them (`showcase/proposal/zh`), less the heading, the tabs, the source line,
 * the deck's label and the folio, which are the face's and the motif's. Each
 * page names the composition that draws it in the binder setting, and
 * whether it has a source line under it (its band then ends at y640,
 * otherwise y648). The board's images are named for the assets the tests
 * hand in (`BINDER_BOARD_IMAGES`).
 */

export interface BinderBoardPage {
  components: Component[]
  drawnBy: string[]
  sourced: boolean
}

export const BINDER_BOARD_IMAGES = ["grid-pv", "grid-ess", "grid-switch", "om-worker"] as const

export const BINDER_BOARD: Record<string, BinderBoardPage> = {
  "p02-promise": {"components": [{"type": "verdict_banner", "tone": "positive", "icon": "handshake", "text": "贵司会得到三样东西"}, {"type": "kpi_cards", "items": [{"icon": "sun", "label": "屋顶每年自发\n一部分白天用电", "value": "108 万 kWh", "note": "每 MW 光伏一年发电\n江苏官方参数，1080 小时"}, {"icon": "calculator", "label": "一份按贵司电费单和\n售电合同算清的回本账", "value": "**6.1 至 7.7 年**", "note": "江苏自投静态回收，每 MW 算例\n未扣衰减、税费和融资"}, {"icon": "file-check", "label": "一份把出资、运维和\n安全责任写清楚的合同", "value": "0 元", "note": "合同能源管理模式下贵司出资\n节省按电价折扣分享"}]}, {"type": "callout", "variant": "tip", "icon": "battery-charging", "text": "储能不默认配：用贵司的负荷曲线测算，扣完运维、衰减和分成之后过线才装。"}], "drawnBy": ["gains"], "sourced": true} as BinderBoardPage,
  "p04-tou": {"components": [{"type": "heatmap", "x_labels": ["0 时", "1 时", "2 时", "3 时", "4 时", "5 时", "6 时", "7 时", "8 时", "9 时", "10 时", "11 时", "12 时", "13 时", "14 时", "15 时", "16 时", "17 时", "18 时", "19 时", "20 时", "21 时", "22 时", "23 时"], "y_labels": ["江苏 10 月：苏发改价格发〔2025〕426 号", "浙江春秋季：浙发改价格〔2026〕112 号", "广东汕头 9 月：粤发改价格〔2021〕331 号"], "values": [[0.64, 0.64, 0.3828, 0.3828, 0.3828, 0.3828, 0.64, 0.64, 0.64, 0.64, 0.3828, 0.3828, 0.3828, 0.3828, 0.64, 0.9566, 0.9566, 0.9566, 0.9566, 0.9566, 0.9566, 0.9566, 0.64, 0.64], [0.3653, 0.3653, 0.3653, 0.3653, 0.3653, 0.3653, 0.3653, 0.6803, 0.6803, 0.6803, 0.6803, 0.3653, 0.3653, 0.3653, 0.6803, 0.6803, 1.1267, 1.1267, 1.1267, 1.1267, 1.1267, 1.1267, 1.1267, 0.6803], [0.2635, 0.2635, 0.2635, 0.2635, 0.2635, 0.2635, 0.2635, 0.2635, 0.6483, 0.6483, 1.0827, 1.3465, 0.6483, 0.6483, 1.0827, 1.3465, 1.3465, 1.0827, 1.0827, 0.6483, 0.6483, 0.6483, 0.6483, 0.6483]], "steps": [{"max": 0.5, "label": "低谷", "short": "谷"}, {"max": 0.9, "label": "平段", "short": "平"}, {"max": 1.3, "label": "高峰", "short": "峰"}, {"label": "尖峰", "short": "尖"}], "label_every": 6, "bands": [{"from": "10 时", "to": "13 时", "label": "午间 10-14 点", "icon": "sun"}], "x_title": "代理购电、两部制、1-10 千伏，元/kWh"}, {"type": "kpi_cards", "items": [{"label": "峰谷差", "value": "0.5738", "note": "谷 0.3828 · 平 0.6400 · 峰 0.9566"}, {"label": "峰谷差", "value": "约 0.76（示意）", "note": "谷 0.3653 · 平 0.6803 · 峰 1.1267"}, {"label": "峰谷差", "value": "0.8192", "note": "谷 0.2635 · 平 0.6483 · 峰 1.0827 · 尖 1.3465"}]}], "drawnBy": ["hours"], "sourced": true} as BinderBoardPage,
  "p05-provinces": {"components": [{"type": "comparison", "columns": ["江苏", "浙江", "广东"], "rows": [{"label": "", "cells": ["苏发改价格发〔2025〕426 号", "浙发改价格〔2026〕112 号", "粤发改价格〔2021〕331 号"]}, {"label": "中午时段", "cells": ["低谷（春秋 10-14 点）", "低谷（全年 11-14 点）", "10-12 点高峰，12-14 点平段"]}, {"label": "峰谷差（元/kWh）", "emphasis": true, "cells": ["0.5738", "约 0.76（示意）", "0.8192（汕头价区）"]}, {"label": "", "cells": ["午间发电多半只抵谷价", "午间发电多半只抵谷价", "**白天发电多半抵峰价**"]}]}, {"type": "callout", "variant": "info", "icon": "receipt", "title": "10 千伏以上的工厂，按售电合同算", "text": "1656 号第三十五条：直接参与市场交易的用户，2026-03-01 起不再执行行政分时电价。江苏零售套餐峰、谷相对平段浮动不低于 60%。"}], "drawnBy": ["regions"], "sourced": true} as BinderBoardPage,
  "p06-pv-math": {"components": [{"type": "data_table", "columns": [{"key": "name", "label": "参数"}, {"key": "how", "label": ""}, {"key": "value", "label": "取值", "align": "right"}, {"key": "kind", "label": "来源性质"}], "rows": [{"cells": {"name": "E 年发电量", "how": "1 MW × 1080 小时，江苏竞价通知", "value": "108 万 kWh", "kind": "政策原文"}}, {"cells": {"name": "p 替代电价", "how": "江苏 2026 年 5 月 9-15 时均价", "value": "0.45 元/kWh", "kind": "媒体报道"}}, {"cells": {"name": "O 运维", "how": "0.046 元/W·年，CPIA 2024", "value": "4.6 万元/年", "kind": "行业协会"}}, {"cells": {"name": "I 投资", "how": "2.70 元/W，CPIA 2024", "value": "270 万元", "kind": "行业协会"}}]}, {"type": "kpi_cards", "items": [{"label": "年净收益", "value": "44.0 万元", "note": "E × p − O = 108 × 0.45 − 4.6"}, {"label": "静态回收", "value": "**6.1 年**", "note": "I ÷ 年净收益 = 270 ÷ 44.0"}]}, {"type": "callout", "variant": "info", "icon": "info", "text": "全部自用情景，未扣衰减、税费、融资和屋顶租金。贵司的账按电费单和售电合同重算。"}], "drawnBy": ["workings"], "sourced": true} as BinderBoardPage,
  "p07-sensitivity": {"components": [{"type": "chart", "chart_type": "bar", "direction": "horizontal", "axes": {"x_unit": "年"}, "series": [{"name": "江苏每 MW，静态回收", "data": [{"x": "全部自用，按平段 0.64 元", "y": 4.2, "note": "年净收益 64.5 万元"}, {"x": "全部自用，按 0.45 元", "y": 6.1, "note": "年净收益 44.0 万元", "emphasis": true}, {"x": "自用 58.46%，余电 0.391 元", "y": 6.5, "note": "年净收益 41.4 万元"}, {"x": "全部自用，按谷段 0.3828 元", "y": 7.3, "note": "年净收益 36.7 万元"}, {"x": "自用 58.46%，余电 0.25 元", "y": 7.7, "note": "年净收益 35.0 万元"}]}, {"name": "广东参照，企业口径", "data": [{"x": "1163 小时，按 0.803 元", "y": 3.0, "note": "年净收益 88.8 万元"}]}]}, {"type": "icon_cards", "items": [{"icon": "sun", "title": "白天自己用掉多少", "text": "江苏近三年平均自用 58.46%，其余送上网。自用越多，回本越快。"}, {"icon": "receipt", "title": "按什么电价算", "text": "自用的电抵 0.3828 到 0.64 元。余电机制电价竞价 0.25 到 0.391 元，不保证中标。"}]}, {"type": "callout", "variant": "warn", "title": "这些回收期都还没扣：", "text": "衰减、税费、融资成本、屋顶租金和逆变器更换。造价按直流侧、发电按交流侧计时，约再长四分之一。"}], "drawnBy": ["levers"], "sourced": true} as BinderBoardPage,
  "p08-storage-math": {"components": [{"type": "callout", "variant": "info", "text": "每次毛收益 = 1000 kWh × (放电价 − 充电价 ÷ 86.5%)", "tag": {"text": "效率 86.5%，CPIA"}}, {"type": "comparison", "title": "两部制 1-10 千伏，元/kWh", "columns": ["江苏 10 月", "广东汕头 9 月"], "rows": [{"label": "第 1 次", "cells": ["谷 0.3828 → 峰 0.9566：514.1 元", "谷 0.2635 → 峰 1.0827：778.1 元"]}, {"label": "第 2 次", "cells": ["谷 0.3828 → 平 0.6400：197.5 元", "平 0.6483 → 峰 1.0827：333.2 元"]}, {"label": "每天，两充两放", "emphasis": true, "cells": ["711.5 元", "1111.3 元 · 未计尖峰"]}, {"label": "一年运行 300 至 330 天", "cells": ["21.3 万至 23.5 万元", "33.3 万至 36.7 万元"]}]}, {"type": "callout", "variant": "warn", "icon": "triangle-alert", "title": "这是上限，不是收益", "text": "未扣运维、容量衰减、放电深度、业主分成和融资成本，运行天数是假设。回收期用贵司的负荷曲线逐项扣完再给。"}], "drawnBy": ["cycles"], "sourced": true} as BinderBoardPage,
  "p09-storage-discount": {"components": [{"type": "from_to", "from": {"title": "此前"}, "to": {"title": "现在"}, "rows": [{"icon": "arrow-down-up", "label": "江苏峰谷价差", "note": "CNESA 估算，426 号新政前后", "from": "约 0.85", "to": "约 0.65", "unit": "元/kWh", "tag": {"text": "降约 25%"}}, {"icon": "trending-up", "label": "2 小时系统中标价", "note": "CNESA，上半年均价，主要是大型储能", "from": "约 553", "to": "599.3", "unit": "元/kWh", "tag": {"text": "涨 8.3%"}}, {"icon": "clock", "label": "浙江储能回收期", "note": "NRDC 与 CNESA 估计，调价前后", "from": "5.4", "to": "9.1", "unit": "年", "tag": {"text": "研究机构估计"}, "emphasis": true}]}, {"type": "callout", "variant": "info", "icon": "trending-down", "text": "2026 年一季度用户侧储能新增同比降约 50%。补贴不计入：只查到已到期的地方临时补贴。"}], "drawnBy": ["drift"], "sourced": true} as BinderBoardPage,
  "p11-solution": {"components": [{"type": "image_grid", "emphasis": "first", "items": [{"asset_id": "grid-pv", "icon": "solar-panel", "caption": "屋顶光伏：按屋顶承重和白天负荷定容量，优先自己用掉"}, {"asset_id": "grid-ess", "icon": "battery-charging", "caption": "储能柜：按负荷曲线测算，扣完运维、衰减和分成后过线才装", "tag": {"text": "选配", "basis": "pending"}}, {"asset_id": "grid-switch", "icon": "plug-zap", "caption": "并网与配电：按电网接入意见改造，取得并网意见后才开工"}, {"asset_id": "om-worker", "icon": "hard-hat", "caption": "运维与能源管理：发电、自用、余电和节省逐月对账，报告给贵司"}]}], "drawnBy": ["parts"], "sourced": true} as BinderBoardPage,
  "p12-models": {"components": [{"type": "comparison", "columns": ["贵司自投", "合同能源管理（EMC）", "融资租赁"], "rows": [{"label": "", "cells": ["适合：资金充裕，想拿全部节省", "适合：不想占用资金 · **贵司出资 0 元**", "适合：想要资产，愿意分期"]}, {"label": "江苏每 MW 一年省", "emphasis": true, "cells": ["约 44.0 万元 · 节省全部归贵司", "约 12.9 万元 · 按 7.35 折结算，余电归投资方", "44.0 万元减租金 · 节省扣除租金后归贵司"]}, {"label": "谁出钱", "cells": ["贵司，约 270 万元/MW", "投资方，贵司不出钱", "融资方先付，贵司分期付租金"]}, {"label": "发电和设备风险", "cells": ["贵司承担", "投资方承担", "贵司承担"]}, {"label": "期满以后", "cells": ["资产一直归贵司", "公开样本 20 年后移交", "按租赁合同取得资产"]}]}, {"type": "callout", "variant": "info", "icon": "handshake", "text": "7.35 折、20 年是一家上市公司公告里的单个样本，不是行业标准。媒体报道江苏 EMC 折扣已从六折收窄到八折，贵司的折扣按贵司电价和屋顶条件谈。"}], "drawnBy": ["plans"], "sourced": true} as BinderBoardPage,
  "p13-references": {"components": [{"type": "data_table", "title": "均非我方项目", "columns": [{"key": "name", "label": ""}, {"key": "scale", "label": ""}, {"key": "num", "label": ""}], "rows": [{"icon": "factory", "cells": {"name": "深圳莱宝高科光明工厂", "scale": "光伏 2.541 MWp，EMC", "num": "预计年省约 62.90 万元"}, "tag": {"text": "企业口径"}}, {"icon": "factory", "cells": {"name": "常州钟楼金瑞达园区", "scale": "光伏约 1.6 MW", "num": "146.7 万 kWh，年省约 36 万元"}, "tag": {"text": "区政府发布"}}, {"icon": "battery-charging", "cells": {"name": "常州钟楼智谷工场", "scale": "光伏 0.9 MWp + 储能 1.33 MW", "num": "年化收益超过 20 万元"}, "tag": {"text": "区政府发布"}}, {"icon": "zap", "cells": {"name": "扬州高邮泰晶厂区", "scale": "光伏 4 万 kW + 储能 80.25 MWh", "num": "年省约 2000 万元"}, "tag": {"text": "供电公司口径"}}, {"icon": "file-check", "cells": {"name": "亿晶光电江苏四座电站", "scale": "0.81 至 3.49 MW", "num": "991 至 1098 小时，自用率 77.7% 至 91.0%"}, "tag": {"text": "会计师审计"}, "emphasis": "highlight"}]}, {"type": "callout", "variant": "tip", "icon": "lightbulb", "text": "参照只说明同类厂房做得成。贵司能省多少，按贵司的电费单、负荷曲线和屋顶条件算。"}], "drawnBy": ["precedents"], "sourced": true} as BinderBoardPage,
  "p14-safety": {"components": [{"type": "icon_cards", "title": "按什么做", "items": [{"icon": "shield-check", "title": "GB 44240-2024", "text": "2025-08-01 起实施。只选通过该标准检测的电池，检测报告交贵司存档。", "tag": {"text": "强制性国家标准", "settled": true}}, {"icon": "file-check", "title": "国能综通安全〔2025〕65 号", "text": "可研做安全论证，备案写明安全责任，竣工检查，投运后做安全后评价。"}]}, {"type": "icon_cards", "title": "公开事故的教训", "items": [{"icon": "flame", "tone": "danger", "title": "广州黄埔「6·14」事故", "text": "电池包测试时热失控后闪爆，1 人死亡。我们的做法：储能柜远离车间和通道，柜内可探测、排出可燃气体。"}, {"icon": "zap", "tone": "danger", "title": "深圳龙华储能柜起火", "text": "初步认定为充电过载导致电池发热。我们的做法：设充放电上限，过温、过流自动停机并告警。"}]}, {"type": "insight_panel", "title": "出了事谁负责", "icon": "scale", "rows": [{"label": "贵司自投", "text": "安全主体责任：贵司"}, {"label": "合同能源管理", "text": "安全主体责任：投资方"}, {"label": "设计、施工和运维", "text": "按合同由我们承担"}], "footnote": "备案时写明安全主体责任"}], "drawnBy": ["safeguards"], "sourced": true} as BinderBoardPage,
  "p15-risks": {"components": [{"type": "data_table", "columns": [{"key": "risk", "label": "风险"}, {"key": "basis", "label": "公开依据"}, {"key": "answer", "label": "我们的应对", "icon": "shield-check"}], "rows": [{"icon": "clock", "cells": {"risk": "电价时段再调整", "basis": "苏浙已把午间改为低谷，1656 号让市场化用户按合同定价", "answer": "容量以自用定，每年按最新电价和合同重算"}, "emphasis": "highlight"}, {"icon": "trending-down", "cells": {"risk": "余电上网价", "basis": "136 号文要求入市，江苏机制电价竞价 0.25-0.391 元/kWh，不保证中标", "answer": "少靠余电，余电按 0.25 元/kWh 做底线"}}, {"icon": "building-2", "cells": {"risk": "屋顶承重和产权", "basis": "7 号文第十七至十九条。判例：厂房转让后新业主不受原 EMC 约束", "answer": "踏勘做结构复核，合同写明转让、拆迁和补偿"}}, {"icon": "solar-panel", "cells": {"risk": "组件衰减", "basis": "衰减逐年减少发电，前面的测算还没扣", "answer": "合同写明衰减上限和质保，到货抽检"}}, {"icon": "plug-zap", "cells": {"risk": "接入容量不足", "basis": "7 号文：容量不足按申请顺序排队", "answer": "踏勘前先查所在县的可开放容量"}}]}], "drawnBy": ["remedies"], "sourced": true} as BinderBoardPage,
  "p16-roadmap": {"components": [{"type": "timeline", "milestones": [{"date": "第 1 步", "title": "踏勘", "desc": "查屋顶结构、配电房和接入点。交贵司确认：踏勘报告", "icon": "search"}, {"date": "第 2 步", "title": "方案与测算", "desc": "按贵司电费单和合同出账。交贵司确认：测算书", "icon": "calculator"}, {"date": "第 3 步", "title": "并网意见与备案", "desc": "取得并网意见后才开工。交贵司确认：并网意见和备案文件", "icon": "file-check", "source": "7 号文第十二、十七、二十六条", "highlight": true}, {"date": "第 4 步", "title": "施工", "desc": "结构、消防、防水达标。交贵司确认：竣工资料", "icon": "hard-hat", "source": "7 号文第十九条"}, {"date": "第 5 步", "title": "并网验收", "desc": "检验合格后投产。交贵司确认：并网检验报告", "icon": "plug-zap", "source": "7 号文第三十一条"}, {"date": "第 6 步", "title": "运维", "desc": "发电和节省每月对账。交贵司确认：月度运维报告", "icon": "wrench"}]}, {"type": "callout", "variant": "info", "icon": "clipboard-check", "title": "上储能的另加三道安全关：", "text": "可研安全论证 · 竣工安全检查 · 投运后安全后评价（65 号文）"}], "drawnBy": ["checkpoints"], "sourced": true} as BinderBoardPage,
  "p17-pricing": {"components": [{"type": "data_table", "title": "光伏主体 · 按瓦计价", "columns": [{"key": "item", "label": "报价项"}, {"key": "what", "label": "包含什么"}, {"key": "how", "label": "计价方式"}, {"key": "amount", "label": "金额（按踏勘结果出具）"}], "rows": [{"icon": "solar-panel", "cells": {"item": "组件", "what": "光伏组件", "how": "元/W", "amount": "— — —"}}, {"icon": "zap", "cells": {"item": "逆变器", "what": "组串式逆变器", "how": "元/W", "amount": "— — —"}}, {"icon": "hard-hat", "cells": {"item": "支架、电缆和建安", "what": "支架、直流交流电缆、安装施工", "how": "元/W", "amount": "— — —"}}]}, {"type": "data_table", "title": "按项单列 · 随现场条件", "columns": [{"key": "item", "label": "报价项"}, {"key": "what", "label": "包含什么"}, {"key": "how", "label": "计价方式"}, {"key": "amount", "label": "金额（按踏勘结果出具）"}], "rows": [{"icon": "server", "cells": {"item": "一次和二次设备", "what": "箱变、开关箱、预制舱、监控计量", "how": "按项", "amount": "— — —"}}, {"icon": "plug-zap", "cells": {"item": "电网接入", "what": "按电网接入意见改造", "how": "按项单列", "amount": "— — —"}}, {"icon": "building-2", "cells": {"item": "屋顶加固", "what": "按结构复核结果", "how": "按项单列", "amount": "— — —"}, "emphasis": "highlight", "tag": {"text": "不需要则为零"}}, {"icon": "landmark", "cells": {"item": "屋顶租赁和管理费用", "what": "租用他方屋顶的租金，设计和报批", "how": "按年，按项", "amount": "— — —"}}]}, {"type": "data_table", "title": "选配", "columns": [{"key": "item", "label": "报价项"}, {"key": "what", "label": "包含什么"}, {"key": "how", "label": "计价方式"}, {"key": "amount", "label": "金额（按踏勘结果出具）"}], "rows": [{"icon": "battery-charging", "cells": {"item": "储能", "what": "电池柜、变流器、消防和安全论证", "how": "元/kWh，测算过线才报", "amount": "— — —"}}]}], "drawnBy": ["quote"], "sourced": true} as BinderBoardPage,
  "p18-documents": {"components": [{"type": "icon_cards", "items": [{"icon": "receipt", "title": "近 12 个月电费单", "text": "用来：分时电量、需量电费和实际电价", "tag": {"text": "财务部门"}}, {"icon": "handshake", "title": "售电合同或代理购电确认", "text": "用来：10 千伏以上用户的真实峰谷价", "tag": {"text": "售电公司"}}, {"icon": "activity", "title": "15 分钟负荷曲线", "text": "用来：白天自用比例和储能充放时段", "tag": {"text": "电网或厂内计量"}}, {"icon": "ruler", "title": "屋顶结构图和产权证明", "text": "用来：复核承重，确认产权，签屋顶协议", "tag": {"text": "基建和法务"}}, {"icon": "plug-zap", "title": "变压器容量和配电系统图", "text": "用来：选接入点，核需量", "tag": {"text": "动力部门"}}, {"icon": "calendar", "title": "生产班次和停产检修计划", "text": "用来：算周末自用比例，排施工窗口", "tag": {"text": "生产部门"}}]}, {"type": "callout", "variant": "info", "text": "资料齐了，我们按贵司自己的电价出测算和踏勘报告。勾掉一份，测算里就少一个假设。"}], "drawnBy": ["papers"], "sourced": false} as BinderBoardPage,
}
