import type { Component, Slide } from "@/ir"

/*
 * clinic's 2026-10 board, its content pages p02 to p17 as the showcase deck
 * writes them (`showcase/clinic/zh`), less the heading and the source line,
 * which are the face's. Each page names the compositions that draw it in the
 * dossier setting, in the order they print.
 */

export interface DossierBoardPage {
  kicker: string
  tag?: NonNullable<Slide["tag"]>
  components: Component[]
  drawnBy: string[]
}

export const DOSSIER_BOARD_IMAGES = ["clinic-room", "nutrition", "pen", "pharmacist", "pharmacy"] as const

export const DOSSIER_BOARD: Record<string, DossierBoardPage> = {
  "p02-proposal": {"kicker": "提议", "components": [{"type": "numbered_cards", "items": [{"icon": "pill", "title": "品种：纳入替尔泊肽、诺和盈，玛仕度肽临时采购", "text": "两者中国人群和头对头证据最充分，诺和盈另有心血管结局证据", "sub": "依据见第 5 至 13 页", "emphasis": true}, {"icon": "hospital", "title": "范围：健康体重管理门诊、内分泌科、临床营养科", "text": "经院内培训考核授权的医师开具，药师专人做处方前置审核", "sub": "依据见第 14 页"}, {"icon": "clipboard-check", "title": "规则：按说明书门槛审核，减重适应证一律自费", "text": "按有效性、安全性、依从性三类指标监测，上线 6 个月首次复评", "sub": "依据见第 15 至 17 页"}]}], "drawnBy": ["rows"]} as DossierBoardPage,
  "p03-why-now": {"kicker": "背景", "components": [{"type": "kpi_cards", "items": [{"value": "全覆盖", "label": "三级公立综合医院 2026 年均提供健康体重管理门诊", "note": "国家卫健委 2026 年为民服务十件实事之三", "icon": "hospital", "tag": {"text": "官方文件", "evidence": "official"}}, {"value": "**约 80%**", "label": "替尔泊肽 2026 年 1 月 1 日起降价", "note": "10 mg 规格 4 周 4,758 元降到 936.70 元", "icon": "trending-down", "tag": {"text": "媒体报道", "evidence": "press"}}, {"value": "0 个", "label": "国产司美格鲁肽注射液获批", "note": "专利 2026 年 3 月到期，截至 9 月 8 日", "icon": "hourglass", "tag": {"text": "企业口径", "evidence": "company"}}]}, {"type": "chart", "chart_type": "stacked", "direction": "horizontal", "axes": {"y_unit": "%"}, "series": [{"name": "肥胖", "data": [{"x": "成人体重状况（2018 年）", "y": 16.4}], "emphasis": true}, {"name": "超重", "data": [{"x": "成人体重状况（2018 年）", "y": 34.3}], "emphasis": true}, {"name": "其他", "data": [{"x": "成人体重状况（2018 年）", "y": 49.3}]}]}], "drawnBy": ["readings"]} as DossierBoardPage,
  "p04-outside": {"kicker": "背景", "components": [{"type": "image", "asset_id": "pharmacy", "fit": "cover", "caption": "示意图：医院门诊药房（AI 生成）"}, {"type": "kpi_cards", "items": [{"icon": "siren", "source": "国家药监局 · 2024-09", "label": "货值", "value": "3,500 万元", "note": "生产销售含司美格鲁肽的假减肥药", "tone": "danger"}, {"icon": "siren", "source": "公安部 · 2025-03", "label": "涉案", "value": "2,200 余万元", "note": "上海非法减肥针案，窝点 15 处，抓获 40 人", "tone": "danger"}, {"icon": "landmark", "source": "国家医保局 · 2024-04", "label": "罚款", "value": "2 至 5 倍", "note": "代开减肥药涉嫌套取医保基金"}, {"icon": "badge-alert", "source": "国家药监局 · 2024-09", "label": "提示", "value": "严格限制", "note": "减重药「适用人群有严格限制」"}]}], "drawnBy": ["inset", "docket"]} as DossierBoardPage,
  "p05-china": {"kicker": "疗效", "components": [{"type": "chart", "chart_type": "bar", "direction": "horizontal", "axes": {"y_title": "试验 · 药物 · 例数和疗程", "x_title": "体重变化", "y_unit": "%"}, "series": [{"name": "药物组", "data": [{"x": "SURMOUNT-CN · 替尔泊肽 15 mg · 210 例 · 52 周", "y": -17.5}, {"x": "GLORY-1 · 玛仕度肽 6 mg · 610 例 · 48 周", "y": -14.01}, {"x": "STEP 12 · 司美格鲁肽 2.4 mg · 242 例 · 44 周", "y": -12.1}, {"x": "STEP 7 中国亚组 · 司美格鲁肽 2.4 mg · 300 例 · 44 周", "y": -11.8}], "emphasis": true}, {"name": "安慰剂组", "data": [{"x": "SURMOUNT-CN · 替尔泊肽 15 mg · 210 例 · 52 周", "y": -2.3}, {"x": "GLORY-1 · 玛仕度肽 6 mg · 610 例 · 48 周", "y": 0.3}, {"x": "STEP 12 · 司美格鲁肽 2.4 mg · 242 例 · 44 周", "y": -2.2}, {"x": "STEP 7 中国亚组 · 司美格鲁肽 2.4 mg · 300 例 · 44 周", "y": -3.5}]}]}, {"type": "kpi_cards", "items": [{"value": "15.2", "unit": "个百分点", "label": "SURMOUNT-CN", "note": "较安慰剂多减"}, {"value": "14.3", "unit": "个百分点", "label": "GLORY-1", "note": "较安慰剂多减"}, {"value": "9.9", "unit": "个百分点", "label": "STEP 12", "note": "较安慰剂多减"}, {"value": "8.3", "unit": "个百分点", "label": "STEP 7 中国亚组", "note": "较安慰剂多减"}]}], "drawnBy": ["controlled"]} as DossierBoardPage,
  "p06-h2h": {"kicker": "疗效", "tag": {"text": "RCT · NEJM 2025 · 751 例 · 72 周 · 开放标签", "evidence": "trial"}, "components": [{"type": "kpi_cards", "items": [{"value": "−20.2%", "label": "替尔泊肽", "note": "体重变化 · 腰围 −18.4 cm"}, {"value": "−13.7%", "label": "司美格鲁肽", "note": "体重变化 · 腰围 −13.0 cm"}]}, {"type": "chart", "chart_type": "bar", "axes": {"y_title": "减重达标比例", "y_unit": "%"}, "tag": {"text": "企业口径", "evidence": "company"}, "series": [{"name": "替尔泊肽", "data": [{"x": "减重 ≥10%", "y": 81.6}, {"x": "减重 ≥15%", "y": 64.6}, {"x": "减重 ≥20%", "y": 48.4}, {"x": "减重 ≥25%", "y": 31.6}]}, {"name": "司美格鲁肽", "data": [{"x": "减重 ≥10%", "y": 60.5}, {"x": "减重 ≥15%", "y": 40.1}, {"x": "减重 ≥20%", "y": 27.3}, {"x": "减重 ≥25%", "y": 16.1}]}]}, {"type": "data_table", "columns": [{"key": "m", "label": ""}, {"key": "t", "label": "替尔泊肽", "align": "right"}, {"key": "s", "label": "司美格鲁肽", "align": "right"}], "rows": [{"cells": {"m": "恶心", "t": "43.6%", "s": "44.4%"}}, {"cells": {"m": "呕吐", "t": "15.0%", "s": "21.3%"}}, {"cells": {"m": "因不良事件停药（企业口径）", "t": "6.1%", "s": "8.0%"}}]}], "drawnBy": ["duel"]} as DossierBoardPage,
  "p07-select": {"kicker": "心血管", "tag": {"text": "RCT · NEJM 2023 · 17,604 例 · 已有心血管病 · 无糖尿病", "evidence": "trial"}, "components": [{"type": "data_table", "columns": [{"key": "e", "label": "终点"}, {"key": "s", "label": "司美格鲁肽", "align": "right"}, {"key": "p", "label": "安慰剂", "align": "right"}, {"key": "hr", "label": "HR（95% CI）", "align": "right"}], "rows": [{"cells": {"e": "主要心血管不良事件", "s": "6.5%", "p": "8.0%", "hr": "0.80（0.72 至 0.90）"}, "emphasis": "highlight"}, {"cells": {"e": "心血管死亡", "s": "2.5%", "p": "3.0%", "hr": "0.85（0.71 至 1.01），未达统计学显著"}}, {"cells": {"e": "全因死亡", "s": "4.3%", "p": "5.2%", "hr": "0.81（0.71 至 0.93）"}}, {"cells": {"e": "心衰复合终点", "s": "3.4%", "p": "4.1%", "hr": "0.82（0.71 至 0.96）"}}]}, {"type": "callout", "variant": "warn", "icon": "hourglass", "text": "替尔泊肽的心血管结局试验 SURMOUNT-MMO 预计 2027 年 10 月完成，目前没有结果"}], "drawnBy": ["forest"]} as DossierBoardPage,
  "p08-safety": {"kicker": "安全性", "components": [{"type": "data_table", "title": "发生率", "columns": [{"key": "d", "label": "药物组"}, {"key": "n", "label": "恶心", "align": "right"}, {"key": "v", "label": "呕吐", "align": "right"}, {"key": "q", "label": "因不良反应停药", "align": "right"}], "rows": [{"cells": {"d": "司美格鲁肽 2.4 mg", "n": "44%", "v": "24%", "q": "6.8%"}, "tag": {"text": "美国标签", "evidence": "label"}}, {"cells": {"d": "安慰剂", "n": "16%", "v": "6%", "q": "3.2%"}}, {"cells": {"d": "替尔泊肽 15 mg", "n": "28%", "v": "13%", "q": "6.7%"}, "tag": {"text": "美国标签", "evidence": "label"}}, {"cells": {"d": "安慰剂", "n": "8%", "v": "2%", "q": "3.4%"}}, {"cells": {"d": "玛仕度肽 6 mg", "n": "50.5%", "v": "43.1%", "q": "1.0%"}, "emphasis": "highlight", "tag": {"text": "中国说明书", "evidence": "label"}}, {"cells": {"d": "安慰剂", "n": "5.9%", "v": "2.9%", "q": "1.0%"}}]}, {"type": "row_cards", "items": [{"icon": "shield-alert", "title": "甲状腺 C 细胞肿瘤", "text": "三药标签均有警示，甲状腺髓样癌或 MEN2 病史禁用", "tone": "danger"}, {"icon": "triangle-alert", "title": "胆囊胆道疾病", "text": "减重试验中 RR 2.29（76 项随机试验荟萃分析）", "tone": "warning"}, {"icon": "eye", "title": "缺血性视神经病变", "text": "EMA 2025 年 6 月列为司美格鲁肽非常罕见不良反应", "tone": "warning"}, {"icon": "bed", "title": "麻醉误吸", "text": "美国标签列入警告，围术期和胃肠镜前要评估", "tone": "warning"}]}], "drawnBy": ["multiples"]} as DossierBoardPage,
  "p09-rebound": {"kicker": "安全性", "tag": {"text": "RCT · JAMA 2024 · 先用药 36 周，再随机继续或换安慰剂", "evidence": "trial"}, "components": [{"type": "chart", "chart_type": "line", "axes": {"y_unit": "%"}, "series": [{"name": "继续用药", "data": [{"x": "第 0 周", "y": 0}, {"x": "第 36 周 · 随机分组", "y": -20.9}, {"x": "第 88 周", "y": -25.3}], "emphasis": true}, {"name": "换安慰剂", "data": [{"x": "第 0 周", "y": 0}, {"x": "第 36 周 · 随机分组", "y": -20.9}, {"x": "第 88 周", "y": -9.9}], "tone": "warning"}]}, {"type": "callout", "variant": "info", "text": "较第 36 周回升 14.0%"}, {"type": "kpi_cards", "items": [{"label": "STEP 4 · 司美格鲁肽", "value": "继续 −7.9%　换安慰剂 +6.9%", "note": "随机后 48 周，JAMA 2021"}, {"label": "STEP 1 延伸 · 司美格鲁肽", "value": "停药 1 年回升 11.6 个百分点", "note": "净减重只剩 5.6%"}, {"label": "BMJ 2026 荟萃分析", "value": "每月回升 0.4 kg", "note": "37 项研究，9,341 人"}]}, {"type": "callout", "variant": "warn", "icon": "trending-up", "text": "美国真实世界：约 2/3 患者 1 年内停药"}], "drawnBy": ["fork"]} as DossierBoardPage,
  "p10-approvals": {"kicker": "审批", "components": [{"type": "timeline", "lanes": ["减重适应证获批（药监局批准日）", "新增适应证、政策与专利"], "milestones": [{"date": "2023-06-30", "title": "利鲁平", "lane": "减重适应证获批（药监局批准日）", "desc": "利拉鲁肽"}, {"date": "2023-07-25", "title": "贝那鲁肽", "lane": "减重适应证获批（药监局批准日）"}, {"date": "2024-06-18", "title": "诺和盈", "lane": "减重适应证获批（药监局批准日）", "desc": "司美格鲁肽 2.4 mg"}, {"date": "2024-07-16", "title": "穆峰达", "lane": "减重适应证获批（药监局批准日）", "desc": "替尔泊肽"}, {"date": "2024-10-12", "title": "《肥胖症诊疗指南》印发", "lane": "新增适应证、政策与专利"}, {"date": "2025-06-24", "title": "信尔美", "lane": "减重适应证获批（药监局批准日）", "desc": "玛仕度肽"}, {"date": "2025-06-30", "title": "穆峰达增睡眠呼吸暂停", "lane": "新增适应证、政策与专利"}, {"date": "2025-12-16", "title": "诺和盈增心血管适应证", "lane": "新增适应证、政策与专利", "highlight": true}, {"date": "2026-01-01", "title": "新版医保目录执行", "lane": "新增适应证、政策与专利"}, {"date": "2026-03-03", "title": "先维盈", "lane": "减重适应证获批（药监局批准日）", "desc": "埃诺格鲁肽"}, {"date": "2026-03-20", "title": "司美格鲁肽专利到期", "lane": "新增适应证、政策与专利"}, {"date": "2026-09-08", "title": "诺和盈增 MASH", "lane": "新增适应证、政策与专利"}]}], "drawnBy": ["lanes"]} as DossierBoardPage,
  "p11-thresholds": {"kicker": "审批", "components": [{"type": "comparison", "title": "BMI", "columns": ["超重档，需至少 1 种合并症", "肥胖档"], "tag_column": "审核要点", "rows": [{"label": "诺和盈、利鲁平", "cells": ["27 至 <30，合并症", "≥30，肥胖档"], "tag": {"text": "门槛更高"}, "emphasis": true}, {"label": "穆峰达、信尔美", "cells": ["24 至 <28，合并症", "≥28，肥胖档"], "tag": {"text": "与指导原则一致", "quiet": true}}, {"label": "《体重管理指导原则》", "cells": ["24 至 <28，并发症", "≥28，干预 3 至 6 个月减重 <5%"], "tag": {"text": "用药参考", "quiet": true}}, {"label": "诺和盈心血管适应证", "cells": ["", "≥27，已确诊心血管病"], "tag": {"text": "单独核验"}}, {"label": "诺和盈用于 BMI 24 至 <28", "cells": ["24 至 <28，超说明书", ""], "tag": {"text": "超说明书", "tone": "danger"}}]}, {"type": "callout", "variant": "info", "text": "STEP 12 有中国 BMI 24 至 <28 人群数据，但诺和盈说明书门槛未改"}], "drawnBy": ["ruler"]} as DossierBoardPage,
  "p12-cost": {"kicker": "费用", "components": [{"type": "chart", "chart_type": "dumbbell", "axes": {"x_title": "4 周药费", "x_unit": "元"}, "series": [{"name": "调整前", "data": [{"x": "替尔泊肽 10 mg", "y": 4758}, {"x": "替尔泊肽 5 mg", "y": 2758}, {"x": "诺和盈 2.4 mg", "y": 2463}, {"x": "诺和盈 1.7 mg", "y": 1894}, {"x": "玛仕度肽 6 mg（零售）", "y": 2920}]}, {"name": "2026 年初", "data": [{"x": "替尔泊肽 10 mg", "y": 937}, {"x": "替尔泊肽 5 mg", "y": 551}, {"x": "诺和盈 2.4 mg", "y": 1284}, {"x": "诺和盈 1.7 mg", "y": 987}, {"x": "玛仕度肽 6 mg（零售）", "y": 2020}]}]}, {"type": "insight_panel", "icon": "receipt", "title": "医保只报 2 型糖尿病", "rows": [{"label": "2025 年版目录 · 替尔泊肽支付限制", "text": "「限成人2型糖尿病患者的血糖控制」"}, {"label": "《基本医疗保险用药管理暂行办法》第八条", "text": "「减肥、美容」等作用的药品不纳入目录"}], "footnote": "减重处方一律自费，玛仕度肽不在目录"}], "drawnBy": ["dumbbells"]} as DossierBoardPage,
  "p13-formulary": {"kicker": "建议", "components": [{"type": "comparison", "label_column": "药品", "columns": ["主要依据", "4 周药费"], "tag_column": "建议", "rows": [{"icon": "pill", "label": "替尔泊肽", "cells": ["头对头 −20.2%，中国人群 −17.5%，心血管结局 2027 年出", "551 至 937 元"], "tag": {"text": "纳入", "settled": true}, "emphasis": true}, {"icon": "pill", "label": "司美格鲁肽 2.4 mg", "cells": ["唯一有心血管结局证据，SELECT HR 0.80", "987 至 1,284 元"], "tag": {"text": "纳入", "settled": true}}, {"icon": "pill", "label": "玛仕度肽", "cells": ["中国人群 −14.01%，无心血管结局，恶心 50.5%", "约 2,020 元（零售）"], "tag": {"text": "临时采购"}}, {"icon": "pill", "label": "埃诺格鲁肽", "cells": ["说明书 BMI 门槛和价格未查到", "未查到"], "tag": {"text": "暂缓", "quiet": true}}, {"icon": "pill", "label": "利拉鲁肽、贝那鲁肽", "cells": ["疗效较弱：去除安慰剂后 5.4%，16 周 −6.0%", "利拉鲁肽约 1,550 元（30 天）"], "tag": {"text": "不纳入", "quiet": true, "settled": true}}]}], "drawnBy": ["table"]} as DossierBoardPage,
  "p14-scope": {"kicker": "管理", "components": [{"type": "image", "asset_id": "clinic-room", "fit": "cover", "caption": "示意图：体重管理门诊诊室（AI 生成）"}, {"type": "icon_cards", "items": [{"icon": "hospital", "title": "开具场所", "text": "体重管理门诊、内分泌科、临床营养科"}, {"icon": "user-check", "title": "处方权限", "text": "经院内培训考核授权的医师"}]}, {"type": "icon_cards", "items": [{"icon": "badge-check", "title": "审核药师", "text": "每个门诊至少 1 名专项培训药师"}, {"icon": "users", "title": "多学科随访", "text": "内分泌、营养、减重外科、药学"}]}], "drawnBy": ["inset", "cards"]} as DossierBoardPage,
  "p15-audit": {"kicker": "管理", "tag": {"text": "依据：中国药学会征求意见稿（2026-06）", "evidence": "draft"}, "components": [{"type": "steps", "items": [{"icon": "ruler", "title": "核门槛", "text": "BMI、合并症和体成分，按品种对照说明书", "tone": "danger"}, {"icon": "ban", "title": "排禁忌", "text": "甲状腺髓样癌或 MEN2 病史，妊娠和哺乳", "tone": "danger"}, {"icon": "pill", "title": "查相互作用", "text": "左甲状腺素钠、华法林、口服避孕药等"}, {"icon": "file-check", "title": "核超说明书", "text": "知情同意书和备案记录齐全"}, {"icon": "receipt", "title": "定结算", "text": "减重适应证自费，糖尿病按医保限定支付"}]}, {"type": "callout", "variant": "warn", "icon": "ban", "text": "拦截：存在禁忌、不符合说明书门槛，或因容貌焦虑求药"}, {"type": "callout", "variant": "info", "icon": "receipt-text", "text": "替尔泊肽的糖尿病和减重是同一产品、同一文号，系统要按诊断区分医保结算"}], "drawnBy": ["gate"]} as DossierBoardPage,
  "p16-pharmacist": {"kicker": "管理", "components": [{"type": "row_cards", "items": [{"icon": "clipboard-list", "title": "首诊评估", "text": "用 DAST-10 量表筛查药物滥用风险"}, {"icon": "scan-search", "title": "处方监测", "text": "识别频繁跨机构就诊、剂量异常递增"}, {"icon": "bed", "title": "围术期", "text": "麻醉和胃肠镜前评估误吸风险"}, {"icon": "baby", "title": "特殊人群", "text": "妊娠哺乳期禁用，育龄女性确认未孕"}]}, {"type": "image", "asset_id": "pharmacist", "fit": "cover", "caption": "示意图：药师在审方工作站（AI 生成）"}], "drawnBy": ["inset", "rows"]} as DossierBoardPage,
  "p17-monitoring": {"kicker": "监测", "components": [{"type": "row_cards", "items": [{"icon": "activity", "title": "有效性", "text": "最大耐受剂量 3 至 6 个月减重 ≥5% 的比例。不足 5% 评估停药"}, {"icon": "shield-check", "title": "安全性", "text": "胰腺炎、胆囊炎等严重不良事件。因不良反应停药率。瘦体重下降超 5% 的比例"}, {"icon": "calendar-check", "title": "依从性", "text": "6 个月治疗持续率。门诊随访依从率"}]}, {"type": "image", "asset_id": "nutrition", "fit": "cover"}, {"type": "timeline", "title": "复评节点", "milestones": [{"date": "上线", "title": "院内目录生效"}, {"date": "+6 个月", "title": "首次复评", "highlight": true}, {"date": "2027-04", "title": "司美格鲁肽数据保护到期"}, {"date": "2027-10", "title": "SURMOUNT-MMO 完成"}, {"date": "2027-12", "title": "医保协议到期"}]}], "drawnBy": ["watch"]} as DossierBoardPage,
}
