import type { Component } from "@/ir"

/*
 * luxe's 2026-10 board, its content pages as the showcase deck writes them
 * (`showcase/luxe/zh` and `showcase/luxe/en`), less the card stock's frame,
 * the occasion and the folio, which are the motif's. Each page names the
 * compositions that draw it in the invitation setting and carries the
 * page's chapter, claim, source and stamp (a composition places them). The
 * board's photographs are named for the assets the tests hand in
 * (`INVITATION_BOARD_IMAGES`).
 */

export interface InvitationBoardPage {
  heading: string
  kicker?: string
  components: Component[]
  footnote?: string
  stamp?: { text: string }
  drawnBy: string[]
}

export const INVITATION_BOARD_IMAGES = ["bangle", "filigree", "charms", "tray"] as const

export const INVITATION_BOARD: Record<string, InvitationBoardPage> = {
  "p02-agenda": {"heading": "今天讲四件事，最后一件请大家一起定", "components": [{"type": "numbered_cards", "items": [{"title": "金价", "text": "涨到了什么位置，高点之后回落了多少", "sub": "03"}, {"title": "顾客", "text": "首饰少了，金条金币多了，一口价和按克在回摆", "sub": "05"}, {"title": "行业", "text": "谁在关店，税改和纯度国标带来什么", "sub": "09"}, {"title": "我们", "text": "产品、定价、门店服务和金价风险，请大家一起定五件事", "sub": "13", "emphasis": true}]}], "drawnBy": ["programme"]} as InvitationBoardPage,
  "p03-price": {"heading": "金价七年涨到 3.3 倍，盘中最高到过 1,256 元/克", "components": [{"type": "chart", "chart_type": "bar", "reference": {"value": 1256, "label": "历史最高 1,256.00 · 2026-01-29 盘中"}, "series": [{"name": "中国黄金协会公布的年度均价", "data": [{"x": "2019", "y": 308.7}, {"x": "2020", "y": 388.13}, {"x": "2021", "y": 373.66}, {"x": "2022", "y": 390.58}, {"x": "2023", "y": 449.05}, {"x": "2024", "y": 548.49}]}, {"name": "按上金所 Au99.99 日行情计算", "data": [{"x": "2025", "y": 798.12}, {"x": "2026 年 1 至 9 月", "y": 1025.08}]}]}, {"type": "kpi_cards", "items": [{"value": "3.3", "unit": "×", "label": "2019 年均价 308.70 元/克\n2026 年 1 至 9 月均价 1,025.08 元/克", "note": "单位：元/克。倍数为计算"}]}], "footnote": "来源：中国黄金协会年度公告，上海黄金交易所 Au99.99 每日行情。2025 年起均价按日行情、用协会同一方法计算", "drawnBy": ["climb"]} as InvitationBoardPage,
  "p04-retreat": {"heading": "高点之后回落 27%，仍比去年均价高 14%", "components": [{"type": "kpi_cards", "items": [{"value": "−27%", "label": "9 月 30 日收盘 907.32 元/克，比最高收盘低 27%", "note": "仍比 2025 年均价 798.12 元/克（按日行情计算）高 14%"}]}, {"type": "chart", "chart_type": "line", "series": [{"name": "Au99.99 收盘价", "data": [{"x": "2026-01-29", "y": 1243.02, "note": "最高收盘"}, {"x": "2026-09-30", "y": 907.32, "note": "收盘"}]}, {"name": "2025 年全年均价", "data": [{"x": "2026-01-29", "y": 798.12}, {"x": "2026-09-30", "y": 798.12}]}]}], "footnote": "来源：上海黄金交易所 Au99.99 每日行情。单位：元/克。回落幅度和 2025 年均价为按日行情计算", "drawnBy": ["solo", "descent"]} as InvitationBoardPage,
  "p06-flip": {"heading": "金条金币第一次超过首饰，今年上半年已是首饰的 2.6 倍", "kicker": "第一章　顾客变了", "components": [{"type": "kpi_cards", "items": [{"value": "2.6", "unit": "×", "label": "2026 年上半年，金条金币用金是首饰的 2.6 倍", "note": "2025 年全年，金条金币第一次超过首饰"}]}, {"type": "chart", "chart_type": "bar", "direction": "horizontal", "axes": {"x_unit": "吨"}, "series": [{"name": "金条及金币", "data": [{"x": "2025 年", "y": 504.2}, {"x": "2026 年上半年", "y": 339.3}]}, {"name": "黄金首饰", "data": [{"x": "2025 年", "y": 363.8}, {"x": "2026 年上半年", "y": 132.1}]}]}], "footnote": "来源：中国黄金协会 2025 年度及 2026 年上半年黄金市场数据公告。中国黄金协会口径。倍数为计算", "drawnBy": ["solo", "doubles"]} as InvitationBoardPage,
  "p07-lighter": {"heading": "金饰用金一年少了四分之一，花的钱反而多了 8%", "kicker": "第一章　顾客变了", "components": [{"type": "kpi_cards", "items": [{"value": "360.1", "unit": "吨", "label": "2025 年", "note": "同比 −25%", "delta": "down", "tag": {"text": "用金量"}}, {"value": "136", "unit": "吨", "label": "2026 年上半年", "note": "同比 −30%", "delta": "down", "tag": {"text": "用金量"}}, {"value": "2,814", "unit": "亿元", "label": "2025 年", "note": "同比 +8%", "delta": "up", "tag": {"text": "消费金额"}}, {"value": "1,419", "unit": "亿元", "label": "2026 年上半年", "note": "同比 +2%", "delta": "up", "tag": {"text": "消费金额"}}]}, {"type": "callout", "variant": "info", "text": "世界黄金协会口径。消费金额是吨数乘以 Au9999 均价的估算，不含工费、品牌溢价和税，不等于门店收银额。不与中国黄金协会的吨数相加或相比"}], "footnote": "来源：世界黄金协会 2025 年及 2026 年上半年中国黄金市场回顾", "drawnBy": ["balance"]} as InvitationBoardPage,
  "p08-swing": {"heading": "一口价做上去了，金价一回落，按克计价又回来了", "kicker": "第一章　顾客变了", "components": [{"type": "row_cards", "items": [{"title": "周大福", "text": "定价首饰占内地零售值", "sub": "按克计价零售值同比 +21.0%"}, {"title": "六福", "text": "定价款占集团零售值", "sub": "按克黄金同店销量 +13%，由跌转升"}, {"title": "周生生", "text": "内地同店，2026 年上半年", "sub": "一口价同比 −20%，按克 +34%"}]}, {"type": "chart", "chart_type": "dumbbell", "title": "金价上行时", "axes": {"x_unit": "%"}, "series": [{"name": "上一财年", "data": [{"x": "周大福", "y": 30.6}]}, {"name": "本财年", "data": [{"x": "周大福", "y": 35.4}]}]}, {"type": "chart", "chart_type": "dumbbell", "title": "金价回落后", "axes": {"x_unit": "%"}, "series": [{"name": "去年 4 至 6 月", "data": [{"x": "周大福", "y": 34.0}, {"x": "六福", "y": 24}]}, {"name": "今年 4 至 6 月", "data": [{"x": "周大福", "y": 29.0}, {"x": "六福", "y": 18}]}]}, {"type": "paragraph", "text": "三家的期间和分母都不同，只比各家自己的方向，不互相比高低"}], "footnote": "来源：周大福 2026 财年业绩公告及季度经营数据，六福季度零售表现，周生生 2026 中期业绩公告。企业口径", "drawnBy": ["swing"]} as InvitationBoardPage,
  "p10-stores": {"heading": "上市同行大多在关店，逆势开店的是老铺和潮宏基", "kicker": "第二章　行业变了", "components": [{"type": "chart", "chart_type": "bar", "direction": "horizontal", "series": [{"name": "净关店", "data": [{"x": "周大福（内地零售点 · 2024-03 至 2026-06）", "y": -2123, "note": "7,170 → 5,047"}, {"x": "中国黄金（门店 · 2025 年）", "y": -925, "note": "4,236 → 3,311"}, {"x": "老凤祥（营销网点 · 2024 年末至 2026-06）", "y": -922, "note": "5,838 → 4,916"}, {"x": "六福（内地店铺 · 2025-03 至 2026-03）", "y": -299, "note": "3,179 → 2,880"}, {"x": "周生生（内地门店 · 2024 年末至 2026-06）", "y": -165, "note": "842 → 677"}]}, {"name": "净开店", "data": [{"x": "老铺黄金（自营门店 · 2024 年末至 2026-06）", "y": 9, "note": "36 → 45"}, {"x": "潮宏基（珠宝门店 · 2024 年末至 2026-06）", "y": 171, "note": "1,511 → 1,682"}]}]}], "footnote": "来源：各公司年报、中期报告及季度经营数据。企业口径，各家期间和门店口径不同，只看方向，不比大小", "drawnBy": ["ebb"]} as InvitationBoardPage,
  "p11-tax": {"heading": "每 100 元原料可抵税从约 11.50 元降到 6.00 元", "kicker": "第二章　行业变了", "components": [{"type": "from_to", "label_column": "做首饰用的提金，非投资用途", "from": {"kicker": "2025 年 10 月 31 日前", "title": "财税〔2002〕142 号"}, "to": {"kicker": "2025 年 11 月 1 日起", "title": "财政部 税务总局公告 2025 年第 11 号"}, "rows": [{"label": "拿到的发票", "from": "增值税专用发票", "to": "普通发票"}, {"label": "进项怎么算", "from": "按 13% 税率价税分离", "to": "发票金额 × 6%"}, {"label": "每 100 元原料可抵扣", "from": "约 11.50", "to": "6.00", "unit": "元", "change": "少抵约 5.50 元", "emphasis": true}]}], "footnote": "来源：财政部、税务总局，两份文件原文。可抵扣额按公告原文公式计算：100 × 13 ÷ 113，100 × 6%", "drawnBy": ["facing"]} as InvitationBoardPage,
  "p12-standard": {"heading": "纯度国标仍用 2012 版，新版还在批准", "kicker": "第二章　行业变了", "components": [{"type": "timeline", "milestones": [{"date": "2013-05", "title": "GB 11887-2012 实施", "desc": "强制性国标，现行"}, {"date": "2022-07", "title": "明码标价新规施行", "desc": "不得在标价之外加价"}, {"date": "2024-01", "title": "国标复审：修订"}, {"date": "2024-10", "title": "修订计划下达", "desc": "新名称加入「标识」"}, {"date": "2025-05", "title": "硬足金行标实施", "desc": "QB/T 5793-2024"}, {"date": "2026-10", "title": "新版仍在批准", "desc": "尚未发布", "status": "pending"}]}, {"type": "callout", "variant": "tip", "title": "现在怎么做", "text": "价签和凭证按现行要求，标清纯度、重量、计价方式和工费。新版发布后，总部统一给出价签和印记的改法"}], "footnote": "来源：国家标准信息公共服务平台（2026-10-07 查询），市场监管总局令第 56 号，行业标准信息服务平台", "drawnBy": ["lapse"]} as InvitationBoardPage,
  "p14-product": {"heading": "明年上新往三处走：古法金、设计款、小克重", "kicker": "第三章　我们一起做什么", "components": [{"type": "image_grid", "items": [{"asset_id": "bangle", "caption": "古法金：手工厚重，零售商的核心利润来源"}, {"asset_id": "filigree", "caption": "设计款：轻克重、设计感强、附加值高"}, {"asset_id": "charms", "caption": "小克重：10 克以内的产品占门店销量 **45%**"}]}], "footnote": "来源：世界黄金协会《2025 中国金饰零售市场洞察》（576 份店长反馈），中国黄金协会 2025 年上半年公告。图片为 AI 生成的示意图", "drawnBy": ["triptych"]} as InvitationBoardPage,
  "p15-pricing": {"heading": "定价两条腿走：设计和手艺走一口价，素金和金条按克卖", "kicker": "第三章　我们一起做什么", "components": [{"type": "comparison", "columns": ["一口价 · 按件定价", "按克计价"], "rows": [{"label": "放在哪些货上", "cells": ["设计款、古法金小件、工艺复杂的款", "素金、大克重足金、金条金币"]}, {"label": "金价上涨时", "cells": ["售价不随日金价变，占比上升", "售价跟着涨，顾客改买轻的"]}, {"label": "金价回落时", "cells": ["显得贵，占比回落，要按时复盘调价", "售价跟着降，先回暖"]}, {"label": "毛利从哪来", "cells": ["设计和工艺的溢价含在价里", "工费，金价部分基本透明"]}]}, {"type": "callout", "variant": "info", "title": "两条腿都要守的规矩", "text": "价签标清计价方式、重量、纯度和工费，不在标价之外加价，不收未标明的费用"}], "footnote": "依据：第 8 页三家上市公司的披露，老铺黄金招股书（产品推出时定价，不随原料小幅波动调整），市场监管总局令第 56 号", "drawnBy": ["mirror"]} as InvitationBoardPage,
  "p16-service": {"heading": "以旧换新和回收按标准做，\n金价风险先记清再对冲", "kicker": "第三章　我们一起做什么", "components": [{"type": "image", "asset_id": "tray", "fit": "cover"}, {"type": "icon_cards", "items": [{"icon": "repeat", "title": "以旧换新", "text": "约占首饰消费量两成。按行业团体标准做，凭证写清损耗和折价"}, {"icon": "recycle", "title": "回收", "text": "税改后售价含税、回收价不含，报价当着顾客算清"}, {"icon": "shield-check", "title": "金价风险", "text": "先把每家店的库存克重和金价敞口记清，再谈对冲"}]}], "footnote": "来源：中国黄金协会（2025-12-13，两成为不完全统计），世界黄金协会增值税解读（2025-11-07）。图片为 AI 生成的示意图", "drawnBy": ["vitrine"]} as InvitationBoardPage,
  "p17-decide": {"heading": "请与我们一起定的五件事", "kicker": "第三章　我们一起做什么", "components": [{"type": "row_cards", "items": [{"title": "上新结构", "text": "古法金、设计款、小克重在明年上新里各占多少，按区域分别定"}, {"title": "定价规则", "text": "哪些款走一口价、哪些按克，一口价多久复盘一次，金价变动多少就调"}, {"title": "以旧换新", "text": "是否全网按团体标准执行，验金设备和凭证模板由谁来出"}, {"title": "金价风险", "text": "每家店建金价敞口台账，总部是否对接黄金租赁和套保，经销商自愿参加"}, {"title": "税票和进货", "text": "提金用途和发票逐项核对，金条进货走哪条渠道"}]}], "stamp": {"text": "回执 · 敬请回复"}, "drawnBy": ["reply"]} as InvitationBoardPage,
}


/** The same pages in the English deck. */
export const INVITATION_BOARD_EN: Record<string, InvitationBoardPage> = {
  "p02-agenda": {"heading": "Four things today, the last we settle together", "components": [{"type": "numbered_cards", "items": [{"title": "Gold", "text": "How high it went, and how far it has fallen since", "sub": "03"}, {"title": "Customers", "text": "Less jewellery, more bars and coins, fixed prices and per-gram swinging", "sub": "05"}, {"title": "The trade", "text": "Who is closing stores, and what the tax change and purity standard bring", "sub": "09"}, {"title": "Us", "text": "Product, pricing, store service and gold risk, and five things to settle together", "sub": "13", "emphasis": true}]}], "drawnBy": ["programme"]} as InvitationBoardPage,
  "p03-price": {"heading": "Gold rose 3.3× in 7 years, peak 1,256 yuan/g", "components": [{"type": "chart", "chart_type": "bar", "reference": {"value": 1256, "label": "Record 1,256.00 · intraday, 29 Jan 2026"}, "series": [{"name": "Annual average, China Gold Association", "data": [{"x": "2019", "y": 308.7}, {"x": "2020", "y": 388.13}, {"x": "2021", "y": 373.66}, {"x": "2022", "y": 390.58}, {"x": "2023", "y": 449.05}, {"x": "2024", "y": 548.49}]}, {"name": "Calculated from SGE Au99.99 daily quotes", "data": [{"x": "2025", "y": 798.12}, {"x": "2026 Jan-Sep", "y": 1025.08}]}]}, {"type": "kpi_cards", "items": [{"value": "3.3", "unit": "×", "label": "2019 average 308.70 yuan/g\nJan-Sep 2026 average 1,025.08 yuan/g", "note": "In yuan per gram. The multiple is calculated"}]}], "footnote": "Source: China Gold Association annual releases, Shanghai Gold Exchange Au99.99 daily quotes. From 2025 the average is calculated from daily quotes by the association's own method", "drawnBy": ["climb"]} as InvitationBoardPage,
  "p04-retreat": {"heading": "27% off the high, still 14% above 2025's average", "components": [{"type": "kpi_cards", "items": [{"value": "−27%", "label": "30 Sep close 907.32 yuan/g, 27% below the record close", "note": "Still 14% above the 2025 average of 798.12 yuan/g (calculated from daily quotes)"}]}, {"type": "chart", "chart_type": "line", "series": [{"name": "Au99.99 close", "data": [{"x": "29 Jan 2026", "y": 1243.02, "note": "Record close"}, {"x": "30 Sep 2026", "y": 907.32, "note": "Close"}]}, {"name": "2025 full-year average", "data": [{"x": "29 Jan 2026", "y": 798.12}, {"x": "30 Sep 2026", "y": 798.12}]}]}], "footnote": "Source: Shanghai Gold Exchange Au99.99 daily quotes. In yuan per gram. The fall and the 2025 average are calculated from daily quotes", "drawnBy": ["solo", "descent"]} as InvitationBoardPage,
  "p06-flip": {"heading": "Bars and coins overtook jewellery, now 2.6× it", "kicker": "Chapter One · Our customers have changed", "components": [{"type": "kpi_cards", "items": [{"value": "2.6", "unit": "×", "label": "In H1 2026 bars and coins took 2.6 times the gold jewellery did", "note": "In 2025 bars and coins passed jewellery for the first time"}]}, {"type": "chart", "chart_type": "bar", "direction": "horizontal", "axes": {"x_unit": "t"}, "series": [{"name": "Bars and coins", "data": [{"x": "2025", "y": 504.2}, {"x": "H1 2026", "y": 339.3}]}, {"name": "Gold jewellery", "data": [{"x": "2025", "y": 363.8}, {"x": "H1 2026", "y": 132.1}]}]}], "footnote": "Source: China Gold Association market data for 2025 and H1 2026. China Gold Association basis. The multiple is calculated", "drawnBy": ["solo", "doubles"]} as InvitationBoardPage,
  "p07-lighter": {"heading": "A quarter less gold in jewellery, 8% more spent", "kicker": "Chapter One · Our customers have changed", "components": [{"type": "kpi_cards", "items": [{"value": "360.1", "unit": "t", "label": "2025", "note": "Down 25%", "delta": "down", "tag": {"text": "Gold used"}}, {"value": "136", "unit": "t", "label": "H1 2026", "note": "Down 30%", "delta": "down", "tag": {"text": "Gold used"}}, {"value": "281.4", "unit": "bn yuan", "label": "2025", "note": "Up 8%", "delta": "up", "tag": {"text": "Money spent"}}, {"value": "141.9", "unit": "bn yuan", "label": "H1 2026", "note": "Up 2%", "delta": "up", "tag": {"text": "Money spent"}}]}, {"type": "callout", "variant": "info", "text": "World Gold Council basis. Spending is tonnes times the average Au9999 price, an estimate without labour charges, brand premiums or tax, not what tills took in. Not added to or set against the China Gold Association's tonnes"}], "footnote": "Source: World Gold Council, China gold market reviews for 2025 and H1 2026", "drawnBy": ["balance"]} as InvitationBoardPage,
  "p08-swing": {"heading": "Fixed prices climbed, then per-gram came back", "kicker": "Chapter One · Our customers have changed", "components": [{"type": "row_cards", "items": [{"title": "Chow Tai Fook", "text": "Fixed-price share of mainland retail value", "sub": "Per-gram retail value up 21.0%"}, {"title": "Luk Fook", "text": "Fixed-price share of group retail value", "sub": "Per-gram same-store volume up 13%, back from a fall"}, {"title": "Chow Sang Sang", "text": "Mainland same-store, H1 2026", "sub": "Fixed price down 20%, per gram up 34%"}]}, {"type": "chart", "chart_type": "dumbbell", "title": "While gold rose", "axes": {"x_unit": "%"}, "series": [{"name": "FY2025", "data": [{"x": "Chow Tai Fook", "y": 30.6}]}, {"name": "FY2026", "data": [{"x": "Chow Tai Fook", "y": 35.4}]}]}, {"type": "chart", "chart_type": "dumbbell", "title": "After gold fell", "axes": {"x_unit": "%"}, "series": [{"name": "Apr-Jun 2025", "data": [{"x": "Chow Tai Fook", "y": 34.0}, {"x": "Luk Fook", "y": 24}]}, {"name": "Apr-Jun 2026", "data": [{"x": "Chow Tai Fook", "y": 29.0}, {"x": "Luk Fook", "y": 18}]}]}, {"type": "paragraph", "text": "Each company reports its own period and base, so read each one's direction and do not rank them"}], "footnote": "Source: Chow Tai Fook FY2026 results and quarterly update, Luk Fook quarterly retail update, Chow Sang Sang 2026 interim results. Company figures", "drawnBy": ["swing"]} as InvitationBoardPage,
  "p10-stores": {"heading": "Most peers close stores, Laopu and CHJ open more", "kicker": "Chapter Two · The trade has changed", "components": [{"type": "chart", "chart_type": "bar", "direction": "horizontal", "series": [{"name": "Net closures", "data": [{"x": "Chow Tai Fook (mainland POS · Mar 2024 to Jun 2026)", "y": -2123, "note": "7,170 → 5,047"}, {"x": "China Gold (stores · 2025)", "y": -925, "note": "4,236 → 3,311"}, {"x": "Lao Feng Xiang (outlets · end 2024 to Jun 2026)", "y": -922, "note": "5,838 → 4,916"}, {"x": "Luk Fook (mainland · Mar 2025 to Mar 2026)", "y": -299, "note": "3,179 → 2,880"}, {"x": "Chow Sang Sang (mainland · end 2024 to Jun 2026)", "y": -165, "note": "842 → 677"}]}, {"name": "Net openings", "data": [{"x": "Laopu Gold (own stores · end 2024 to Jun 2026)", "y": 9, "note": "36 → 45"}, {"x": "CHJ (jewellery stores · end 2024 to Jun 2026)", "y": 171, "note": "1,511 → 1,682"}]}]}], "footnote": "Source: company annual, interim and quarterly reports. Company figures with different periods and store definitions, so read direction, not size", "drawnBy": ["ebb"]} as InvitationBoardPage,
  "p11-tax": {"heading": "VAT credit per 100 yuan: about 11.50 to 6.00", "kicker": "Chapter Two · The trade has changed", "components": [{"type": "from_to", "label_column": "Gold drawn for jewellery, not investment", "from": {"kicker": "Until 31 Oct 2025", "title": "Caishui [2002] No. 142"}, "to": {"kicker": "From 1 Nov 2025", "title": "MOF and STA Announcement 2025 No. 11"}, "rows": [{"label": "Invoice received", "from": "Special VAT invoice", "to": "Ordinary invoice"}, {"label": "Input VAT counted as", "from": "13% backed out of price", "to": "Invoice amount × 6%"}, {"label": "Credit per 100 yuan of gold", "from": "About 11.50", "to": "6.00", "unit": "yuan", "change": "About 5.50 yuan less", "emphasis": true}]}], "footnote": "Source: Ministry of Finance and State Taxation Administration, both documents in full. Credit calculated by the announcement's formulas: 100 × 13 ÷ 113, 100 × 6%", "drawnBy": ["facing"]} as InvitationBoardPage,
  "p12-standard": {"heading": "Purity rules date from 2012, new ones pending", "kicker": "Chapter Two · The trade has changed", "components": [{"type": "timeline", "milestones": [{"date": "2013-05", "title": "GB 11887-2012 in force", "desc": "Mandatory, still current"}, {"date": "2022-07", "title": "Price-marking rules", "desc": "No charges beyond the tag"}, {"date": "2024-01", "title": "Review: revise it"}, {"date": "2024-10", "title": "Revision planned", "desc": "Name adds labelling"}, {"date": "2025-05", "title": "Hard-gold standard", "desc": "QB/T 5793-2024"}, {"date": "2026-10", "title": "Still in approval", "desc": "Not yet published", "status": "pending"}]}, {"type": "callout", "variant": "tip", "title": "What to do now", "text": "Tags and receipts follow the current rules and show purity, weight, pricing method and labour charge. Once the new version is out, head office issues one set of changes to tags and hallmarks"}], "footnote": "Source: National Public Service Platform for Standards Information (checked 7 Oct 2026), SAMR Order No. 56, industry standards information platform", "drawnBy": ["lapse"]} as InvitationBoardPage,
  "p14-product": {"heading": "New lines go three ways: heritage, design, light", "kicker": "Chapter Three · What we do together", "components": [{"type": "image_grid", "items": [{"asset_id": "bangle", "caption": "Heritage: Heavy, hand-made, a core profit"}, {"asset_id": "filigree", "caption": "Design: Light, distinctive, higher value"}, {"asset_id": "charms", "caption": "Light: Under 10 g, **45%** of units sold"}]}], "footnote": "Source: World Gold Council China gold jewellery retail insights 2025 (576 store managers), China Gold Association H1 2025 release. AI-generated illustrations", "drawnBy": ["triptych"]} as InvitationBoardPage,
  "p15-pricing": {"heading": "Fixed price for craft, by weight for plain gold", "kicker": "Chapter Three · What we do together", "components": [{"type": "comparison", "columns": ["Fixed price · per piece", "By weight"], "rows": [{"label": "Which pieces", "cells": ["Design, small heritage, complex work", "Plain gold, heavy pieces, bars, coins"]}, {"label": "When gold rises", "cells": ["Price holds, its share rises", "Price follows, buyers go lighter"]}, {"label": "When gold falls", "cells": ["Looks dear, review and reprice", "Price follows, recovers first"]}, {"label": "Margin from", "cells": ["Design and craft in the price", "Labour charge, gold at cost"]}]}, {"type": "callout", "variant": "info", "title": "Rules for both", "text": "tags show pricing method, weight, purity and labour charge, and nothing is charged beyond the tag"}], "footnote": "Basis: disclosures on page 8, Laopu Gold prospectus (priced at launch, not moved by small swings in gold), SAMR Order No. 56", "drawnBy": ["mirror"]} as InvitationBoardPage,
  "p16-service": {"heading": "Trade-ins to standard,\ngold risk logged first", "kicker": "Chapter Three · What we do together", "components": [{"type": "image", "asset_id": "tray", "fit": "cover"}, {"type": "icon_cards", "items": [{"icon": "repeat", "title": "Trade-ins", "text": "About a fifth of jewellery demand. Follow the industry standard, and receipts state loss and discount"}, {"icon": "recycle", "title": "Buybacks", "text": "Since the tax change, prices include VAT and buybacks do not. Work the quote out in front of the customer"}, {"icon": "shield-check", "title": "Gold risk", "text": "Log each store's gold by weight and its price exposure first, then talk about hedging"}]}], "footnote": "Source: China Gold Association (13 Dec 2025, a fifth is an incomplete count), World Gold Council VAT explainer (7 Nov 2025). AI-generated illustration", "drawnBy": ["vitrine"]} as InvitationBoardPage,
  "p17-decide": {"heading": "Five things we would like to settle with you", "kicker": "Chapter Three · What we do together", "components": [{"type": "row_cards", "items": [{"title": "New-line mix", "text": "How much heritage, design and light pieces in next year's lines, by region"}, {"title": "Pricing rules", "text": "Which pieces are fixed-price, how often to review, and what move in gold triggers a change"}, {"title": "Trade-ins", "text": "One standard in every store, and who supplies the testing kit and receipt forms"}, {"title": "Gold risk", "text": "An exposure ledger in every store, and leasing and hedging for dealers who opt in"}, {"title": "Tax and sourcing", "text": "Check each withdrawal's use and invoice, and which channel bars come through"}]}], "stamp": {"text": "Reply · RSVP"}, "drawnBy": ["reply"]} as InvitationBoardPage,
}
