import type { Component } from "@/ir"

/*
 * stage's 2026-10 board, its content pages as the showcase deck writes them
 * (`showcase/stage/zh` and `showcase/stage/en`), less the clicker, which is
 * the motif's. Each page names the composition that draws it in the keynote
 * setting and carries the page's chapter, claim and source (a composition
 * places them). The board's photograph is named for the asset the tests hand
 * in (`KEYNOTE_BOARD_IMAGES`).
 */

export interface KeynoteBoardPage {
  heading: string
  kicker?: string
  components: Component[]
  footnote?: string
  drawnBy: string[]
}

export const KEYNOTE_BOARD_IMAGES: readonly string[] = ["studio"]

export const KEYNOTE_BOARD: Record<string, KeynoteBoardPage> = {
  "p02-peak": {"heading": "国内收入还在涨，\n到顶的是**人数**", "components": [{"type": "paragraph", "text": "2025 年收入增长 7.68%，用户只增长 1.35%"}], "footnote": "来源：游戏工委《2025 年中国游戏产业报告》", "drawnBy": ["hush"]} as KeynoteBoardPage,
  "p03-users": {"heading": "2018 年到 2025 年，七年里国内游戏用户只多了", "components": [{"type": "kpi_cards", "items": [{"value": "5,700", "unit": "万", "label": "2018 年　6.26 亿 → 2025 年　6.83 亿"}]}], "footnote": "来源：游戏工委 2018、2025 年《中国游戏产业报告》。差值为计算", "drawnBy": ["giant"]} as KeynoteBoardPage,
  "p05-trend": {"heading": "出海十年放大近 4 倍，中间跌过两年", "kicker": "第一章　出海", "components": [{"type": "chart", "chart_type": "line", "axes": {"y_unit": "亿美元"}, "series": [{"name": "自研游戏海外实际销售收入", "data": [{"x": "2015", "y": 53.1}, {"x": "2016", "y": 72.3}, {"x": "2017", "y": 82.8}, {"x": "2018", "y": 95.9}, {"x": "2019", "y": 115.9}, {"x": "2020", "y": 154.5}, {"x": "2021", "y": 180.13}, {"x": "2022", "y": 173.46}, {"x": "2023", "y": 163.66, "note": "2022、2023 连跌两年"}, {"x": "2024", "y": 185.57}, {"x": "2025", "y": 204.55}]}]}, {"type": "kpi_cards", "items": [{"value": "3.85", "unit": "倍", "label": "年均约 14.4%"}]}], "footnote": "来源：游戏工委 2015 至 2025 年《中国游戏产业报告》。倍数与年均增速为计算", "drawnBy": ["contour"]} as KeynoteBoardPage,
  "p06-faster": {"heading": "今年上半年，出海增速是国内的 2.5 倍", "kicker": "第一章　出海", "components": [{"type": "kpi_cards", "items": [{"value": "**30.22%**", "label": "出海", "note": "自研游戏海外收入 123.72 亿美元"}, {"value": "12.17%", "label": "国内", "note": "国内游戏收入 1,884.5 亿元"}]}], "footnote": "来源：游戏工委《2026 年 1-6 月中国游戏产业报告》。倍数为计算：30.22 ÷ 12.17。只比增速，不比规模", "drawnBy": ["faceoff"]} as KeynoteBoardPage,
  "p07-map": {"heading": "日本在变小，欧洲在变大", "kicker": "第一章　出海", "components": [{"type": "from_to", "from": {"title": "2025 年上半年"}, "to": {"title": "2026 年上半年"}, "rows": [{"label": "美国", "from": "31.96", "to": "32.31", "unit": "%"}, {"label": "日本", "from": "16.20", "to": "14.05", "unit": "%"}, {"label": "德英法合计", "from": "8.78", "to": "10.14", "unit": "%", "emphasis": true}, {"label": "韩国", "from": "7.47", "to": "7.48", "unit": "%"}]}], "footnote": "来源：游戏工委 2025、2026 年《1-6 月中国游戏产业报告》。自研移动游戏海外收入占比", "drawnBy": ["tilt"]} as KeynoteBoardPage,
  "p08-genre": {"heading": "出海手游一半的钱来自策略类，和国内是两张榜", "kicker": "第一章　出海", "components": [{"type": "chart", "title": "出海", "chart_type": "bar", "direction": "horizontal", "axes": {"x_unit": "%"}, "series": [{"name": "海外收入前 100 的自研手游", "data": [{"x": "策略", "y": 49.96, "emphasis": true}, {"x": "射击", "y": 9.69}, {"x": "角色扮演", "y": 9.39}]}]}, {"type": "chart", "title": "国内", "chart_type": "bar", "direction": "horizontal", "axes": {"x_unit": "%"}, "series": [{"name": "国内收入前 100 的手游", "data": [{"x": "多人在线战术竞技", "y": 19.45}, {"x": "射击", "y": 18.29}, {"x": "角色扮演", "y": 15.1}]}]}], "footnote": "来源：游戏工委《2025 年中国游戏产业报告》。分母分别是海外、国内收入前 100 的手游", "drawnBy": ["podiums"]} as KeynoteBoardPage,
  "p10-wukong": {"heading": "《黑神话：悟空》发售不到 4 天，全平台卖出", "components": [{"type": "kpi_cards", "items": [{"value": "1,000", "unit": "万套", "label": "开发商口径"}]}], "footnote": "来源：开发商公告，经澎湃新闻转引（2024 年 8 月 23 日）", "drawnBy": ["giant"]} as KeynoteBoardPage,
  "p11-peaks": {"heading": "同样是国产动作大作，峰值能差几百倍", "kicker": "第二章　单机", "components": [{"type": "chart", "chart_type": "bar", "direction": "horizontal", "series": [{"name": "Steam 历史同时在线峰值", "data": [{"x": "黑神话：悟空", "y": 2415714}, {"x": "明末：渊虚之羽", "y": 131518}, {"x": "失落之魂", "y": 3070, "emphasis": true}]}]}, {"type": "paragraph", "text": "最高和最低相差约 **787 倍**　这是同时在线人数，不是销量"}, {"type": "paragraph", "text": "今年上半年国内主机游戏收入 9.61 亿元，下降 7.06%。协会给的原因：《黑神话：悟空》降温，后续新品跟进不足"}], "footnote": "来源：SteamDB，经互联网档案馆快照（2025-12 至 2026-08），游戏工委 2026 年半年报告。倍数为计算", "drawnBy": ["gulf"]} as KeynoteBoardPage,
  "p12-steam": {"heading": "平常月份，Steam 用户里选简体中文客户端的比例", "kicker": "第二章　单机", "components": [{"type": "kpi_cards", "items": [{"value": "约 ¼", "label": "去掉每年 2 月的冲高，平均 24.2%。统计的是客户端语言，不是国籍"}]}], "footnote": "来源：Valve《Steam 硬件和软件调查》。平均值为计算，一个点约 1%", "drawnBy": ["crowd"]} as KeynoteBoardPage,
  "p13-small": {"heading": "小团队，\n也有自己的路", "kicker": "第二章　单机", "components": [{"type": "image", "asset_id": "studio", "fit": "cover"}, {"type": "kpi_cards", "items": [{"value": "300 万份+", "label": "《逃离鸭科夫》首月内，发行方口径"}, {"value": "301,322", "label": "《逃离鸭科夫》Steam 历史峰值"}, {"value": "5 人团队", "label": "《戴森球计划》抢先体验 4 天 20 万份"}]}], "footnote": "来源：哔哩哔哩 2025 年三季度业绩会，SteamDB 档案馆快照 2026-08，《戴森球计划》发行方新闻稿。左图为 AI 生成", "drawnBy": ["tower"]} as KeynoteBoardPage,
  "p15-cost": {"heading": "出海最贵的不是研发，是流量", "kicker": "第三章　押注", "components": [{"type": "chart", "chart_type": "bar", "axes": {"y_unit": "元"}, "series": [{"name": "每 100 元营业收入里，2025 年", "data": [{"x": "销售费用", "y": 48.6, "emphasis": true}, {"x": "研发费用", "y": 4.3}]}]}, {"type": "paragraph", "text": "一家出海做得多的上市游戏公司，销售费用是研发费用的 11 倍多"}, {"type": "callout", "variant": "info", "title": "年报原话", "text": "销售费用下降，「主要系报告期内互联网流量费用减少」"}], "footnote": "来源：三七互娱《2025 年年度报告》。每 100 元营收占比和倍数为计算，销售费用为集团口径", "drawnBy": ["toll"]} as KeynoteBoardPage,
  "p16-limits": {"heading": "出海要过三道门：版号、合规、本地化", "kicker": "第三章　押注", "components": [{"type": "kpi_cards", "items": [{"icon": "ticket", "label": "版号", "value": "1,525", "unit": "个", "note": "今年 1 至 9 月国产游戏版号，月均约 169 个。进口只有 46 个。只在海外发行不需要国内版号"}, {"icon": "shield-check", "label": "合规", "value": "4%", "note": "欧盟 GDPR 最高罚全球营业额的 4%。韩国强制公示抽卡概率，海外公司也要"}, {"icon": "languages", "label": "本地化", "value": "一成", "note": "德英法合计已占出海手游收入一成。本地化没有行业统一单价，账要自己算"}]}], "footnote": "来源：国家新闻出版署审批名单，官方名单现存数（2026-10-08 计数），欧盟 GDPR 原文，韩国文化体育观光部，游戏工委 2026 年半年报告", "drawnBy": ["arches"]} as KeynoteBoardPage,
  "p17-bets": {"heading": "下一个十年，我押这五件事", "kicker": "第三章　押注", "components": [{"type": "numbered_cards", "items": [{"title": "押留存，不押拉新", "text": "用户五年都在 6.64 亿到 6.84 亿之间"}, {"title": "押美国，把欧洲当第二主场", "text": "美国稳在三成，德英法升到一成"}, {"title": "押新玩法，别只靠策略类的惯性", "text": "合成类一年涨了 9.74 个百分点"}, {"title": "押 PC 和主机，按小团队的规模算账", "text": "天花板有人摸到，3,070 的峰值也是真的"}, {"title": "押合规和本地化的完成度", "text": "先定在哪运营，再定过哪几道门"}]}], "footnote": "来源：游戏工委历年《中国游戏产业报告》，SteamDB", "drawnBy": ["slate"]} as KeynoteBoardPage,
}

export const KEYNOTE_BOARD_EN: Record<string, KeynoteBoardPage> = {
  "p02-peak": {"heading": "Revenue is still growing.\n**Players** have peaked.", "components": [{"type": "paragraph", "text": "2025: revenue up 7.68%, players up only 1.35%"}], "footnote": "Source: CADPA, China Game Industry Report 2025", "drawnBy": ["hush"]} as KeynoteBoardPage,
  "p03-users": {"heading": "From 2018 to 2025, players in China grew by only", "components": [{"type": "kpi_cards", "items": [{"value": "57", "unit": "million", "label": "2018　626 million → 2025　683 million"}]}], "footnote": "Source: CADPA, China Game Industry Reports 2018 and 2025. Difference calculated", "drawnBy": ["giant"]} as KeynoteBoardPage,
  "p05-trend": {"heading": "Ten years abroad: nearly 4 times, two down years", "kicker": "Act one　Abroad", "components": [{"type": "chart", "chart_type": "line", "axes": {"y_unit": "US$ bn"}, "series": [{"name": "Overseas revenue of China-developed games", "data": [{"x": "2015", "y": 5.31}, {"x": "2016", "y": 7.23}, {"x": "2017", "y": 8.28}, {"x": "2018", "y": 9.59}, {"x": "2019", "y": 11.59}, {"x": "2020", "y": 15.45}, {"x": "2021", "y": 18.013}, {"x": "2022", "y": 17.346}, {"x": "2023", "y": 16.366, "note": "Down in 2022 and 2023"}, {"x": "2024", "y": 18.557}, {"x": "2025", "y": 20.455}]}]}, {"type": "kpi_cards", "items": [{"value": "3.85×", "label": "about 14.4% a year"}]}], "footnote": "Source: CADPA, China Game Industry Reports 2015 to 2025. Multiple and annual growth calculated", "drawnBy": ["contour"]} as KeynoteBoardPage,
  "p06-faster": {"heading": "This half, abroad grew 2.5 times as fast as home", "kicker": "Act one　Abroad", "components": [{"type": "kpi_cards", "items": [{"value": "**30.22%**", "label": "Overseas", "note": "US$12.372 billion from China-developed games"}, {"value": "12.17%", "label": "China", "note": "RMB 188.45 billion in domestic revenue"}]}], "footnote": "Source: CADPA, China Game Industry Report, January to June 2026. Ratio calculated: 30.22 ÷ 12.17. Growth rates only, not size", "drawnBy": ["faceoff"]} as KeynoteBoardPage,
  "p07-map": {"heading": "Japan is shrinking, Europe is growing", "kicker": "Act one　Abroad", "components": [{"type": "from_to", "from": {"title": "H1 2025"}, "to": {"title": "H1 2026"}, "rows": [{"label": "United States", "from": "31.96", "to": "32.31", "unit": "%"}, {"label": "Japan", "from": "16.20", "to": "14.05", "unit": "%"}, {"label": "Germany, UK, France", "from": "8.78", "to": "10.14", "unit": "%", "emphasis": true}, {"label": "South Korea", "from": "7.47", "to": "7.48", "unit": "%"}]}], "footnote": "Source: CADPA, January to June reports 2025 and 2026. Shares of overseas revenue of China-developed mobile games", "drawnBy": ["tilt"]} as KeynoteBoardPage,
  "p08-genre": {"heading": "Strategy earns half abroad. Home is another list", "kicker": "Act one　Abroad", "components": [{"type": "chart", "title": "Abroad", "chart_type": "bar", "direction": "horizontal", "axes": {"x_unit": "%"}, "series": [{"name": "top 100 China-developed mobile games", "data": [{"x": "Strategy", "y": 49.96, "emphasis": true}, {"x": "Shooter", "y": 9.69}, {"x": "RPG", "y": 9.39}]}]}, {"type": "chart", "title": "At home", "chart_type": "bar", "direction": "horizontal", "axes": {"x_unit": "%"}, "series": [{"name": "top 100 mobile games in China", "data": [{"x": "MOBA", "y": 19.45}, {"x": "Shooter", "y": 18.29}, {"x": "RPG", "y": 15.1}]}]}], "footnote": "Source: CADPA, China Game Industry Report 2025. Shares of revenue within each top 100", "drawnBy": ["podiums"]} as KeynoteBoardPage,
  "p10-wukong": {"heading": "Black Myth: Wukong, all platforms, under 4 days", "components": [{"type": "kpi_cards", "items": [{"value": "10", "unit": "million copies", "label": "Developer's figure"}]}], "footnote": "Source: developer's announcement, via The Paper, August 23, 2024", "drawnBy": ["giant"]} as KeynoteBoardPage,
  "p11-peaks": {"heading": "Same genre, peaks hundreds of times apart", "kicker": "Act two　Premium", "components": [{"type": "chart", "chart_type": "bar", "direction": "horizontal", "series": [{"name": "Steam all-time concurrent peak", "data": [{"x": "Black Myth: Wukong", "y": 2415714}, {"x": "Wuchang: Fallen Feathers", "y": 131518}, {"x": "Lost Soul Aside", "y": 3070, "emphasis": true}]}]}, {"type": "paragraph", "text": "Top and bottom about **787 times** apart　Players online at once, not sales"}, {"type": "paragraph", "text": "Console game revenue in China fell 7.06% to RMB 961 million in H1 2026. CADPA blames Black Myth cooling off and too few follow-ups"}], "footnote": "Source: SteamDB via Internet Archive snapshots (December 2025 to August 2026), CADPA H1 2026 report. Multiple calculated", "drawnBy": ["gulf"]} as KeynoteBoardPage,
  "p12-steam": {"heading": "Steam users on the Simplified Chinese client", "kicker": "Act two　Premium", "components": [{"type": "kpi_cards", "items": [{"value": "1 in 4", "label": "Roughly, in a normal month: Februaries removed, the average is 24.2%. It counts the client's language, not nationality"}]}], "footnote": "Source: Valve, Steam Hardware & Software Survey. Average calculated, one dot is about 1%", "drawnBy": ["crowd"]} as KeynoteBoardPage,
  "p13-small": {"heading": "Small teams have\na road of their own", "kicker": "Act two　Premium", "components": [{"type": "image", "asset_id": "studio", "fit": "cover"}, {"type": "kpi_cards", "items": [{"value": "3 million+", "label": "Escape from Duckov, first month, publisher's figure"}, {"value": "301,322", "label": "Escape from Duckov, Steam all-time peak"}, {"value": "5 people", "label": "Dyson Sphere Program: 200,000 in 4 days of early access"}]}], "footnote": "Source: Bilibili Q3 2025 earnings call, SteamDB snapshot August 2026, Dyson Sphere Program publisher's release. Photo AI-generated", "drawnBy": ["tower"]} as KeynoteBoardPage,
  "p15-cost": {"heading": "Abroad, the big bill is traffic, not development", "kicker": "Act three　Bets", "components": [{"type": "chart", "chart_type": "bar", "series": [{"name": "Out of every RMB 100 of revenue, 2025", "data": [{"x": "Selling", "y": 48.6, "emphasis": true}, {"x": "R&D", "y": 4.3}]}]}, {"type": "paragraph", "text": "At one listed game company that sells a lot abroad, selling expenses ran more than 11 times R&D"}, {"type": "callout", "variant": "info", "title": "From its annual report", "text": "selling expenses fell \"mainly because internet traffic costs fell\""}], "footnote": "Source: 37 Interactive Entertainment, 2025 Annual Report. Shares of revenue and multiple calculated, selling expenses are group-wide", "drawnBy": ["toll"]} as KeynoteBoardPage,
  "p16-limits": {"heading": "Three gates: licences, compliance, localization", "kicker": "Act three　Bets", "components": [{"type": "kpi_cards", "items": [{"icon": "ticket", "label": "Licences", "value": "1,525", "note": "Domestic game licences, January to September 2026, about 169 a month. Only 46 for imports. Overseas-only releases need none"}, {"icon": "shield-check", "label": "Compliance", "value": "4%", "note": "GDPR fines reach 4% of global turnover. Korea makes foreign firms disclose gacha odds too"}, {"icon": "languages", "label": "Localization", "value": "A tenth", "note": "Germany, UK and France are now a tenth of mobile revenue abroad. No industry price list, so do your own math"}]}], "footnote": "Source: National Press and Publication Administration lists as they stand (counted October 8, 2026), GDPR, Korea MCST, CADPA H1 2026 report", "drawnBy": ["arches"]} as KeynoteBoardPage,
  "p17-bets": {"heading": "My five bets for the next decade", "kicker": "Act three　Bets", "components": [{"type": "numbered_cards", "items": [{"title": "Retention, not acquisition", "text": "Players flat at 664 to 684 million for five years"}, {"title": "The US, with Europe as a second home", "text": "US near a third, Europe's big three up to a tenth"}, {"title": "New mechanics, not strategy's inertia", "text": "Merge games up 9.74 points in a year"}, {"title": "PC and console, run like a small team", "text": "The ceiling is real, so is a 3,070 peak"}, {"title": "Compliance and localization, finished", "text": "Pick your markets, then your gates"}]}], "footnote": "Source: CADPA annual reports, SteamDB", "drawnBy": ["slate"]} as KeynoteBoardPage,
}
