import type { Component, Slide } from "@/ir"

/*
 * homeroom's 2026-10 board, its content pages p02 to p20 as the showcase deck
 * writes them (`showcase/homeroom/zh`), less the heading, the step's label,
 * the course strip and the source line, which are the face's. Each page names
 * the composition that draws it in the lesson setting.
 */

export interface LessonBoardPage {
  components: Component[]
  ballot?: NonNullable<Slide["ballot"]>
  drawnBy: string[]
}

export const LESSON_BOARD_IMAGES = ["classroom", "quiz-hand", "quiz-pair", "method-desk", "method-board", "method-redpen"] as const

export const LESSON_BOARD: Record<string, LessonBoardPage> = {
  "p02-goals": {"components": [{"type": "image", "asset_id": "classroom", "fit": "cover", "caption": "示意图：培训教室（AI 生成）"}, {"type": "icon_cards", "items": [{"icon": "list-checks", "title": "会挑任务", "text": "说得出 AI 在哪类活上真帮忙，在哪类活上会帮倒忙", "tag": {"text": "环节一"}}, {"icon": "shield-alert", "title": "会避开风险", "text": "认得出泄露信息、编造事实、版权、对外标识四类风险", "tag": {"text": "环节二"}}, {"icon": "clipboard-check", "title": "会照规则做", "text": "按公司的六条规则用 AI，交出去之前用三个方法把关", "tag": {"text": "环节三"}}]}, {"type": "callout", "variant": "tip", "text": "下课前回到这页，在三个方框里打勾"}], "drawnBy": ["objectives"]} as LessonBoardPage,
  "p03-agenda": {"components": [{"type": "roadmap", "duration_unit": "分钟", "items": [{"period": "环节一", "title": "它在哪儿帮忙，哪儿帮倒忙", "icon": "lightbulb", "duration": 15, "points": ["四项研究", "两种帮倒忙"], "checkpoint": "小测一", "rows": [{"label": "目标", "value": "会挑任务"}]}, {"period": "环节二", "title": "三个真实案例", "icon": "gavel", "duration": 7, "points": ["三星、律师、航空公司", "47 国员工调查"], "rows": [{"label": "目标", "value": "会避开风险"}]}, {"period": "环节三", "title": "我们的规则和方法", "icon": "clipboard-check", "duration": 15, "points": ["六条规则", "三个方法"], "checkpoint": "小测二", "rows": [{"label": "目标", "value": "会照规则做"}], "emphasis": true}, {"period": "小结", "title": "板书和课后练习", "icon": "notebook-pen", "duration": 5, "points": ["八个关键词", "课后三道题"], "rows": [{"label": "目标", "value": "三个目标回顾"}]}]}, {"type": "callout", "variant": "tip", "icon": "hand", "text": "课堂约定：随时举手提问。两次小测可以和旁边的同事商量。"}], "drawnBy": ["syllabus"]} as LessonBoardPage,
  "p05-helps": {"components": [{"type": "kpi_cards", "items": [{"icon": "pencil-line", "label": "写作：用时", "value": "**−40%**", "note": "质量评分同时高 18%", "source": "453 名专业人员", "tag": {"text": "同行评审 · 《科学》2023", "evidence": "trial"}}, {"icon": "headset", "label": "客服：每小时解决的问题", "value": "+15%", "note": "一家企业的客服团队", "source": "5,172 名客服", "tag": {"text": "同行评审 · 《经济学季刊》2025", "evidence": "trial"}}, {"icon": "briefcase", "label": "做方案：能力范围内的任务", "value": "快 25.1%", "note": "完成量还多 12.2%", "source": "咨询顾问，18 项任务", "tag": {"text": "工作论文 · 哈佛商学院 2023", "evidence": "preprint"}}, {"icon": "users", "label": "团队：一个人用 AI，赶上两人团队", "value": "1 人 ≈ 2 人", "note": "用时还少 16.4%", "source": "776 名员工做新产品方案", "tag": {"text": "工作论文 · NBER 2025", "evidence": "preprint"}}]}, {"type": "callout", "variant": "warn", "icon": "info", "text": "四项研究的人群、任务和单位都不同，不能直接比较，也不能相加。"}], "drawnBy": ["studies"]} as LessonBoardPage,
  "p06-novice": {"components": [{"type": "comparison", "columns": ["原本较弱的一组", "原本较强的一组"], "rows": [{"label": "客服，5,172 人", "cells": ["技能最低的五分之一：+36%", "技能最高的五分之一：几乎没变，质量略降"]}, {"label": "咨询顾问", "cells": ["低于平均水平：+43%", "高于平均水平：+17%"]}]}, {"type": "callout", "variant": "info", "text": "两项研究的分组口径不同：客服按技能五等分，咨询按平均水平上下分"}, {"type": "insight_panel", "title": "上手速度", "rows": [{"label": "用 AI 两个月的新人", "text": "2 个月"}, {"label": "不用 AI、干了六个月以上的人", "text": "6 个月以上"}], "footnote": "表现相当"}, {"type": "callout", "variant": "tip", "icon": "graduation-cap", "text": "对新同事，它像一位随时在旁边的带教老师。对老手，提速有限，要盯住质量。"}], "drawnBy": ["cohorts"]} as LessonBoardPage,
  "p07-backfire": {"components": [{"type": "insight_panel", "icon": "triangle-alert", "title": "超出它能力范围的任务", "rows": [{"label": "怎么测的", "text": "顾问做一项 AI 能力范围外的分析任务"}], "footnote": "看着一样难的任务，可能一个在它能力内，一个在外。没把握的活，先拿答案已知的例子试一次。"}, {"type": "chart", "chart_type": "bar", "direction": "horizontal", "axes": {"x_title": "正确率", "x_unit": "%"}, "tag": {"text": "工作论文 · 哈佛商学院 2023", "evidence": "preprint"}, "series": [{"name": "正确率", "data": [{"x": "不用 AI", "y": 84.5}, {"x": "用 AI", "y": 60, "upper": 70, "emphasis": true}]}]}, {"type": "insight_panel", "icon": "file-warning", "title": "它编出来的内容", "rows": [{"label": "怎么测的", "text": "让 108 个模型只摘要给定的原文"}], "footnote": "只给原文，要求找不到就答「待确认」"}, {"type": "chart", "chart_type": "bar", "direction": "horizontal", "axes": {"x_unit": "%"}, "tag": {"text": "厂商测评 · Vectara 2026-09", "evidence": "company"}, "series": [{"name": "编造的比例", "data": [{"x": "加进原文没有的内容的摘要比例（108 个模型）", "y": 1.8, "upper": 24.2, "emphasis": true}, {"x": "专业法律研究工具的幻觉率", "y": 17, "upper": 33}]}]}, {"type": "callout", "variant": "tip", "icon": "user-check", "text": "两种情况，靠的是同一道保险：交出去之前，由人来核对。"}], "drawnBy": ["diptych"]} as LessonBoardPage,
  "p08-feeling": {"components": [{"type": "chart", "chart_type": "bar", "direction": "horizontal", "axes": {"x_title": "完成任务的用时变化，负数为更快", "x_unit": "%"}, "series": [{"name": "用时变化", "data": [{"x": "开发者事前预期", "y": -24}, {"x": "经济学专家预测", "y": -39}, {"x": "机器学习专家预测", "y": -38}, {"x": "开发者事后自评", "y": -20}, {"x": "实际测得", "y": 19, "emphasis": true}]}]}, {"type": "kpi_cards", "items": [{"icon": "gauge", "value": "**39**", "unit": "个百分点", "label": "自评和实测之差", "note": "试新用法时，记下用时和返工，别只问感觉。", "tag": {"text": "工作论文 · METR 2025-07", "evidence": "preprint"}}]}], "drawnBy": ["estimates"]} as LessonBoardPage,
  "p09-quiz1": {"components": [{"type": "image", "asset_id": "quiz-hand", "fit": "cover", "caption": "示意图：课堂（AI 生成）"}, {"type": "row_cards", "items": [{"title": "情景一", "text": "新同事用公司批准的 AI 工具，把自己写的周报润色一遍，读过再交"}, {"title": "情景二", "text": "一位老同事让 AI 算出三个季度的同比增长率，没核对就放进给领导的汇报"}, {"title": "情景三", "text": "一位主管觉得用 AI 写方案快多了，要求部门所有活都先交给 AI 做"}]}], "drawnBy": ["quiz"], "ballot": {"choices": ["可以", "不行", "先别急"]}} as LessonBoardPage,
  "p10-answer1": {"components": [{"type": "row_cards", "items": [{"title": "情景一：可以", "text": "新同事用公司批准的 AI 工具，把自己写的周报润色一遍，读过再交", "sub": "写作是它擅长的活，新人获益最大。交之前自己读一遍。见第 5、6 页", "tone": "success"}, {"title": "情景二：不行", "text": "一位老同事让 AI 算出三个季度的同比增长率，没核对就放进给领导的汇报", "sub": "算数和核对事实可能超出它的能力。数字发出前要人核对。见第 7 页", "tone": "danger"}, {"title": "情景三：先别急", "text": "一位主管觉得用 AI 写方案快多了，要求部门所有活都先交给 AI 做", "sub": "感觉快不等于真的快。先挑几类活试，记下用时和返工。见第 8 页", "tone": "warning"}]}, {"type": "callout", "variant": "info", "text": "判断的顺序：先问是不是它擅长的活，再问结果谁来核，最后看数字再推广。"}], "drawnBy": ["answers"]} as LessonBoardPage,
  "p12-cases": {"components": [{"type": "comparison", "columns": ["发生了什么", "谁担了后果", "出处"], "rows": [{"label": "三星", "icon": "file-warning", "tag": {"text": "2023-03 至 05", "quiet": true}, "cells": ["放开公共 AI 工具不到 20 天，员工把源码和会议记录贴了进去，出了 3 起泄露", "公司禁止员工用生成式 AI", "韩国《经济学人》、彭博"]}, {"label": "律师", "icon": "gavel", "tag": {"text": "2023-06-22", "quiet": true}, "cells": ["交了 AI 编造的判例，被质疑后仍坚持", "罚 5,000 美元，法院认定主观恶意", "纽约南区联邦法院"]}, {"label": "航空公司", "icon": "plane", "tag": {"text": "2024-02-14", "quiet": true}, "cells": ["网站客服机器人说丧亲票可以事后申请，实际不行", "判赔 812.02 加元，「机器人是独立主体」没被采纳", "加拿大民事解决庭"]}]}, {"type": "callout", "variant": "info", "icon": "message-square-quote", "text": "律师案的法官写得很清楚：用可靠的 AI 工具本身没有不当，把关核实是律师的责任。"}, {"type": "kpi_cards", "items": [{"value": "**2,145**", "label": "起法庭裁决涉及 AI 编造的内容（截至 2026-10-04）"}]}], "drawnBy": ["cases"]} as LessonBoardPage,
  "p13-habits": {"components": [{"type": "chart", "chart_type": "bar", "direction": "horizontal", "axes": {"x_title": "在工作中用 AI 的员工里，承认做过的比例", "x_unit": "%"}, "tag": {"text": "企业调查 · 员工自报 · 47 国 32,352 人", "evidence": "company"}, "series": [{"name": "承认做过", "data": [{"x": "知道能靠 AI，就少花力气", "y": 72}, {"x": "不加评估就用 AI 的输出", "y": 66}, {"x": "隐瞒用了 AI，或当成自己写的", "y": 57}, {"x": "因为 AI 在工作中犯过错", "y": 56}, {"x": "不知道是否允许就用了", "y": 56}, {"x": "把公司信息传进公共 AI 工具", "y": 48, "emphasis": true}]}]}, {"type": "callout", "variant": "info", "icon": "ban", "title": "传过公司信息的员工，按公司政策分", "text": "光靠禁令不管用，要给工具、给规则、给培训。"}, {"type": "chart", "chart_type": "bar", "direction": "horizontal", "axes": {"x_unit": "%"}, "series": [{"name": "传过公司信息", "data": [{"x": "明令禁用 AI", "y": 67, "emphasis": true}, {"x": "有使用政策", "y": 56}, {"x": "没有政策", "y": 33}]}]}], "drawnBy": ["ranking"]} as LessonBoardPage,
  "p15-rules": {"components": [{"type": "icon_cards", "items": [{"icon": "lock", "title": "一、分级使用", "text": "个人信息、商业秘密和未公开的经营材料，不放进公共 AI 工具", "tag": {"text": "个保法 · 数安法", "basis": "law"}}, {"icon": "shield-check", "title": "二、只用批准的工具", "text": "用公司批准的工具和公司账号，不用个人账号处理工作", "tag": {"text": "个保法第 21 条", "basis": "law"}}, {"icon": "user-check", "title": "三、人来复核", "text": "事实、数字、引用、代码和对外承诺，发出前由人核对", "tag": {"text": "治理框架 6.3.1", "basis": "law"}}, {"icon": "badge-info", "title": "四、对外标识", "text": "对外发布 AI 生成的内容，主动声明，不删改标识", "tag": {"text": "标识办法第 10 条", "basis": "law"}}, {"icon": "history", "title": "五、留存记录", "text": "留着提示词、草稿和修改记录，版权有争议时拿得出来", "tag": {"text": "张家港法院判例", "basis": "law"}}, {"icon": "siren", "title": "六、出错就报", "text": "传错了信息、用错了内容，马上报告，不悄悄改", "tag": {"text": "数安法第 29 条", "basis": "law"}}]}], "drawnBy": ["rules"]} as LessonBoardPage,
  "p16-grading": {"components": [{"type": "pyramid", "layers": [{"label": "个人信息、商业秘密", "tone": "danger"}, {"label": "内部资料", "tone": "warning"}, {"label": "公开信息", "tone": "success"}]}, {"type": "icon_cards", "items": [{"icon": "lock", "title": "不放进公共 AI 工具", "text": "例如：客户名单和电话、源代码、报价、未公开的财务数据"}, {"icon": "shield-check", "title": "只在公司批准的工具里用", "text": "例如：内部流程、会议安排、不含个人信息的草稿"}, {"icon": "globe", "title": "可以交给公司批准的工具", "text": "例如：官网文章、已发布的报告、公开的法规"}]}], "drawnBy": ["tiers"]} as LessonBoardPage,
  "p17-methods": {"components": [{"type": "image_grid", "items": [{"asset_id": "method-desk", "caption": "给足资料：贴上资料，要求只用这些", "icon": "file-text"}, {"asset_id": "method-board", "caption": "讲清规矩：没有就答「待确认」，分清原文和推断", "icon": "message-square-quote"}, {"asset_id": "method-redpen", "caption": "逐条核对：打开原文，一条条对", "icon": "pencil-line"}]}, {"type": "callout", "variant": "tip", "title": "最管用的一句", "text": "资料里找不到答案时，请回答「待确认」，不要自己补。"}], "drawnBy": ["methods"]} as LessonBoardPage,
  "p18-quiz2": {"components": [{"type": "image", "asset_id": "quiz-pair", "fit": "cover", "caption": "示意图：课堂（AI 生成）"}, {"type": "row_cards", "items": [{"title": "情景一", "text": "把客户投诉邮件连同姓名、手机号，贴进个人账号的免费 AI 写回复"}, {"title": "情景二", "text": "用 AI 生成一张活动海报，发到公司公众号之前，把角上的 AI 标识裁掉了"}, {"title": "情景三", "text": "发现自己上周把一份带客户名单的表格贴进了公共 AI，想着没人知道就算了"}]}], "drawnBy": ["quiz"], "ballot": {"choices": ["可以", "不行", "先别急"]}} as LessonBoardPage,
  "p19-answer2": {"components": [{"type": "row_cards", "items": [{"title": "情景一：不行", "text": "把客户投诉邮件连同姓名、手机号，贴进个人账号的免费 AI 写回复", "sub": "规则一、二：个人信息不进公共工具，只用批准的工具", "tone": "danger"}, {"title": "情景二：不行", "text": "用 AI 生成一张活动海报，发到公司公众号之前，把角上的 AI 标识裁掉了", "sub": "规则四：对外发布要主动声明，不得删改标识", "tone": "danger"}, {"title": "情景三：不行", "text": "发现自己上周把一份带客户名单的表格贴进了公共 AI，想着没人知道就算了", "sub": "规则六：马上报告，越早补救损失越小。这一题最容易做错", "tone": "danger"}]}, {"type": "callout", "variant": "info", "text": "报告不是认错，是让公司来得及补救。"}], "drawnBy": ["answers"]} as LessonBoardPage,
  "p20-recap": {"components": [{"type": "row_cards", "items": [{"icon": "list-checks", "title": "挑任务 · 看数字", "text": "写、改、归纳交给它，推广之前记下用时和返工"}, {"icon": "lock", "title": "先分级 · 用批准的", "text": "个人信息、商业秘密不进公共工具，只用公司批准的工具", "highlight": true}, {"icon": "user-check", "title": "人来核 · 对外标", "text": "事实、数字、引用发出前核对，对外发布主动声明"}, {"icon": "siren", "title": "留记录 · 错就报", "text": "留着提示词和草稿，出了错马上报告"}]}, {"type": "callout", "variant": "tip", "text": "回到第 2 页：三个目标，打勾了吗？"}], "drawnBy": ["blackboard"]} as LessonBoardPage,
}
