import type { Component } from "@/ir"

/*
 * runway's 2026-10 board, its content pages as the showcase deck writes them
 * (`showcase/runway/zh` and `showcase/runway/en`), less the running order's
 * masthead, which is the motif's. Each page names the composition that draws
 * it in the lineup setting and carries the page's claim and source (a
 * composition places them). The chapter's row of looks (`LINEUP_PARADE`) is
 * drawn by `parade` in the band the chapter face hands it. The board's
 * photographs are named for the assets the tests hand in
 * (`LINEUP_BOARD_IMAGES`).
 */

export interface LineupBoardPage {
  heading: string
  kicker?: string
  components: Component[]
  footnote?: string
  drawnBy: string[]
}

export const LINEUP_BOARD_IMAGES: readonly string[] = ["gradient", "hero", "look0203", "look04", "look0507", "mood-fray", "mood-ghost", "mood-indigo", "mood-knee", "mood-mend", "mood-seam", "panels", "samples", "sort", "unpick"]

export const LINEUP_BOARD: Record<string, LineupBoardPage> = {
  "p02-agenda": {"heading": "答辩分五段：从一条旧裤子讲到一个系列", "kicker": "出场顺序", "components": [{"type": "numbered_cards", "items": [{"icon": "factory", "title": "为什么是旧牛仔", "text": "旧纺织品的规模，一条牛仔裤的水"}, {"icon": "palette", "title": "灵感", "text": "把磨白、褶痕和口袋印当成图案"}, {"icon": "scissors", "title": "面料", "text": "拆线、分档、拼接，做出新面料"}, {"icon": "shirt", "title": "系列", "text": "七个造型，按色阶从深走到浅", "emphasis": true}, {"icon": "scale", "title": "边界", "text": "做到了什么，做不到什么"}]}], "drawnBy": ["order"]} as LineupBoardPage,
  "p03-why": {"heading": "旧衣不缺，\n缺的是让它**再被用一次**的办法", "kicker": "为什么是旧牛仔", "components": [{"type": "kpi_cards", "items": [{"value": "约 2200", "unit": "万吨", "label": "2020 年全国废旧纺织品产生量，当年循环利用率约 20%"}, {"value": "25%　30%", "label": "国家定下的 2025 年、2030 年循环利用率目标"}, {"value": "易拆解", "label": "同一份文件要求提高纺织品易拆解、易分类、易回收性"}]}], "footnote": "来源：发改委等《关于加快推进废旧纺织品循环利用的实施意见》（发改环资〔2022〕526 号），发改委网站专家解读（2022 年 4 月）", "drawnBy": ["standfirst"]} as LineupBoardPage,
  "p04-cost": {"heading": "一条牛仔裤在被剪开之前，已经付过一次水的代价", "kicker": "为什么是旧牛仔", "components": [{"type": "kpi_cards", "items": [{"value": "**3,781**", "unit": "升", "label": "一条 Levi's 501 从棉田到报废的净耗水", "source": "Levi's 生命周期评估，2015，企业口径"}, {"value": "10,850", "unit": "升", "label": "每 1000 克牛仔裤的全球平均虚拟水", "source": "Chapagain 等，UNESCO-IHE，2005"}]}, {"type": "paragraph", "text": "两套算法口径不同：一个按一条裤子的全生命周期，一个按每千克的虚拟水。并排看，不相加，不比大小"}], "footnote": "来源：Levi Strauss & Co.《The Life Cycle of a Jean》（2015），Chapagain 等《The water footprint of cotton consumption》（2005）", "drawnBy": ["duet"]} as LineupBoardPage,
  "p06-mood": {"heading": "情绪板：把磨损当成图案", "kicker": "灵感", "components": [{"type": "image_grid", "items": [{"asset_id": "mood-ghost", "caption": "口袋印"}, {"asset_id": "mood-knee", "caption": "膝盖磨白"}, {"asset_id": "mood-seam", "caption": "明线卷边"}, {"asset_id": "mood-fray", "caption": "毛边"}, {"asset_id": "mood-mend", "caption": "补丁"}, {"asset_id": "mood-indigo", "caption": "靛蓝色阶"}]}, {"type": "paragraph", "text": "被穿过的地方，\n就是这个系列的图案"}], "footnote": "图片均为 AI 生成示意", "drawnBy": ["collage"]} as LineupBoardPage,
  "p08-unpick": {"heading": "一条旧裤子变成面料，要走五步", "kicker": "面料", "components": [{"type": "steps", "items": [{"title": "清洗晾干", "text": "先洗净晾干，再看哪里破、哪里能用"}, {"title": "拆线", "text": "沿缝线拆，不剪断，保住整块面积"}, {"title": "展平熨烫", "text": "前片、后片、腰头、口袋布分开压平"}, {"title": "分档", "text": "按深浅分成三档，同一档放一起"}, {"title": "排料拼接", "text": "先拼成整幅面料，再按样板裁"}]}, {"type": "image_grid", "items": [{"asset_id": "unpick", "caption": "02 沿缝线拆开"}, {"asset_id": "panels", "caption": "03 分部位压平"}, {"asset_id": "sort", "caption": "04 按深浅分档"}]}], "footnote": "过程图均为 AI 生成示意", "drawnBy": ["thread"]} as LineupBoardPage,
  "p09-fiber": {"heading": "打碎重纺会让纤维短三分之一，所以这次只拆不打碎", "kicker": "面料", "components": [{"type": "kpi_cards", "items": [{"value": "28.3", "unit": "毫米", "label": "原生棉纤维的上四分位长度", "source": "Arafat & Uddin，Heliyon，2022"}, {"value": "18.9", "delta": "down", "unit": "毫米", "label": "消费后回收棉纤维的上四分位长度", "source": "同一试验"}]}, {"type": "paragraph", "text": "同一试验里，30 支环锭纱最多只能掺 **25%** 回收棉。所以这个系列在面料层面再造，纤维不打碎"}], "footnote": "来源：Arafat & Uddin，Heliyon（2022），纺纱厂工业规模试验。「短约三分之一」为计算：(28.3 − 18.9) ÷ 28.3。线段按长度等比例画", "drawnBy": ["lengths"]} as LineupBoardPage,
  "p10-grade": {"heading": "按深浅把裁片分成三档", "kicker": "面料", "components": [{"type": "image", "asset_id": "gradient", "fit": "cover", "caption": "同一批旧裤拆出的裁片，从深到浅排开（AI 生成示意）"}, {"type": "row_cards", "items": [{"title": "深档", "text": "腰头背面、口袋下面，少见光的地方"}, {"title": "中档", "text": "大腿和小腿正面的大块裁片"}, {"title": "浅档", "text": "膝盖、臀部、褶痕，反复磨白的地方"}]}], "drawnBy": ["shades"]} as LineupBoardPage,
  "p11-joins": {"heading": "三种拼法，各管一类部位", "kicker": "面料", "components": [{"type": "row_cards", "items": [{"icon": "ruler", "title": "平接压明线", "text": "用在肩、腰、裆等受力处。结实，但明线多、费工"}, {"icon": "layers", "title": "叠拼留毛边", "text": "用在衣身大面和下摆，深浅两层都看得见"}, {"icon": "scissors", "title": "窄条拼", "text": "把太小的碎片也用上。拼缝最多，最费时"}]}, {"type": "image", "asset_id": "samples", "fit": "cover", "caption": "拼接小样（AI 生成示意）"}], "drawnBy": ["atelier"]} as LineupBoardPage,
  "p13-look01": {"heading": "渐变拼片长风衣", "components": [{"type": "image", "asset_id": "hero", "fit": "cover", "caption": "LOOK 01（AI 生成示意）", "crop": [0, 0.043, 1, 0.857]}, {"type": "insight_panel", "title": "LOOK **01**", "rows": [{"label": "面料", "text": "几条旧裤的大块裁片，按色阶斜向排开"}, {"label": "工艺", "text": "受力处平接压明线，衣身叠拼留毛边"}, {"label": "色阶", "text": "肩上深档，往下一档档变浅到下摆"}]}], "drawnBy": ["look"]} as LineupBoardPage,
  "p14-look0203": {"heading": "腰头和裤腿，换个位置再用", "components": [{"type": "insight_panel", "title": "LOOK 02 03", "rows": [{"label": "LOOK 02", "text": "腰头横拼短夹克，侧缝外翻的阔腿裤"}, {"label": "LOOK 03", "text": "裤腿裁成长条，深浅交替拼成长裙"}, {"label": "共同点", "text": "保留原来的腰头、侧缝和黄色明线"}]}, {"type": "image", "asset_id": "look0203", "fit": "cover", "caption": "LOOK 02（左）与 LOOK 03（右）（AI 生成示意）"}], "drawnBy": ["look"]} as LineupBoardPage,
  "p15-look04": {"heading": "色阶长裙", "components": [{"type": "image", "asset_id": "look04", "fit": "cover", "caption": "LOOK 04 背面（AI 生成示意）", "crop": [0, 0.057, 1, 0.857]}, {"type": "insight_panel", "title": "LOOK 04", "rows": [{"label": "面料", "text": "横向布条按色阶排，上深下浅"}, {"label": "工艺", "text": "布条之间叠拼，边缘不锁"}, {"label": "廓形", "text": "无袖长裙，裙摆落到地面"}]}], "drawnBy": ["look"]} as LineupBoardPage,
  "p16-look0507": {"heading": "毛边、口袋印和工装", "components": [{"type": "insight_panel", "title": "LOOK 05–07", "rows": [{"label": "LOOK 05", "text": "拼接衬衫，过肩和袖口的毛边露在外面"}, {"label": "LOOK 06", "text": "连衣裙，拆掉口袋后的深色印子排成图案"}, {"label": "LOOK 07", "text": "工装连体裤，中深档拼身，浅档做口袋"}]}, {"type": "image", "asset_id": "look0507", "fit": "cover", "caption": "从左到右：LOOK 05、06、07（AI 生成示意）"}], "drawnBy": ["look"]} as LineupBoardPage,
  "p17-limits": {"heading": "这个系列示范了一种做法，**没有解决环境问题**", "kicker": "边界", "components": [{"type": "pros_cons", "pros": {"title": "做到了", "items": [{"label": "旧牛仔的颜色、磨痕和缝线留了下来", "note": "面料层级再造，纤维没有被打碎"}, {"label": "来源不一的旧裤靠分档拼成一个系列", "note": "靠深、中、浅三档色差分级"}, {"label": "整理出一套拆、分、拼的做法", "note": "三种拼法各管一类部位"}]}, "cons": {"title": "做不到", "items": [{"label": "劳动密集、来料不稳，难以规模化", "note": "艾伦·麦克阿瑟基金会对这类做法的判断"}, {"label": "环境账没有核算，不能说省了水", "note": "清洗、辅料、边角料都有代价"}, {"label": "全国一年回收约 555 万吨，系列按条用", "note": "2025 年数据，中国物资再生协会"}]}, "verdict": "能说的是方法，不能说的是环境收益"}], "footnote": "来源：艾伦·麦克阿瑟基金会《A New Textiles Economy》（2017），中国物资再生协会（2025 年回收量）", "drawnBy": ["bounds"]} as LineupBoardPage,
}

export const LINEUP_BOARD_EN: Record<string, LineupBoardPage> = {
  "p02-agenda": {"heading": "Five parts: from old jeans to a collection", "kicker": "Running order", "components": [{"type": "numbered_cards", "items": [{"icon": "factory", "title": "Why old denim", "text": "How much textile waste, and the water in one pair"}, {"icon": "palette", "title": "Inspiration", "text": "Fading, creases and pocket marks as pattern"}, {"icon": "scissors", "title": "Fabric", "text": "Unpick, grade by shade, piece together"}, {"icon": "shirt", "title": "Collection", "text": "Seven looks, walking from dark to light", "emphasis": true}, {"icon": "scale", "title": "Limits", "text": "What it does, and what it cannot do"}]}], "drawnBy": ["order"]} as LineupBoardPage,
  "p03-why": {"heading": "Plenty of old clothes,\nfew ways to **reuse them**", "kicker": "Why old denim", "components": [{"type": "kpi_cards", "items": [{"value": "About 22", "unit": "million t", "label": "Textile waste in China in 2020, when about 20% was recycled"}, {"value": "25%  30%", "label": "China's recycling-rate targets for 2025 and 2030"}, {"value": "Easy to unpick", "label": "The same policy asks for textiles easier to take apart, sort and recycle"}]}], "footnote": "Source: National Development and Reform Commission et al., NDRC Huanzi [2022] No. 526, and expert commentary on the NDRC website, April 2022", "drawnBy": ["standfirst"]} as LineupBoardPage,
  "p04-cost": {"heading": "A new pair of jeans has already paid in water", "kicker": "Why old denim", "components": [{"type": "kpi_cards", "items": [{"value": "**3,781**", "unit": "L", "label": "One pair of Levi's 501, from cotton field to disposal", "source": "Levi's life cycle assessment, 2015, company figure"}, {"value": "10,850", "unit": "L", "label": "Virtual water in 1,000 g of jeans, global average", "source": "Chapagain et al., UNESCO-IHE, 2005"}]}, {"type": "paragraph", "text": "The two are counted differently, one over a pair's whole life, one as virtual water per kilogram. Read them side by side, never added or ranked"}], "footnote": "Source: Levi Strauss & Co., The Life Cycle of a Jean (2015), Chapagain et al., The water footprint of cotton consumption (2005)", "drawnBy": ["duet"]} as LineupBoardPage,
  "p06-mood": {"heading": "Moodboard: wear as pattern", "kicker": "Inspiration", "components": [{"type": "image_grid", "items": [{"asset_id": "mood-ghost", "caption": "Pocket mark"}, {"asset_id": "mood-knee", "caption": "Faded knee"}, {"asset_id": "mood-seam", "caption": "Stitched hem"}, {"asset_id": "mood-fray", "caption": "Raw edge"}, {"asset_id": "mood-mend", "caption": "Mend"}, {"asset_id": "mood-indigo", "caption": "Indigo shades"}]}, {"type": "paragraph", "text": "Where the jeans were worn\nis the pattern of the collection"}], "footnote": "All images are AI-generated", "drawnBy": ["collage"]} as LineupBoardPage,
  "p08-unpick": {"heading": "Five steps turn an old pair of jeans into fabric", "kicker": "Fabric", "components": [{"type": "steps", "items": [{"title": "Wash and dry", "text": "Then see what is torn and what can be used"}, {"title": "Unpick", "text": "Open the seams, never cut, to keep whole pieces"}, {"title": "Press flat", "text": "Fronts, backs, waistbands and pockets apart"}, {"title": "Grade", "text": "Sort into three shades, each kept together"}, {"title": "Lay out and piece", "text": "Piece whole lengths, then cut the pattern"}]}, {"type": "image_grid", "items": [{"asset_id": "unpick", "caption": "02 Unpicking a seam"}, {"asset_id": "panels", "caption": "03 Pressed by part"}, {"asset_id": "sort", "caption": "04 Sorted by shade"}]}], "footnote": "Process images are AI-generated", "drawnBy": ["thread"]} as LineupBoardPage,
  "p09-fiber": {"heading": "Shredding shortens fibre by a third, so I unpick", "kicker": "Fabric", "components": [{"type": "kpi_cards", "items": [{"value": "28.3", "unit": "mm", "label": "Virgin cotton fibre, upper quartile length", "source": "Arafat & Uddin, Heliyon, 2022"}, {"value": "18.9", "delta": "down", "unit": "mm", "label": "Post-consumer recycled cotton, same measure", "source": "Same trial"}]}, {"type": "paragraph", "text": "In the same trial, a 30s ring-spun yarn took at most **25%** recycled cotton. So this collection is remade as fabric, with the fibre left whole"}], "footnote": "Source: Arafat & Uddin, Heliyon (2022), industrial-scale spinning-mill trial. A third shorter is calculated: (28.3 − 18.9) ÷ 28.3. The lines are drawn to scale", "drawnBy": ["lengths"]} as LineupBoardPage,
  "p10-grade": {"heading": "Every piece is graded into three shades", "kicker": "Fabric", "components": [{"type": "image", "asset_id": "gradient", "fit": "cover", "caption": "Pieces from one batch of jeans, laid out dark to light (AI-generated)"}, {"type": "row_cards", "items": [{"title": "Dark", "text": "Waistband backs and under pockets, out of the light"}, {"title": "Mid", "text": "Large pieces from the fronts of thighs and shins"}, {"title": "Light", "text": "Knees, seat and creases, worn pale"}]}], "drawnBy": ["shades"]} as LineupBoardPage,
  "p11-joins": {"heading": "Three joins, each for its own part of a garment", "kicker": "Fabric", "components": [{"type": "row_cards", "items": [{"icon": "ruler", "title": "Flat seam", "text": "For shoulders, waist and crotch, where it pulls. Strong, but slow to stitch"}, {"icon": "layers", "title": "Raw overlap", "text": "For body panels and hems. Both shades stay in view"}, {"icon": "scissors", "title": "Narrow strips", "text": "Uses even the smallest scraps. The most seams, the most hours"}]}, {"type": "image", "asset_id": "samples", "fit": "cover", "caption": "Joining samples (AI-generated)"}], "drawnBy": ["atelier"]} as LineupBoardPage,
  "p13-look01": {"heading": "Graded patchwork trench", "components": [{"type": "image", "asset_id": "hero", "fit": "cover", "caption": "LOOK 01 (AI-generated)", "crop": [0, 0.043, 1, 0.857]}, {"type": "insight_panel", "title": "LOOK **01**", "rows": [{"label": "FABRIC", "text": "Large pieces from several pairs, laid on the bias by shade"}, {"label": "MAKE", "text": "Flat seams where it pulls, raw overlaps on the body"}, {"label": "SHADE", "text": "Dark at the shoulder, a shade lighter each step to the hem"}]}], "drawnBy": ["look"]} as LineupBoardPage,
  "p14-look0203": {"heading": "Waistbands and legs, used again elsewhere", "components": [{"type": "insight_panel", "title": "LOOK 02 03", "rows": [{"label": "LOOK 02", "text": "Cropped jacket of stacked waistbands, wide trousers with seams out"}, {"label": "LOOK 03", "text": "Legs cut into long panels, dark and light in turn, as a long skirt"}, {"label": "SHARED", "text": "The old waistbands, side seams and yellow stitching kept"}]}, {"type": "image", "asset_id": "look0203", "fit": "cover", "caption": "LOOK 02 (left) and LOOK 03 (right), AI-generated"}], "drawnBy": ["look"]} as LineupBoardPage,
  "p15-look04": {"heading": "Gradient maxi dress", "components": [{"type": "image", "asset_id": "look04", "fit": "cover", "caption": "LOOK 04, back (AI-generated)", "crop": [0, 0.057, 1, 0.857]}, {"type": "insight_panel", "title": "LOOK 04", "rows": [{"label": "FABRIC", "text": "Horizontal strips by shade, dark at the top, pale at the hem"}, {"label": "MAKE", "text": "Strips overlapped, their edges left unfinished"}, {"label": "SHAPE", "text": "Sleeveless, falling to the floor"}]}], "drawnBy": ["look"]} as LineupBoardPage,
  "p16-look0507": {"heading": "Raw edges, pocket marks, workwear", "components": [{"type": "insight_panel", "title": "LOOK 05–07", "rows": [{"label": "LOOK 05", "text": "Pieced shirt, raw edges left out at the yoke and cuffs"}, {"label": "LOOK 06", "text": "Dress patterned with the dark marks of removed pockets"}, {"label": "LOOK 07", "text": "Workwear jumpsuit, a mid to dark body and pale pockets"}]}, {"type": "image", "asset_id": "look0507", "fit": "cover", "caption": "Left to right: LOOK 05, 06, 07 (AI-generated)"}], "drawnBy": ["look"]} as LineupBoardPage,
  "p17-limits": {"heading": "A method, **not an environmental fix**", "kicker": "Limits", "components": [{"type": "pros_cons", "pros": {"title": "What it does", "items": [{"label": "Keeps the colour, wear and seams of old denim", "note": "Remade as fabric, the fibre left whole"}, {"label": "Turns mismatched jeans into one collection", "note": "Graded into dark, mid and light"}, {"label": "Sets out a way to unpick, grade and piece", "note": "Three joins, each for its own part"}]}, "cons": {"title": "What it cannot do", "items": [{"label": "Labour-heavy, uneven supply, hard to scale", "note": "The Ellen MacArthur Foundation's view of such methods"}, {"label": "No environmental accounting, no claim of water saved", "note": "Washing, trims and offcuts all have costs"}, {"label": "About 5.55 million t recycled a year, this counts pairs", "note": "2025 figure, China National Resources Recycling Association"}]}, "verdict": "It can claim a method, not an environmental gain"}], "footnote": "Source: Ellen MacArthur Foundation, A New Textiles Economy (2017), China National Resources Recycling Association (2025 recovery)", "drawnBy": ["bounds"]} as LineupBoardPage,
}

export const LINEUP_PARADE: Component = {"type": "image_grid", "emphasis": "first", "items": [{"asset_id": "hero", "caption": "LOOK 01"}, {"asset_id": "look0203", "caption": "LOOK 02", "crop": [0.06, 0.05, 0.385, 0.9]}, {"asset_id": "look0203", "caption": "LOOK 03", "crop": [0.555, 0.05, 0.385, 0.9]}, {"asset_id": "look04", "caption": "LOOK 04"}, {"asset_id": "look0507", "caption": "LOOK 05", "crop": [0.004, 0.117, 0.328, 0.766]}, {"asset_id": "look0507", "caption": "LOOK 06", "crop": [0.336, 0.117, 0.328, 0.766]}, {"asset_id": "look0507", "caption": "LOOK 07", "crop": [0.668, 0.117, 0.328, 0.766]}]} as Component
export const LINEUP_PARADE_EN: Component = {"type": "image_grid", "emphasis": "first", "items": [{"asset_id": "hero", "caption": "LOOK 01"}, {"asset_id": "look0203", "caption": "LOOK 02", "crop": [0.06, 0.05, 0.385, 0.9]}, {"asset_id": "look0203", "caption": "LOOK 03", "crop": [0.555, 0.05, 0.385, 0.9]}, {"asset_id": "look04", "caption": "LOOK 04"}, {"asset_id": "look0507", "caption": "LOOK 05", "crop": [0.004, 0.117, 0.328, 0.766]}, {"asset_id": "look0507", "caption": "LOOK 06", "crop": [0.336, 0.117, 0.328, 0.766]}, {"asset_id": "look0507", "caption": "LOOK 07", "crop": [0.668, 0.117, 0.328, 0.766]}]} as Component
