import type { Component, Slide } from "@/ir"

/*
 * rally's 2026-10 board, its content pages p03 to p17 as the showcase deck
 * writes them (`showcase/rally/zh`), less the heading, the ticket, the source
 * line and the folio, which are the face's and the motif's. Each page names
 * the composition that draws it in the marquee setting, and whether it has
 * a source line under it (its band then ends at y640, otherwise y648).
 */

export interface MarqueeBoardPage {
  components: Component[]
  drawnBy: string[]
  ballot?: Slide["ballot"]
  sourced: boolean
}

export const MARQUEE_BOARD: Record<string, MarqueeBoardPage> = {
  "p03-market": {"components": [{"type": "kpi_cards", "items": [{"value": "4338.58", "unit": "万人次", "label": "2025 年 · 同比 +18.81%", "note": "5000 人以上大型营业性演出观众。2026 年上半年再涨 20.37%。"}]}, {"type": "chart", "chart_type": "bar", "axes": {"y_unit": "亿元"}, "series": [{"name": "大型演出票房", "data": [{"x": "2019", "y": 39.64}, {"x": "2023", "y": 177.96}, {"x": "2024", "y": 296.36}, {"x": "2025", "y": 324.48, "emphasis": true}]}]}, {"type": "callout", "variant": "info", "title": "票房占全国演出一半以上", "text": "2023 年 35.4%，2024 年 51.1%，2025 年约 52.6%（324.48 ÷ 616.55）"}], "drawnBy": ["crest"], "sourced": true} as MarqueeBoardPage,
  "p04-split": {"components": [{"type": "chart", "chart_type": "line", "axes": {"y_unit": "%"}, "series": [{"name": "演唱会", "emphasis": true, "data": [{"x": "2024", "y": 0}, {"x": "2025", "y": 30.8}]}, {"name": "音乐节", "data": [{"x": "2024", "y": 0}, {"x": "2025", "y": -6.1}]}]}, {"type": "callout", "variant": "info", "icon": "mic-vocal", "title": "演唱会 · 2027 押这边", "text": "近 3800 万人次 · 2496 场 · 票房 295.58 亿元（+13.7%）"}, {"type": "callout", "variant": "info", "icon": "tent", "title": "音乐节", "text": "545.6 万人次 · 547 场 · 2026 年 3 至 5 月约 40 场，上年同期 90 多场", "tag": {"text": "媒体报道", "evidence": "press"}}], "drawnBy": ["branch"], "sourced": true} as MarqueeBoardPage,
  "p05-season": {"components": [{"type": "heatmap", "x_labels": ["1 月", "2 月", "3 月", "4 月", "5 月", "6 月", "7 月", "8 月", "9 月", "10 月", "11 月", "12 月"], "y_labels": ["演唱会", "音乐节"], "values": [[0, 0, 0, 0, 2, 0, 0, 3, 3, 0, 2, 0], [0, 0, 0, 0, 3, 0, 1, 1, 1, 3, 0, 0]], "bands": [{"from": "6 月", "to": "9 月", "label": "2027 演唱会季 · 6 至 9 月"}]}, {"type": "callout", "variant": "info", "text": "演唱会：8、9 月场次见顶，5、11 月票房高点"}, {"type": "callout", "variant": "info", "text": "音乐节：五一超过 60 场、十一超过 40 场，7 至 9 月次高"}, {"type": "callout", "variant": "info", "text": "色块深浅只表示高峰位置，2024 年月度柱图没有标数值"}], "drawnBy": ["season"], "sourced": true} as MarqueeBoardPage,
  "p06-audience": {"components": [{"type": "chart", "chart_type": "stacked", "direction": "horizontal", "emphasis_label": "18 至 34 岁 74.9%", "series": [{"name": "青少年", "data": [{"x": "演唱会", "y": 3.6}]}, {"name": "18-24", "data": [{"x": "演唱会", "y": 25.8}], "emphasis": true}, {"name": "25-29", "data": [{"x": "演唱会", "y": 31.1}], "emphasis": true}, {"name": "30-34", "data": [{"x": "演唱会", "y": 18.0}], "emphasis": true}, {"name": "35-39", "data": [{"x": "演唱会", "y": 10.3}]}, {"name": "40-44", "data": [{"x": "演唱会", "y": 5.4}]}, {"name": "45+", "data": [{"x": "演唱会", "y": 5.9}]}]}, {"type": "chart", "chart_type": "stacked", "direction": "horizontal", "emphasis_label": "18 至 34 岁 84.9%", "series": [{"name": "青少年", "data": [{"x": "音乐节", "y": 5.0}]}, {"name": "18-24", "data": [{"x": "音乐节", "y": 36.2}], "emphasis": true}, {"name": "25-29", "data": [{"x": "音乐节", "y": 33.3}], "emphasis": true}, {"name": "30-34", "data": [{"x": "音乐节", "y": 15.4}], "emphasis": true}, {"name": "35-39", "data": [{"x": "音乐节", "y": 6.0}]}, {"name": "40-44", "data": [{"x": "音乐节", "y": 2.2}]}, {"name": "45+", "data": [{"x": "音乐节", "y": 1.9}]}]}, {"type": "kpi_cards", "items": [{"value": "**66.1%**", "label": "演唱会观众中的女性", "note": "音乐节 67.1%（2024 年）。00 后占现场音乐观众 32.5%（2025 年）", "icon": "venus"}]}, {"type": "callout", "variant": "warn", "icon": "user-round-search", "text": "大盘不等于单场：刀郎巡演 50 岁以上观众占 44.5%。选场次要看艺人的单场画像。"}], "drawnBy": ["makeup"], "sourced": true} as MarqueeBoardPage,
  "p07-crosscity": {"components": [{"type": "chart", "chart_type": "percent_stacked", "axes": {"x_title": "按演出举办城市分线，2024 年", "y_unit": "%"}, "series": [{"name": "本城", "data": [{"x": "一线", "y": 46.5}, {"x": "二线", "y": 35.1}, {"x": "三线", "y": 28.3}, {"x": "四线", "y": 18.6}]}, {"name": "省内跨城", "data": [{"x": "一线", "y": 10.2}, {"x": "二线", "y": 20.7}, {"x": "三线", "y": 37.0}, {"x": "四线", "y": 48.5}]}, {"name": "跨省", "data": [{"x": "一线", "y": 43.3}, {"x": "二线", "y": 44.2}, {"x": "三线", "y": 34.7}, {"x": "四线", "y": 33.0}]}]}, {"type": "image", "asset_id": "train", "fit": "cover", "caption": "示意图（AI 生成）"}, {"type": "kpi_cards", "items": [{"value": "**64.2%**", "label": "2024 年大型演唱会观众跨城观演（音乐节 62.2%）"}]}], "drawnBy": ["origins"], "sourced": true} as MarqueeBoardPage,
  "p08-weekend": {"components": [{"type": "steps", "items": [{"icon": "train-front", "title": "出发", "text": "高铁赶场"}, {"icon": "cup-soda", "title": "开场前", "text": "场外排队等候"}, {"icon": "music", "title": "演出中", "text": "场内归主办方。我们不进场卖货", "tone": "warning"}, {"icon": "moon-star", "title": "散场后", "text": "找地方吃饭"}, {"icon": "map-pin", "title": "第二天", "text": "逛街、景区"}]}, {"type": "kpi_cards", "items": [{"value": "**78.5%**", "label": "停留 2 天及以上", "note": "2 天 41.5%，3 天 24.2%，4 至 5 天 11.7%"}]}, {"type": "chart", "chart_type": "bar", "direction": "horizontal", "axes": {"y_unit": "%"}, "series": [{"name": "在演出地有这项支出的人占多少（不是金额结构）", "data": [{"x": "餐饮", "y": 98.4, "emphasis": true}, {"x": "演出购票", "y": 96.4}, {"x": "市内交通", "y": 68.1}, {"x": "购物（含周边）", "y": 64.7}, {"x": "景区门票", "y": 30.2}]}]}], "drawnBy": ["route"], "sourced": true} as MarqueeBoardPage,
  "p09-touchpoints": {"components": [{"type": "image_grid", "emphasis": "first", "items": [{"asset_id": "kioskwide", "caption": "场外：饮品站，现制杯装，杯上带码。示意图（AI 生成）", "icon": "cup-soda"}, {"asset_id": "wristband", "caption": "场内：只做主办方允许的合作。示意图（AI 生成）", "icon": "sparkles"}, {"asset_id": "exit", "caption": "场后：接驳点补给，发门店券。示意图（AI 生成）", "icon": "moon-star"}, {"asset_id": "riverside", "caption": "城市：票根换饮，城市商户联动。示意图（AI 生成）", "icon": "map-pin"}]}, {"type": "callout", "variant": "warn", "text": "北京警方曾提示大型活动禁带瓶装饮料（北京特定时段，非全国规定）：我们不发瓶装让观众带进场"}], "drawnBy": ["spots"], "sourced": false} as MarqueeBoardPage,
  "p10-cases": {"components": [{"type": "icon_cards", "items": [{"icon": "cup-soda", "title": "沪上阿姨 · 茶饮 · 2024", "text": "巡演联名双杯套餐，12 城 700 多家门店。10 分钟销量破 1 万份", "tag": {"text": "企业口径", "evidence": "company"}}, {"icon": "zap", "title": "战马 · 能量饮料 · 2025", "text": "新疆超级草莓音乐节全场饮品站冠名。现场近 8 万乐迷（全场人数）", "tag": {"text": "品牌软文", "evidence": "company"}}, {"icon": "milk", "title": "畅轻 · 乳品 · 2025", "text": "草莓音乐节联名包装，买酸奶抽门票。未披露", "tag": {"text": "营销媒体", "evidence": "press"}}, {"icon": "ice-cream-cone", "title": "伊利须尽欢 · 乳品 · 2024", "text": "冠名 3 场演唱会，现场设销售点。微博曝光超过 11 亿", "tag": {"text": "企业口径", "evidence": "company"}}, {"icon": "wine", "title": "洋河梦之蓝 M6+ · 白酒 · 2024", "text": "巡演 8 城冠名，扫码开瓶得票。视频播放突破 50 亿", "tag": {"text": "企业口径", "evidence": "company"}}, {"icon": "megaphone", "title": "百事可乐 · 饮料 · 2023", "text": "TFBOYS 十年之约西安站主冠名。未披露品牌效果", "tag": {"text": "媒体报道", "evidence": "press"}}]}, {"type": "kpi_cards", "items": [{"value": "0", "unit": "例", "label": "公开可归因的销量", "note": "效果数字都是曝光、热搜、售罄，查不到一个能算回销量的数"}]}], "drawnBy": ["wall"], "sourced": true} as MarqueeBoardPage,
  "p11-attribution": {"components": [{"type": "chevron_process", "items": [{"title": "发码", "text": "杯码、包装码、票根券，带城市和场次", "icon": "qr-code"}, {"title": "扫码领券", "text": "进小程序领门店券", "icon": "smartphone"}, {"title": "门店核销", "text": "核销记录算回到触点", "icon": "store"}, {"title": "复购回访", "text": "看 30 天内是否再买", "icon": "repeat"}, {"title": "对照复盘", "text": "和没有演出的同类城市比", "icon": "scale"}]}, {"type": "callout", "variant": "info", "text": "复盘结果回到下一站的发码"}, {"type": "data_table", "columns": [{"key": "t", "label": "触点"}, {"key": "c", "label": "码", "emphasis": true}, {"key": "y", "label": "能算清"}, {"key": "n", "label": "首站要验证"}], "rows": [{"icon": "cup-soda", "cells": {"t": "场外饮品站", "c": "杯码", "y": "领取人数，按城市和场次", "n": "现场试饮能否变成门店购买"}}, {"icon": "package", "cells": {"t": "联名包装", "c": "包装码", "y": "扫码率和联名款动销", "n": "买的是不是新客"}}, {"icon": "ticket", "cells": {"t": "票根换饮", "c": "门店券", "y": "跨城观众到店人数", "n": "回家后是否还买"}}]}], "drawnBy": ["loop"], "sourced": false} as MarqueeBoardPage,
  "p12-city": {"components": [{"type": "icon_cards", "items": [{"icon": "landmark", "title": "国家：跟着演出去旅行", "text": "2025 年 1 月国办文件写进全国措施", "tag": {"text": "凭票根"}}, {"icon": "map-pin", "title": "南京：乐享 1+3", "text": "453 家商户，观演前后一周凭票享优惠", "tag": {"text": "凭票根"}}, {"icon": "ticket", "title": "上海浦东：票根兑优惠", "text": "财政补贴 30%，商家让利 20%，实名核验", "tag": {"text": "凭票根"}}, {"icon": "bus-front", "title": "青岛：票根经济 3.0", "text": "超过 800 家商户，开散场接驳专线", "tag": {"text": "凭票根"}}]}, {"type": "kpi_cards", "items": [{"value": "1:6.85", "label": "协会测算：1 元票房带动的其他消费", "note": "方法未公开。只说明城市为什么欢迎演出，不算品牌回报。", "icon": "building-2", "tone": "warning"}]}], "drawnBy": ["stubs"], "sourced": true} as MarqueeBoardPage,
  "p13-planb": {"components": [{"type": "data_table", "columns": [{"key": "e", "label": "风险 · 公开事件"}, {"key": "p", "label": "预案（Plan B）"}], "rows": [{"icon": "cloud-lightning", "cells": {"e": "天气：2026-07 台风「巴威」，邓紫棋杭州站 3 场取消", "p": "站点物料可转场，门店券随改期顺延"}}, {"icon": "siren", "cells": {"e": "执行事故：2025-05 元气森林北京音乐节演出被压缩，现场喊退票", "p": "不自办音乐节，舞台归主办方，我们只管场外站点"}}, {"icon": "user-x", "cells": {"e": "艺人：2021-08 张哲瀚事件，4 小时 21 分内 26 个品牌解约", "p": "只签场次合作不签代言，含道德条款，4 小时内下线物料"}}, {"icon": "ticket-x", "cells": {"e": "黄牛：镇江团伙两年抢票 6 万多张，获利 1600 多万元", "p": "激励门票只走实名，中奖人即观演人"}}, {"icon": "rotate-ccw", "cells": {"e": "退票：2025 年上半年演唱会投诉翻番，退票诉求超过九成", "p": "激励票的退改规则在活动页写清，按平台规则执行"}}, {"icon": "ban", "emphasis": "highlight", "cells": {"e": "禁带瓶装：北京警方 2026 年端午大型活动提示禁带瓶装饮料", "p": "场外现制杯装当场喝完，不发瓶装让观众带进场"}}]}], "drawnBy": ["fallbacks"], "sourced": true} as MarqueeBoardPage,
  "p14-schedule": {"components": [{"type": "gantt", "axis_labels": ["2026.10", "11", "12", "2027.1", "2", "3", "4", "5", "6", "7", "8", "9", "10"], "bands": [{"from": 8, "to": 12, "label": "演唱会季 6 至 9 月"}], "items": [{"label": "拍板立项", "start": 0, "end": 1}, {"label": "选城市，谈场次", "text": "主办方和场馆", "start": 1, "end": 4}, {"label": "包装、看板、票根", "text": "5 月前就绪", "start": 2, "end": 8}, {"label": "首站试点", "text": "复盘过关才拨第二批", "start": 8, "end": 9, "emphasis": true, "icon": "star"}, {"label": "演唱会季执行", "text": "覆盖 8、9 月高峰", "start": 9, "end": 12}, {"label": "收官复盘", "start": 11, "end": 12}]}], "drawnBy": ["timetable"], "sourced": false} as MarqueeBoardPage,
  "p15-kpi": {"components": [{"type": "icon_cards", "items": [{"icon": "qr-code", "title": "杯码核销", "text": "饮品站领取并扫码的杯数，按城市和场次拆", "tag": {"text": "目标：首站复盘后定", "tone": "warning"}}, {"icon": "store", "title": "门店券核销率", "text": "散场后 7 天内核销张数 ÷ 发放张数", "tag": {"text": "目标：首站复盘后定", "tone": "warning"}}, {"icon": "package", "title": "联名款增量", "text": "演出城市与对照城市联名款周销量之差", "tag": {"text": "目标：首站复盘后定", "tone": "warning"}}, {"icon": "repeat", "title": "30 天复购", "text": "扫码会员 30 天内再次购买的比例", "tag": {"text": "目标：首站复盘后定", "tone": "warning"}}, {"icon": "ticket", "title": "票根换饮", "text": "凭票根换饮的核销次数，按城市和商户拆", "tag": {"text": "目标：首站复盘后定", "tone": "warning"}}, {"icon": "message-circle-warning", "title": "舆情", "text": "负面提及占比，触发即启动 4 小时处置", "tag": {"text": "目标：首站复盘后定", "tone": "warning"}}]}, {"type": "callout", "variant": "info", "text": "看板每周报管理层。没有核销码的项目不立项。"}], "drawnBy": ["scoreboard"], "sourced": false} as MarqueeBoardPage,
  "p16-budget": {"components": [{"type": "chart", "chart_type": "stacked", "direction": "horizontal", "axes": {"y_unit": "%"}, "emphasis_label": "单列 15%，不挪用", "series": [{"name": "场外饮品站与物料", "data": [{"x": "拟定比例", "y": 30}]}, {"name": "联名包装与门店活动", "data": [{"x": "拟定比例", "y": 25}]}, {"name": "票根合作与门票激励", "data": [{"x": "拟定比例", "y": 15}]}, {"name": "内容与线上投放", "data": [{"x": "拟定比例", "y": 15}]}, {"name": "归因系统与数据", "data": [{"x": "拟定比例", "y": 8}], "emphasis": true}, {"name": "风险准备金", "data": [{"x": "拟定比例", "y": 7}], "emphasis": true}]}, {"type": "icon_cards", "items": [{"icon": "hand-coins", "title": "分两批拨付", "text": "首站复盘过关再拨第二批"}, {"icon": "file-check", "title": "金额另行报批", "text": "比例为市场部拟定，不是测算"}]}], "drawnBy": ["allotment"], "sourced": false} as MarqueeBoardPage,
  "p17-asks": {"components": [{"type": "numbered_cards", "items": [{"icon": "target", "title": "方向：押大型演唱会的场外和城市", "text": "不冠名、不自办音乐节，2027 年 6 至 9 月执行", "sub": "见 3 至 9 页", "emphasis": true}, {"icon": "wallet", "title": "预算：按六类比例编制，分两批拨付", "text": "首站复盘过关再拨第二批，金额另行报批", "sub": "见 16 页"}, {"icon": "qr-code", "title": "归因：没有核销码的项目不立项", "text": "看板每周报管理层，首站后定目标值", "sub": "见 10、11、15 页"}, {"icon": "shield-alert", "title": "授权：艺人风险由市场部负责人处置", "text": "只签场次合作并含道德条款，出事 4 小时内下线物料", "sub": "见 13 页"}]}], "drawnBy": ["asks"], "sourced": false, "ballot": {"choices": ["批准", "再议"]}} as MarqueeBoardPage,
}
