import type { Component, PageKind } from "@/ir"
import type { CompositionId } from ".."

/*
 * The pages of bulletin's 2026-10 kinds board (`design/rounds/2026-10-09-bulletin-kinds/`),
 * written as a deck would write them: the Chinese deck's six pages and the
 * English deck's three, plus an English table page so each language draws
 * both forms of the evidence page. Figures from the bulletin showcase.
 */

export interface NoticeBoardPage {
  readonly kind: PageKind
  readonly heading: string
  readonly components: Component[]
  readonly footnote?: string
  /** The composition that draws the page. */
  readonly drawnBy: CompositionId
}

export const NOTICE_KINDS_BOARD: Record<string, NoticeBoardPage> = {
  "p01-target": {"kind": "statement", "heading": "四季度目标，按三季度的**实际走势**重定", "components": [{"type": "paragraph", "text": "6 月判断全年零售降 11%。按这个倒推，四季度要比三季度多卖约 65%，去年同期只多了 11%。"}], "drawnBy": "sentence", "footnote": "来源：乘联会月报及 9 月预测，崔东树全年判断（2026 年 6 月 9 日）。四季度为按全年零售降 11% 倒推（计算）"} as NoticeBoardPage,
  "p02-share": {"kind": "statement", "heading": "份额在挪：比亚迪少了约 4.5 个点，拿走份额的是**新势力**", "components": [{"type": "paragraph", "text": "8 月新势力占国内新能源零售 26.0%，同比多 5.5 个点。比亚迪从约 27.8% 降到 23.3%，吉利、长安、特斯拉中国也各让出 0.1 到 1.1 个点。"}], "drawnBy": "sentence", "footnote": "来源：乘联会 2026 年 8 月月报，CnEVPost 转引乘联会 2025 年 8 月厂商数据（2025 年 9 月 10 日）。国内新能源零售份额，近似值"} as NoticeBoardPage,
  "p03-export": {"kind": "fact", "heading": "增量在海外：新能源出口 7–8 月是去年同期的 2.5 倍", "components": [{"type": "kpi_cards", "items": [{"value": "2.5", "unit": "倍", "label": "7–8 月新能源乘用车出口，是去年同期的"}, {"value": "105.8 万辆", "label": "2026 年 7–8 月"}, {"value": "41.7 万辆", "label": "2025 年 7–8 月"}, {"value": "58.4%", "label": "8 月新能源占乘用车出口"}]}], "drawnBy": "billboard", "footnote": "来源：乘联会 7、8 月月报（2025、2026 年），崔东树出口分析（2026 年 9 月 24 日）"} as NoticeBoardPage,
  "p04-market": {"kind": "fact", "heading": "国内零售连续三个月同比降两成以上，9 月也没有旺季", "components": [{"type": "kpi_cards", "items": [{"value": "−23.6", "unit": "%", "label": "8 月乘用车国内零售，同比"}, {"value": "−20.9%", "label": "7 月零售同比"}, {"value": "−29%", "label": "9 月 1–27 日零售同比"}, {"value": "约 169 万辆", "label": "9 月全月预测，同比 −24.6%"}]}], "drawnBy": "billboard", "footnote": "来源：乘联会月报（2025 年 7–9 月，2026 年 7、8 月）、周度数据（2026 年 9 月 30 日）和 9 月预测（2026 年 9 月 17 日）"} as NoticeBoardPage,
  "p05-september": {"kind": "evidence", "heading": "9 月也没有旺季：降幅没有收窄，反而更深", "components": [{"type": "chart", "chart_type": "bar", "title": "乘用车国内零售", "axes": {"y_unit": "万辆"}, "series": [{"name": "2025 年", "data": [{"x": "7 月", "y": 182.6}, {"x": "8 月", "y": 199.5}, {"x": "9 月", "y": 224.1}]}, {"name": "2026 年", "data": [{"x": "7 月", "y": 146.1}, {"x": "8 月", "y": 154.1}, {"x": "9 月", "y": 169, "status": "forecast", "emphasis": true}]}]}, {"type": "paragraph", "text": "9 月 1–27 日零售同比 −29%，比 7、8 月降得更深"}, {"type": "paragraph", "text": "去年 9 月比 8 月多卖 12%，今年按预测只多 10%"}, {"type": "paragraph", "text": "9 月全月为乘联会 9 月 17 日的预测"}], "drawnBy": "proof", "footnote": "来源：乘联会月报（2025 年 7–9 月，2026 年 7、8 月）、周度数据（2026 年 9 月 30 日）和 9 月预测（2026 年 9 月 17 日）"} as NoticeBoardPage,
  "p06-players": {"kind": "evidence", "heading": "零跑三季度卖了 31 万辆，量和涨幅都排第二", "components": [{"type": "data_table", "title": "三季度销量，各公司公告口径", "columns": [{"key": "co", "label": "企业"}, {"key": "q3", "label": "三季度销量", "align": "right"}, {"key": "yoy", "label": "同比", "align": "right"}], "rows": [{"cells": {"co": "极氪", "q3": "110,034 辆", "yoy": "约 +108%"}}, {"cells": {"co": "零跑", "q3": "310,052 辆", "yoy": "+78.3%"}, "emphasis": "highlight"}, {"cells": {"co": "蔚来公司", "q3": "109,178 辆", "yoy": "+25.4%"}}, {"cells": {"co": "比亚迪", "q3": "1,323,065 辆", "yoy": "+18.8%"}}, {"cells": {"co": "理想", "q3": "99,964 辆", "yoy": "+7.2%"}}, {"cells": {"co": "小鹏", "q3": "118,390 辆", "yoy": "+2.1%"}}]}, {"type": "paragraph", "text": "零跑三季度 310,052 辆，同比 +78.3%"}, {"type": "paragraph", "text": "销量仅次于比亚迪，涨幅仅次于极氪"}, {"type": "paragraph", "text": "各家口径不同，含出口，只看各自的同比方向"}], "drawnBy": "proof", "footnote": "来源：各公司 2026 年 7–9 月交付公告（港交所、SEC 6-K、CnEVPost 汇总，2026 年 8 月 1 日至 10 月 1 日）。公司口径，含出口，不能横向比份额"} as NoticeBoardPage,
}

export const NOTICE_KINDS_BOARD_EN: Record<string, NoticeBoardPage> = {
  "p01-target": {"kind": "statement", "heading": "Reset Q4 targets to **Q3’s real trend**", "components": [{"type": "paragraph", "text": "June’s call for an 11% full-year fall needs Q4 retail about 65% above Q3. A year ago Q4 was only 11% above Q3."}], "drawnBy": "sentence", "footnote": "Source: CPCA reports and Sep forecast, Cui Dongshu's full-year call (Jun 9, 2026). Q4 worked back from an 11% decline"} as NoticeBoardPage,
  "p02-export": {"kind": "fact", "heading": "Growth went abroad: NEV exports up 154%", "components": [{"type": "kpi_cards", "items": [{"value": "+154", "unit": "%", "label": "NEV passenger car exports, July and August, year on year"}, {"value": "1.058m", "label": "July and August 2026"}, {"value": "0.417m", "label": "July and August 2025"}, {"value": "58.4%", "label": "NEV share of August exports"}]}], "drawnBy": "billboard", "footnote": "Source: CPCA reports (Jul–Aug 2025, 2026), Cui Dongshu export analysis (Sep 24, 2026)"} as NoticeBoardPage,
  "p03-september": {"kind": "evidence", "heading": "No September peak: the fall got deeper, not shallower", "components": [{"type": "chart", "chart_type": "bar", "title": "Passenger car retail in China", "axes": {"y_unit": "m"}, "series": [{"name": "2025", "data": [{"x": "July", "y": 1.83}, {"x": "August", "y": 2.0}, {"x": "September", "y": 2.24}]}, {"name": "2026", "data": [{"x": "July", "y": 1.46}, {"x": "August", "y": 1.54}, {"x": "September", "y": 1.69, "status": "forecast", "emphasis": true}]}]}, {"type": "paragraph", "text": "September 1–27 retail fell 29% year on year, deeper than July or August"}, {"type": "paragraph", "text": "September 2025 beat August by 12%. This year's forecast: 10%"}, {"type": "paragraph", "text": "Full-month September is the CPCA forecast of September 17"}], "drawnBy": "proof", "footnote": "Source: China Passenger Car Association (CPCA) reports (Jul–Sep 2025, Jul–Aug 2026), Sep 30 weekly data, Sep 17 forecast"} as NoticeBoardPage,
  "p04-players": {"kind": "evidence", "heading": "Leapmotor sold 310,000 in Q3, second in volume and growth", "components": [{"type": "data_table", "title": "Q3 sales, as each company reported them", "columns": [{"key": "co", "label": "Company"}, {"key": "q3", "label": "Q3 sales", "align": "right"}, {"key": "yoy", "label": "YoY", "align": "right"}], "rows": [{"cells": {"co": "Zeekr", "q3": "110,034", "yoy": "about +108%"}}, {"cells": {"co": "Leapmotor", "q3": "310,052", "yoy": "+78.3%"}, "emphasis": "highlight"}, {"cells": {"co": "NIO Inc.", "q3": "109,178", "yoy": "+25.4%"}}, {"cells": {"co": "BYD", "q3": "1,323,065", "yoy": "+18.8%"}}, {"cells": {"co": "Li Auto", "q3": "99,964", "yoy": "+7.2%"}}, {"cells": {"co": "XPeng", "q3": "118,390", "yoy": "+2.1%"}}]}, {"type": "paragraph", "text": "Leapmotor sold 310,052 in Q3, up 78.3%"}, {"type": "paragraph", "text": "Second only to BYD in volume, to Zeekr in growth"}, {"type": "paragraph", "text": "Company figures, exports included: read each one's own direction"}], "drawnBy": "proof", "footnote": "Source: company delivery releases via HKEX, SEC 6-K and CnEVPost (Aug 1 to Oct 1, 2026). Exports included"} as NoticeBoardPage,
}
