import type { Component } from "@/ir"

/*
 * journal's 2026-10 board, its content pages as the showcase deck writes them
 * (`showcase/journal/zh`), less the claim, the section, the column, the issue
 * and the folio, which are the face's and the motif's. Each page names the
 * composition that draws it in the periodical setting, carries the page's
 * claim (a composition places it), and the number each of its blocks takes in
 * the deck (「图 3」), which the face counts and hands down. The board's
 * photographs are named for the assets the tests hand in
 * (`PERIODICAL_BOARD_IMAGES`).
 */

export interface PeriodicalBoardPage {
  heading: string
  components: Component[]
  drawnBy: string[]
  exhibits: (string | null)[]
}

export const PERIODICAL_BOARD_IMAGES = ["listening", "subway", "magazines", "bookshop", "library"] as const

export const PERIODICAL_BOARD: Record<string, PeriodicalBoardPage> = {
  "p02-note": {"heading": "读书的人没变少，变的是读法", "components": [{"type": "paragraph", "text": "今年我们把十年的全国国民阅读调查从头读了一遍，想回答一个常被问起的问题：大家还在读书吗？答案比担心的好，也比想的复杂。读书的人和本数几乎没动，动的是读的方式和花的时间，而跌得最狠的那一条线，正好是我们自己。"}, {"type": "kpi_cards", "items": [{"value": "60.0%", "label": "成年人图书阅读率", "note": "2015 年 58.4%", "icon": "book-open"}, {"value": "80.8%", "label": "数字化阅读接触率", "note": "2015 年 64.0%", "icon": "smartphone"}, {"value": "**16.6%**", "label": "期刊阅读率", "note": "2015 年 34.6%", "icon": "newspaper"}]}], "drawnBy": ["foreword"], "exhibits": [null, null]} as PeriodicalBoardPage,
  "p03-books": {"heading": "十年里，读书的人从 58.4% 到 60.0%，人均纸书只多了 0.23 本", "components": [{"type": "chart", "title": "成年人人均阅读量（本），分母是全体成年人，调查年份 2015 至 2025", "chart_type": "line", "axes": {"y_unit": "本"}, "series": [{"name": "纸书", "data": [{"x": "2015", "y": 4.58}, {"x": "2016", "y": 4.65}, {"x": "2017", "y": 4.66}, {"x": "2018", "y": 4.67}, {"x": "2019", "y": 4.65}, {"x": "2020", "y": 4.7}, {"x": "2021", "y": 4.76}, {"x": "2022", "y": 4.78}, {"x": "2023", "y": 4.75}, {"x": "2024", "y": 4.79}, {"x": "2025", "y": 4.81}], "emphasis": true}, {"name": "电子书", "data": [{"x": "2015", "y": 3.26}, {"x": "2016", "y": 3.21}, {"x": "2017", "y": 3.12}, {"x": "2018", "y": 3.32}, {"x": "2019", "y": 2.84, "note": "2019 年电子书 2.84 本，一个凹点"}, {"x": "2020", "y": 3.29}, {"x": "2021", "y": 3.3}, {"x": "2022", "y": 3.33}, {"x": "2023", "y": 3.4}, {"x": "2024", "y": 3.52}, {"x": "2025", "y": 3.58}]}]}, {"type": "callout", "variant": "info", "text": "4.81 本是平均数，被少数读得多的人拉高了，发布稿没有给中位数。"}], "drawnBy": ["chronicle"], "exhibits": ["图 1", null]} as PeriodicalBoardPage,
  "p04-ways": {"heading": "变的是读法：79.0% 的人用手机读，38.7% 的人用耳朵听", "components": [{"type": "chart", "title": "2025 年成年人各种读法的接触率（%），一个人可以同时用几种", "chart_type": "bar", "direction": "horizontal", "axes": {"x_unit": "%"}, "series": [{"name": "2025 年接触率", "data": [{"x": "手机阅读", "y": 79, "icon": "smartphone"}, {"x": "电脑端在线", "y": 66.4, "icon": "book-marked"}, {"x": "听书", "y": 38.7, "emphasis": true, "icon": "headphones"}, {"x": "电子阅读器", "y": 21.3, "icon": "book-open"}, {"x": "视频讲书", "y": 6.3, "icon": "clapperboard"}]}]}, {"type": "callout", "variant": "info", "text": "数字化阅读接触率十年从 64.0% 升到 80.8%，但 2019 年以后几乎不再涨。"}, {"type": "image", "asset_id": "listening", "caption": "窗边听书的人（AI 生成示意）", "fit": "cover"}], "drawnBy": ["measures"], "exhibits": ["图 2", null, null]} as PeriodicalBoardPage,
  "p05-time": {"heading": "纸书的时间没少，手机的时间多得多", "components": [{"type": "image", "asset_id": "subway", "caption": "晚高峰的地铁车厢（AI 生成示意）", "fit": "cover"}, {"type": "chart", "chart_type": "bar", "direction": "horizontal", "axes": {"x_unit": "分钟"}, "series": [{"name": "2017 年", "data": [{"x": "每天接触手机", "y": 80.43, "note": "虚线是 2017 年：80.43 分钟", "icon": "smartphone"}, {"x": "每天读纸书", "y": 20.38, "note": "虚线是 2017 年：20.38 分钟", "icon": "book-open"}]}, {"name": "2025 年", "data": [{"x": "每天接触手机", "y": 109.54}, {"x": "每天读纸书", "y": 24.68, "emphasis": true}]}]}, {"type": "paragraph", "text": "短视频用户 10.74 亿，占网民 95.4%。它挤走了多少读书时间，没有数据，只能说两件事同时在发生。"}], "drawnBy": ["elapsed"], "exhibits": [null, null, null]} as PeriodicalBoardPage,
  "p06-periodicals": {"heading": "跌得最狠的是报刊：期刊阅读率十年少了一半还多", "components": [{"type": "kpi_cards", "items": [{"value": "16.6", "unit": "%", "label": "2025 年成年人期刊阅读率", "note": "2015 年是 34.6%"}]}, {"type": "chart", "title": "成年人报纸和期刊阅读率（%）", "chart_type": "line", "axes": {"y_unit": "%"}, "gaps": [{"after": "2015", "x": "2016", "label": "留空"}], "series": [{"name": "报纸", "data": [{"x": "2015", "y": 45.7}, {"x": "2017", "y": 37.6}, {"x": "2018", "y": 35.1}, {"x": "2019", "y": 27.6}, {"x": "2020", "y": 25.5}, {"x": "2021", "y": 24.6}, {"x": "2022", "y": 23.5}, {"x": "2023", "y": 23.1}, {"x": "2024", "y": 22.5}, {"x": "2025", "y": 21.2}]}, {"name": "期刊", "data": [{"x": "2015", "y": 34.6}, {"x": "2017", "y": 25.3}, {"x": "2018", "y": 23.4}, {"x": "2019", "y": 19.3}, {"x": "2020", "y": 18.7}, {"x": "2021", "y": 18.4}, {"x": "2022", "y": 17.7}, {"x": "2023", "y": 17.5}, {"x": "2024", "y": 17.1}, {"x": "2025", "y": 16.6}], "emphasis": true}]}, {"type": "callout", "variant": "info", "text": "2016 年两格没能核实，留空不连。"}], "drawnBy": ["headline"], "exhibits": [null, "图 3", null]} as PeriodicalBoardPage,
  "p07-magazine": {"heading": "报刊的线都在往下走，我们也在其中", "components": [{"type": "image", "asset_id": "magazines", "caption": "一摞旧杂志的书脊（AI 生成示意）", "fit": "cover"}, {"type": "kpi_cards", "items": [{"value": "1.57", "unit": "期", "label": "人均每年读的纸质期刊", "note": "2015 年 4.91 期，少了 68%", "icon": "book-marked"}, {"value": "2.77", "unit": "分钟", "label": "每天读期刊的时间", "note": "2015 年 8.83 分钟", "icon": "clock"}, {"value": "21.2", "unit": "%", "label": "报纸阅读率", "note": "2015 年 45.7%", "icon": "newspaper"}]}, {"type": "blockquote", "text": "这不是别人的数字。一本靠订阅读者撑着的杂志，就站在这几条线上。"}], "drawnBy": ["witness"], "exhibits": [null, null, null]} as PeriodicalBoardPage,
  "p09-heavy": {"heading": "常读书的人在慢慢变多：一年读 10 本以上纸书的人从 10.2% 升到 13.5%", "components": [{"type": "chart", "title": "一年读 10 本以上纸书的成年人（%）", "chart_type": "bar", "gaps": [{"after": "2017", "x": "2018", "label": "未公布"}, {"after": "2021", "x": "2022", "label": "未公布"}], "series": [{"name": "一年读 10 本以上纸书的成年人", "data": [{"x": "2017", "y": 10.2}, {"x": "2019", "y": 11.1}, {"x": "2020", "y": 11.6}, {"x": "2021", "y": 11.9}, {"x": "2023", "y": 12.3}, {"x": "2024", "y": 13.2}, {"x": "2025", "y": 13.5, "emphasis": true}]}]}, {"type": "callout", "variant": "info", "text": "2018、2022 年没有可核的数，留空。"}, {"type": "kpi_cards", "items": [{"value": "45.9%", "label": "最想「拿一本纸质书读」", "note": "倾向题，2024 年起可能多选"}, {"value": "30.3%", "label": "对自己的阅读满意", "note": "不满意 13.8%，一般 46.2%"}]}], "drawnBy": ["census"], "exhibits": ["图 4", null, null]} as PeriodicalBoardPage,
  "p10-gap": {"heading": "城镇和农村差 18.4 个百分点，孩子比大人读得多", "components": [{"type": "chart", "title": "城乡成年人图书阅读率（%）", "chart_type": "bar", "gaps": [{"after": "2022", "x": "2023 年起", "label": "未公布"}], "series": [{"name": "城镇", "data": [{"x": "2017", "y": 67.5}, {"x": "2019", "y": 67.9}, {"x": "2020", "y": 68.3}, {"x": "2021", "y": 68.5}, {"x": "2022", "y": 68.6}]}, {"name": "农村", "data": [{"x": "2017", "y": 49.3}, {"x": "2019", "y": 49.8}, {"x": "2020", "y": 49.9}, {"x": "2021", "y": 50}, {"x": "2022", "y": 50.2}]}]}, {"type": "callout", "variant": "info", "text": "2022 年人均纸书：城镇 5.61 本，农村 3.77 本。"}, {"type": "kpi_cards", "items": [{"value": "**86.7%**", "label": "图书阅读率，成年人是 60.0%", "tag": {"text": "0 至 17 岁的孩子"}, "icon": "baby"}, {"value": "11.72", "unit": "本", "label": "人均图书阅读量", "note": "孩子和大人的「本」口径不同，只比阅读率"}]}], "drawnBy": ["contrast"], "exhibits": ["图 5", null, null]} as PeriodicalBoardPage,
  "p11-market": {"heading": "书卖得更少也更便宜：码洋只有 2019 年的 86%，平均 5.8 折", "components": [{"type": "kpi_cards", "items": [{"value": "6.6", "unit": "折", "label": "2022", "tag": {"text": "平均折扣（实付占定价）"}}, {"value": "6.1", "unit": "折", "label": "2023"}, {"value": "**5.8**", "unit": "折", "label": "2025"}, {"value": "5.6", "unit": "折", "label": "2026 Q1"}]}, {"type": "paragraph", "text": "2025 年码洋 −2.24%，实洋 −3.80%"}, {"type": "chart", "title": "图书零售码洋（亿元，按定价计）", "chart_type": "bar", "tag": {"text": "企业口径 · 2025 年回溯后的新口径"}, "changes": [{"from": "2019", "to": "2025"}], "series": [{"name": "图书零售码洋", "data": [{"x": "2019", "y": 1286}, {"x": "2020", "y": 1221}, {"x": "2021", "y": 1241}, {"x": "2022", "y": 1095}, {"x": "2023", "y": 1146}, {"x": "2024", "y": 1129}, {"x": "2025", "y": 1104, "emphasis": true}]}]}, {"type": "callout", "variant": "info", "text": "旧口径的当年公布值约低 25.7%，不能和这条线相接。"}], "drawnBy": ["bracket"], "exhibits": [null, null, "图 6", null]} as PeriodicalBoardPage,
  "p12-channels": {"heading": "四成的书在内容电商卖出，少儿和教辅占码洋一半多", "components": [{"type": "chart", "title": "零售码洋渠道结构（%）", "chart_type": "percent_stacked", "axes": {"y_unit": "%"}, "series": [{"name": "平台电商", "data": [{"x": "2022", "y": 45.1}, {"x": "2023", "y": 41.5}, {"x": "2024", "y": 40.9}, {"x": "2025", "y": 32.4}]}, {"name": "内容电商", "data": [{"x": "2022", "y": 16.4}, {"x": "2023", "y": 26.7}, {"x": "2024", "y": 30.4}, {"x": "2025", "y": 40.5}], "emphasis": true}, {"name": "垂直及其他", "data": [{"x": "2022", "y": 23.2}, {"x": "2023", "y": 19.9}, {"x": "2024", "y": 14.7}, {"x": "2025", "y": 13.4}]}, {"name": "实体店", "data": [{"x": "2022", "y": 15.3}, {"x": "2023", "y": 11.9}, {"x": "2024", "y": 14}, {"x": "2025", "y": 13.7}]}]}, {"type": "callout", "variant": "info", "text": "内容电商指抖音、快手、小红书这类平台。"}, {"type": "image", "asset_id": "bookshop", "caption": "街角的小书店（AI 生成示意）", "fit": "cover"}, {"type": "chart", "chart_type": "stacked", "direction": "horizontal", "axes": {"y_unit": "%"}, "series": [{"name": "少儿", "data": [{"x": "2025 年码洋按品类（%）", "y": 28.79}]}, {"name": "教辅", "data": [{"x": "2025 年码洋按品类（%）", "y": 26.47}]}, {"name": "文学", "data": [{"x": "2025 年码洋按品类（%）", "y": 8.84}], "emphasis": true}, {"name": "其他", "data": [{"x": "2025 年码洋按品类（%）", "y": 35.9}]}]}, {"type": "paragraph", "text": "文学只占 8.84%。「其他」由 100 减三类计算。"}], "drawnBy": ["mix"], "exhibits": ["图 7", null, null, null, null]} as PeriodicalBoardPage,
  "p13-library": {"heading": "去图书馆的人比 2019 年多 63%，借出的书却比上年少了 0.3%", "components": [{"type": "chart", "title": "公共图书馆总流通和书刊外借，各用自己的纵轴", "chart_type": "bar", "axes": {"y_unit": "亿人次"}, "series": [{"name": "总流通", "data": [{"x": "2019", "y": 9.01}, {"x": "2020", "y": 5.41}, {"x": "2021", "y": 7.46}, {"x": "2022", "y": 7.9}, {"x": "2023", "y": 11.61}, {"x": "2024", "y": 13.4}, {"x": "2025", "y": 14.7}]}]}, {"type": "chart", "title": "公共图书馆总流通和书刊外借，各用自己的纵轴", "chart_type": "bar", "axes": {"y_unit": "亿册次"}, "series": [{"name": "书刊外借", "data": [{"x": "2019", "y": 6.14}, {"x": "2020", "y": 4.21}, {"x": "2021", "y": 5.87}, {"x": "2022", "y": 6.07}, {"x": "2023", "y": 7.83}, {"x": "2024", "y": 8.4}, {"x": "2025", "y": 8.3, "emphasis": true}]}]}, {"type": "callout", "variant": "info", "text": "每个到馆人次借出的书，从 0.68 册降到 0.56 册。城镇成年人里只有 16.2% 用过图书馆。"}], "drawnBy": ["twins"], "exhibits": ["图 8", "图 9", null]} as PeriodicalBoardPage,
  "p14-world": {"heading": "别的国家也在问这个问题，但问法不同，只能并排看", "components": [{"type": "data_table", "columns": [{"key": "who", "label": "调查"}, {"key": "ask", "label": "问的是什么"}, {"key": "now", "label": "结果"}, {"key": "before", "label": "早些时候"}], "rows": [{"cells": {"who": "美国 · Pew，2025", "ask": "过去 12 个月读过至少一本书，读一部分也算", "now": "75%", "before": "2011 年 78%"}, "icon": "flag"}, {"cells": {"who": "美国 · NEA，2022", "ask": "过去一年为兴趣读过书，不含工作和学习用书", "now": "48.5%", "before": "2012 年 54.6%"}, "icon": "flag"}, {"cells": {"who": "日本 · 文化厅，2024", "ask": "16 岁以上，一个月一本书都不读", "now": "62.6%", "before": "调查方式已改，前后不宜比"}, "icon": "flag"}, {"cells": {"who": "英国 · NLT，2026", "ask": "8 至 18 岁，喜欢课余读书", "now": "36.1%", "before": "2025 年 32.7%"}, "icon": "flag"}, {"cells": {"who": "中国 · 国民阅读调查，2025", "ask": "成年人图书阅读率，按该调查口径", "now": "60.0%", "before": "2015 年 58.4%"}, "icon": "flag"}]}, {"type": "callout", "variant": "info", "text": "问的不是同一个问题。只能并排看，不能排高低。"}], "drawnBy": ["parallel"], "exhibits": [null, null]} as PeriodicalBoardPage,
  "p15-screen": {"heading": "纸比屏幕读得懂一点，差距是小效应，主要在说明文和限时阅读", "components": [{"type": "chart", "chart_type": "bar", "direction": "horizontal", "bands": [{"from": -0.4, "to": 0, "label": "← 屏幕比纸差"}, {"from": 0, "to": 0.1, "label": "纸比屏幕差 →"}], "series": [{"name": "Delgado 等 2018", "data": [{"x": "总体", "y": -0.21}, {"x": "说明文", "y": -0.27}, {"x": "叙事文", "y": 0.01}, {"x": "限时阅读", "y": -0.26}, {"x": "自定节奏", "y": -0.09}]}, {"name": "Clinton 2019", "data": [{"x": "总体", "y": -0.25}, {"x": "说明文", "y": -0.32}, {"x": "叙事文", "y": -0.04}]}]}, {"type": "callout", "variant": "info", "text": "Hedges' g 约 0.2 是小效应，不能读成「理解提高 21%」。读纸的人对自己读懂了多少，判断也更准。"}], "drawnBy": ["effects"], "exhibits": [null, null]} as PeriodicalBoardPage,
  "p16-essay": {"heading": "读者没有离开书，离开的是报刊上那段固定的时间", "components": [{"type": "paragraph", "text": "把这些数字放在一起读，编辑部最直接的感受是：读书的人还在。十年里读书的人、读的本数几乎没动，每天读纸书的时间还多了约 5 分钟。少掉的是报刊，是从前每天留给报纸和杂志的那一段时间。"}, {"type": "paragraph", "text": "一本杂志能做的，是让值得读完的文章更容易被读完：在纸上，在耳机里，在图书馆的长桌上。下一页是编辑部接下来一年的打算，每一条都写了为什么，做到多少，明年这封信里再向你交代。"}, {"type": "blockquote", "text": "我们不打算把文章剪短，去和屏幕抢那几秒钟。"}], "drawnBy": ["longform"], "exhibits": [null, null, null]} as PeriodicalBoardPage,
  "p17-plans": {"heading": "接下来一年，编辑部打算做四件事，每件都从这些数字里来", "components": [{"type": "icon_cards", "items": [{"icon": "book-open", "title": "每期留一篇能读完的长文", "text": "为什么：纸书的时间十年没少，45.9% 的人最想拿一本纸质书读"}, {"icon": "headphones", "title": "重点文章出音频版", "text": "为什么：38.7% 的成年人在听书，文章也该能被听完"}, {"icon": "library", "title": "读者会搬进公共图书馆", "text": "为什么：到馆人次比 2019 年多 63%，借书却停了"}, {"icon": "pen-line", "title": "每个数字都写明口径", "text": "为什么：这封信里的数，几乎每个都要带着口径读"}]}, {"type": "image", "asset_id": "library", "caption": "公共图书馆的阅览区（AI 生成示意）", "fit": "cover"}, {"type": "callout", "variant": "info", "text": "以上是编辑部的计划，不是已经做到的事。数字来源见前文各页。"}], "drawnBy": ["pledges"], "exhibits": [null, null, null]} as PeriodicalBoardPage,
}
