import type { Component } from "@/ir"

/*
 * ember's 2026-10 board, its content pages p03 to p15 as the showcase deck
 * writes them (`showcase/ember/zh`), less the heading, the rail, the deck's
 * label and the source line, which are the face's, and less the medical
 * page's photograph, which the photo face sets beside its column. Each page
 * names the composition that draws it in the pitch setting.
 */

export interface PitchBoardPage {
  components: Component[]
  drawnBy: string[]
}

export const PITCH_BOARD: Record<string, PitchBoardPage> = {
  "p03-gap": {"components": [{"type": "kpi_cards", "items": [{"value": "600 亿", "label": "2025 年全国即时配送订单，一年"}, {"value": "**100 万+**", "label": "美团无人机多年累计商业订单"}, {"value": "约十万分之二", "label": "多年累计比一年单量，只说明数量级"}]}, {"type": "paragraph", "text": "订单都在地上跑，天上的份额几乎为零。这不是证明需求，是证明空间还没被占。"}], "drawnBy": ["expanse"]} as PitchBoardPage,
  "p04-why-now": {"components": [{"type": "timeline", "milestones": [{"date": "2024", "icon": "file-check", "title": "规则落地", "desc": "条例和 CCAR-92 于 1 月 1 日同日生效。运营合格证、执照、保险有了统一门槛"}, {"date": "2025", "icon": "route", "title": "顺序定了", "desc": "发改委：先载货、先隔离、先远郊。载货配送排在放行顺序最前面"}, {"date": "2026", "icon": "trending-up", "title": "定位升了", "desc": "第三年写进政府工作报告。列为「新兴支柱产业」", "highlight": true}]}, {"type": "callout", "variant": "info", "text": "底盘也在放大：2025 年全国无人机飞行 4530 万小时（同比 +69.89%），持证运营单位 38872 家"}], "drawnBy": ["stairs"]} as PitchBoardPage,
  "p05-funnel": {"components": [{"type": "chart", "chart_type": "funnel", "axes": {"y_unit": "个"}, "series": [{"name": "深圳 2026 年起降点规划目标", "data": [{"x": "起降点总目标（2026 年）", "y": 1200}, {"x": "其中社区配送", "y": 413}, {"x": "其中医疗", "y": 148}]}]}, {"type": "kpi_cards", "items": [{"value": "1284 个", "label": "实绩已经跟上", "note": "2025 年底深圳实有起降点，提前超过 1200 个的目标"}]}, {"type": "callout", "variant": "info", "title": "对我们意味着", "text": "医疗和社区的点位是规划里写死的，不用自己说服城市修。"}], "drawnBy": ["funnel"]} as PitchBoardPage,
  "p06-landscape": {"components": [{"type": "data_table", "columns": [{"key": "who", "label": "先行者"}, {"key": "scene", "label": "主场景"}, {"key": "scale", "label": "公开规模"}, {"key": "network", "label": "网络"}, {"key": "cost", "label": "单均成本绝对额", "emphasis": true, "icon": "circle-help"}], "rows": [{"icon": "utensils", "cells": {"who": "美团", "scene": "城市餐饮、医疗", "scale": "累计超过 100 万单", "network": "70 条航线，6 城", "cost": "未公布"}}, {"icon": "package", "cells": {"who": "顺丰丰翼", "scene": "快递、跨海、城际", "scale": "深圳日飞六七百架次", "network": "深圳 383 条航线", "cost": "未公布"}}, {"icon": "truck", "cells": {"who": "京东物流", "scene": "城乡末端、山区", "scale": "资中覆盖 78 个村", "network": "资中首批 78 条", "cost": "未公布"}}, {"icon": "hospital", "cells": {"who": "迅蚁", "scene": "医疗为主", "scale": "累计飞行 260 万千米", "network": "55 城", "cost": "未公布"}}, {"icon": "plane", "cells": {"who": "Zipline", "scene": "医疗加零售", "scale": "累计超过 250 万次", "network": "约 70% 航班在美国", "cost": "未公布"}}, {"icon": "store", "cells": {"who": "Wing", "scene": "零售", "scale": "超过 100 万次", "network": "2027 年沃尔玛 270 多个点", "cost": "未公布"}}]}, {"type": "callout", "variant": "info", "text": "六家都没有公布单均成本的绝对额，美团只说每年降 40% 至 50%。谁先算清这笔账，谁就有话语权。"}], "drawnBy": ["rivals"]} as PitchBoardPage,
  "p08-wedge": {"components": [{"type": "concept_equation", "operands": [{"icon": "route", "label": "放行顺序", "value": "载货先行", "note": "先隔离、先远郊（发改委）"}, {"icon": "map-pin", "label": "城市规划", "value": "413 个", "note": "深圳社区起降点，其中医疗 148 个"}, {"icon": "hospital", "label": "已验证需求", "value": "460 万管", "note": "迅蚁累计医疗标本（企业口径）"}], "result": {"label": "我们的楔子", "value": "医疗 + 社区", "note": "先做有起降点的园区和城郊"}, "excluded": {"icon": "ban", "label": "先不做", "value": "核心城区的餐饮高峰单", "note": "它排在放行顺序最后，也是美团的主场"}}], "drawnBy": ["equation"]} as PitchBoardPage,
  "p09-medical": {"components": [{"type": "kpi_cards", "items": [{"value": "**460 万**", "label": "迅蚁累计运送医疗标本（管），截至 2025-11，企业口径"}, {"value": "81 万", "label": "美团累计配送检验样本和药品（份），截至 2026-06"}, {"value": "2.5 kg", "label": "美团第四代机最大载重，标本箱够用"}]}], "drawnBy": ["spotlight"]} as PitchBoardPage,
  "p10-hypotheses": {"components": [{"type": "gantt", "range": {"from": 0, "to": 18}, "axis_labels": ["第 1 个月", "第 18 个月"], "items": [{"label": "单均成本低于骑手", "icon": "coins", "start": 15, "end": 18, "period": "第 16 至 18 个月验证", "text": "参照：美团 2022 年每笔配送相关成本约 4.54 元（计算）", "emphasis": true}, {"label": "单个起降点日单量能爬坡", "icon": "trending-up", "start": 9, "end": 15, "period": "第 10 至 15 个月验证", "text": "参照：美团单站日单量从约 10 单升到最高 400 单（企业口径）"}, {"label": "取证后能安全、稳定地复飞", "icon": "shield-check", "start": 6, "end": 9, "period": "第 7 至 9 个月验证", "text": "参照：深圳 2025 年无人机载货运输超过百万架次"}]}], "drawnBy": ["bets"]} as PitchBoardPage,
  "p11-unit-economics": {"components": [{"type": "kpi_cards", "items": [{"value": "4.54", "unit": "元/笔", "label": "美团 2022 年配送相关成本 ÷ 即时配送笔数（计算）", "tag": {"text": "骑手侧 · 有绝对额"}}, {"value": "6.9", "unit": "元/单", "label": "安信国际估算，只算 1P 外卖单，分母更小", "tag": {"text": "骑手侧 · 有绝对额"}}, {"value": "40%-50%", "unit": "/年", "label": "美团无人机单均运营成本年降幅，没有绝对额", "tag": {"text": "无人机侧 · 只有降幅和海外估算"}}, {"value": "5-7", "unit": "美元/单", "label": "巴克莱：欧美高人工地区的自动配送", "tag": {"text": "无人机侧 · 只有降幅和海外估算"}}]}, {"type": "verdict_banner", "text": "要证明：同一口径下，医疗航线的单均成本低于 4.54 元", "tone": "neutral", "icon": "target"}], "drawnBy": ["divide"]} as PitchBoardPage,
  "p12-compliance": {"components": [{"type": "chevron_process", "items": [{"title": "实名登记", "text": "两项强制国标 2026-05-01 实施", "icon": "fingerprint-pattern"}, {"title": "操控员执照", "text": "小型机操控员必须持照", "icon": "id-card"}, {"title": "责任保险", "text": "经营性飞行必须投保", "icon": "umbrella"}, {"title": "特定类评估", "text": "SORA 2.5 版指南仍在征求意见", "icon": "file-check"}, {"title": "运营合格证", "text": "CCAR-92，有效期 24 个月", "icon": "badge-check"}]}, {"type": "kpi_cards", "items": [{"value": "5 万至 50 万元", "label": "没过关的代价", "note": "无运营合格证飞行的罚款（条例第四十九条）"}, {"value": "120 米", "label": "120 米以下也不等于随便飞", "note": "机场、重要设施上空另划为管制空域（条例第十九条）"}]}], "drawnBy": ["locks"]} as PitchBoardPage,
  "p13-risks": {"components": [{"type": "data_table", "columns": [{"key": "risk", "label": "风险"}, {"key": "case", "label": "已发生的先例"}, {"key": "plan", "label": "我们的应对"}, {"key": "when", "label": "何时"}], "rows": [{"icon": "construction", "cells": {"risk": "撞上障碍物", "case": "Amazon 两架 MK30 撞吊车起火（2025-10，NTSB）", "plan": "航线逐段勘测，施工吊车每日更新", "when": "1-6 月"}, "emphasis": "highlight"}, {"icon": "triangle-alert", "cells": {"risk": "迫降", "case": "丰翼方舟 80 在深圳开伞迫降（2026-02）", "plan": "航线避开人群上空，机上带伞", "when": "1-6 月"}}, {"icon": "zap", "cells": {"risk": "电力设施", "case": "Wing 落上电线，约 2000 户停电（2022-09）", "plan": "起降点和航线避开架空线", "when": "7-9 月"}}, {"icon": "volume-2", "cells": {"risk": "噪音与社区", "case": "Wing 堪培拉试点引发噪音审查（2019）", "plan": "先园区和城郊，进社区前先公示", "when": "10-15 月"}}, {"icon": "umbrella", "cells": {"risk": "保险", "case": "强制投保最低保额 2027 年前后才出台", "plan": "开飞前足额投保第三者责任险", "when": "1-6 月"}}, {"icon": "coins", "cells": {"risk": "后续融资", "case": "低空大额融资里运营服务只占 2.2%（2026 上半年，全球口径）", "plan": "按里程碑分段用钱，每段单独验收", "when": "全程"}}]}], "drawnBy": ["register"]} as PitchBoardPage,
  "p14-milestones": {"components": [{"type": "roadmap", "duration_unit": "个月", "items": [{"title": "取得运营合格证", "period": "第 1 至 6 个月", "icon": "file-check", "duration": 6, "checkpoint": "闸门：第 6 个月", "points": ["运营合格证、操控员执照", "第三者责任险足额投保", "完成特定类风险评估"], "emphasis": true}, {"title": "首条医疗航线", "period": "第 7 至 9 个月", "icon": "hospital", "duration": 3, "points": ["园区或城郊医疗点对点", "验证假设 3：安全稳定复飞"]}, {"title": "接入社区起降点", "period": "第 10 至 15 个月", "icon": "map-pin", "duration": 6, "points": ["从医疗点扩到社区起降点", "验证假设 2：单站日单量爬坡"]}, {"title": "成本对表", "period": "第 16 至 18 个月", "icon": "coins", "duration": 3, "points": ["同口径对比 4.54 元", "带三组数据开下一轮"]}]}, {"type": "callout", "variant": "warn", "icon": "flag", "text": "闸门：第 6 个月拿不到运营合格证，就暂停航线投入，先补取证"}], "drawnBy": ["runway"]} as PitchBoardPage,
  "p15-ask": {"components": [{"type": "kpi_cards", "items": [{"value": "支撑 18 个月\n三道验证", "label": "本轮请求", "note": "从取证到第一组同口径成本数据。金额按里程碑和尽调确定。"}]}, {"type": "chart", "chart_type": "stacked", "direction": "horizontal", "axes": {"y_unit": "%"}, "series": [{"name": "取证与安全体系", "data": [{"x": "图中比例为拟定用途占比", "y": 30}]}, {"name": "航线与起降点", "data": [{"x": "图中比例为拟定用途占比", "y": 30}]}, {"name": "机队与运维", "data": [{"x": "图中比例为拟定用途占比", "y": 25}]}, {"name": "团队与运营", "data": [{"x": "图中比例为拟定用途占比", "y": 15}]}]}, {"type": "callout", "variant": "info", "icon": "hand-coins", "text": "参照：城市物流运营公司的公开单笔融资在数千万元量级（迅蚁 C+ 轮，2025-11）"}], "drawnBy": ["uses"]} as PitchBoardPage,
}
