import type { Component, Slide } from "@/ir"

/*
 * almanac's 2026-10 board, its content pages p02 to p16 as the showcase deck
 * writes them (`showcase/almanac/zh`), less the heading, the strip of years
 * and the source line, which are the face's. Each page names the
 * compositions that draw it in the yearbook setting.
 */

export interface YearbookBoardPage {
  kicker: string
  tag?: NonNullable<Slide["tag"]>
  components: Component[]
  drawnBy: string[]
}

export const YEARBOOK_BOARD_IMAGES = ["fasteners", "ingots", "solar", "scrap", "eaf", "dri"] as const

export const YEARBOOK_BOARD: Record<string, YearbookBoardPage> = {
  "p02-ask": {"kicker": "决定", "components": [{"type": "row_cards", "items": [{"icon": "receipt-euro", "title": "账单已经在累计", "text": "2026 年的进口按默认值算，热轧卷每吨约 €164，2027 年 9 月 30 日一次清缴"}, {"icon": "file-check", "title": "最快的降费：改报实际排放", "text": "铝按行业均值情景，每吨从约 €144 降到约 €14，前提是过欧盟认可的核查"}, {"icon": "sprout", "title": "绿电和工艺：今天不减账单，长期要做", "text": "绿电是国内考核和客户要求，工艺要赶在 2034 年免费配额清零之前定路线"}]}, {"type": "insight_panel", "icon": "gavel", "title": "请委员会定", "rows": [{"label": "批准改报实际排放", "text": "启动 2026 年排放核算，约定欧盟认可的核查机构"}, {"label": "列入三条预算项", "text": "核算与核查、绿证采购、电炉和直接还原铁可研"}]}], "drawnBy": ["motion"]} as YearbookBoardPage,
  "p03-timeline": {"kicker": "时间", "tag": {"text": "条例 (EU) 2025/2083 修订后第 6、20、22 至 24 条", "basis": "law"}, "components": [{"type": "timeline", "periods": [{"from": "2026-01", "to": "2026-12", "label": "2026 年：进口计入排放，不必持有证书"}, {"from": "2027-01", "to": "2027-12", "label": "2027 年：开卖、清缴、作废"}], "milestones": [{"date": "2026-01-01", "title": "正式期开始", "desc": "进口货物开始计入排放"}, {"date": "2026-04-07", "title": "Q1 证书价 €75.36", "desc": "2026 年按季度公布"}, {"date": "2027-02-01", "title": "证书开卖", "desc": "此后每季末须持有 50%"}, {"date": "2027-09-30", "title": "首次申报并清缴", "desc": "一次清完 2026 年全年", "highlight": true}, {"date": "2027-11-01", "title": "2026 年证书作废", "desc": "多买的只能年内回购"}]}, {"type": "kpi_cards", "items": [{"label": "Q1 2026 证书价", "value": "€75.36", "note": "官方公布 · 2026-04-07"}, {"label": "Q2 2026 证书价", "value": "€75.28", "note": "官方公布 · 2026-07-06"}, {"label": "Q3 2026 证书价", "value": "**€82.32**", "note": "按法定方法复算", "tag": {"text": "官方待公布", "basis": "pending"}}]}, {"type": "callout", "variant": "info", "icon": "landmark", "title": "谁付", "text": "法律上是欧盟的授权 CBAM 申报人，不是我们的工厂。负担归谁，看合同。"}], "drawnBy": ["calendar"]} as YearbookBoardPage,
  "p04-curve": {"kicker": "账单", "components": [{"type": "chart", "chart_type": "line", "axes": {"y_unit": "€"}, "tag": {"text": "演示 · 碳价冻结在 €75.36，不是预测", "basis": "estimate"}, "series": [{"name": "碳钢螺钉螺栓", "data": [{"x": "2026", "y": 428}, {"x": "2027", "y": 479}, {"x": "2028", "y": 532}, {"x": "2029", "y": 545}, {"x": "2030", "y": 572}, {"x": "2031", "y": 584}, {"x": "2032", "y": 597}, {"x": "2033", "y": 610}, {"x": "2034", "y": 625}]}, {"name": "铝板带", "data": [{"x": "2026", "y": 232}, {"x": "2027", "y": 266}, {"x": "2028", "y": 303}, {"x": "2029", "y": 317}, {"x": "2030", "y": 346}, {"x": "2031", "y": 360}, {"x": "2032", "y": 374}, {"x": "2033", "y": 388}, {"x": "2034", "y": 404}]}, {"name": "热轧卷", "data": [{"x": "2026", "y": 164}, {"x": "2027", "y": 190}, {"x": "2028", "y": 219}, {"x": "2029", "y": 232}, {"x": "2030", "y": 259}, {"x": "2031", "y": 272}, {"x": "2032", "y": 285}, {"x": "2033", "y": 298}, {"x": "2034", "y": 312}], "emphasis": true}, {"name": "未锻轧铝", "data": [{"x": "2026", "y": 144}, {"x": "2027", "y": 169}, {"x": "2028", "y": 197}, {"x": "2029", "y": 211}, {"x": "2030", "y": 239}, {"x": "2031", "y": 252}, {"x": "2032", "y": 265}, {"x": "2033", "y": 279}, {"x": "2034", "y": 294}]}]}, {"type": "timeline", "title": "CBAM 因子", "milestones": [{"date": "2026", "title": "97.5%"}, {"date": "2027", "title": "95%"}, {"date": "2028", "title": "90%"}, {"date": "2029", "title": "77.5%"}, {"date": "2030", "title": "51.5%"}, {"date": "2031", "title": "39%"}, {"date": "2032", "title": "26.5%"}, {"date": "2033", "title": "14%"}, {"date": "2034", "title": "0%", "highlight": true}]}, {"type": "kpi_cards", "items": [{"value": "**€163.5**", "label": "热轧卷 2026 年每吨", "note": "每出口 1 万吨约 €164 万", "icon": "receipt-euro"}, {"value": "€312", "label": "热轧卷 2034 年每吨", "note": "免费配额退到零", "icon": "calendar-clock"}]}], "drawnBy": ["horizon"]} as YearbookBoardPage,
  "p05-waterfall": {"kicker": "账单", "tag": {"text": "条例 2025/2083 第 6(2)(c) 条 · 实施条例 2025/2620 第 6 式", "basis": "law"}, "components": [{"type": "waterfall", "unit": "€", "items": [{"label": "中国默认值", "value": 240.2, "kind": "total", "note": "3.187 吨"}, {"label": "加成 10%", "value": 24.0, "note": "+0.319 吨"}, {"label": "免费配额调整", "value": -100.7, "note": "0.975 × 1.370 = 1.336 吨", "emphasis": true}, {"label": "应清缴", "value": 163.5, "kind": "total", "note": "2.170 吨"}]}, {"type": "code", "language": "formula", "title": "公式", "code": "n = D × (1 + m)\n  − 因子 × CSCF × BM\n成本 = n × P"}, {"type": "bullets", "items": ["D：默认值 3.187", "m：加成 10%", "因子：97.5%", "CSCF：100%", "BM：欧盟基准 1.370", "P：€75.36"]}], "drawnBy": ["formula"]} as YearbookBoardPage,
  "p06-miscalc": {"kicker": "账单", "components": [{"type": "comparison", "columns": ["常见误算", "法规公式"], "recommended": 1, "rows": [{"label": "免费部分怎么扣", "cells": ["排放 × 97.5%", "0.975 × 欧盟基准 1.370"]}, {"label": "2026 年热轧卷每吨", "cells": ["约 €3.6 至 €6", "约 €163.5"], "emphasis": true}, {"label": "出处", "cells": ["多家媒体和咨询网站", "实施条例 (EU) 2025/2620 第 6 式"]}]}, {"type": "callout", "variant": "info", "text": "**为什么差这么多：**扣的是「欧盟基准 × 因子」，不是「排放 × 因子」。中国默认值 3.187 远高于基准 1.370，高出的部分从第一年就全额计费。报价、预算和合同谈判一律按法规公式。"}], "drawnBy": ["errata"]} as YearbookBoardPage,
  "p07-exposure": {"kicker": "暴露", "components": [{"type": "chart", "chart_type": "stacked", "direction": "horizontal", "axes": {"y_unit": "亿欧元"}, "emphasis_label": "第 73 章制品 €93.5 亿，占 69.5%", "series": [{"name": "第 72 章钢材", "data": [{"x": "2025 年欧盟自中国进口的 CBAM 钢铁，按金额", "y": 41.0}]}, {"name": "7326 其他钢制品", "emphasis": true, "data": [{"x": "2025 年欧盟自中国进口的 CBAM 钢铁，按金额", "y": 34.0}]}, {"name": "7308 钢结构件", "emphasis": true, "data": [{"x": "2025 年欧盟自中国进口的 CBAM 钢铁，按金额", "y": 24.1}]}, {"name": "7318 螺钉螺栓", "emphasis": true, "data": [{"x": "2025 年欧盟自中国进口的 CBAM 钢铁，按金额", "y": 17.0}]}, {"name": "第 73 章其余", "emphasis": true, "data": [{"x": "2025 年欧盟自中国进口的 CBAM 钢铁，按金额", "y": 18.4}]}]}, {"type": "kpi_cards", "items": [{"value": "907 万吨", "label": "2025 年欧盟自中国进口 CBAM 钢铁", "note": "金额 €134.6 亿", "icon": "ship"}, {"value": "**21.1%**", "label": "占欧盟自域外同类进口金额，排第一", "note": "第二是土耳其 €71.8 亿", "icon": "chart-column"}, {"value": "€32.5 亿", "label": "铝：61.3 万吨，占 10.7%", "note": "42% 是其他铝制品 7616", "icon": "package"}]}], "drawnBy": ["breakdown"]} as YearbookBoardPage,
  "p08-products": {"kicker": "暴露", "components": [{"type": "image", "asset_id": "fasteners", "fit": "cover", "caption": "示意图：紧固件仓库（AI 生成）"}, {"type": "chart", "chart_type": "bar", "direction": "horizontal", "axes": {"y_title": "中国默认值，tCO₂e/吨（加成前）"}, "reference": {"value": 1.37, "label": "欧盟基准约 1.37"}, "series": [{"name": "中国默认值", "data": [{"x": "热轧材 7208", "y": 3.187}, {"x": "钢结构件 7308", "y": 6.035}, {"x": "碳钢螺钉螺栓 7318 15", "y": 6.375, "emphasis": true}]}]}, {"type": "kpi_cards", "items": [{"value": "**€428**", "label": "螺钉螺栓 2026 年每吨", "note": "是热轧卷的 2.6 倍", "icon": "receipt-euro"}, {"value": "€625", "label": "螺钉螺栓 2034 年每吨", "icon": "calendar-clock", "tag": {"text": "演示 · 碳价冻结在 €75.36，不是预测", "basis": "estimate"}}]}], "drawnBy": ["benchmark"]} as YearbookBoardPage,
  "p09-countries": {"kicker": "暴露", "components": [{"type": "chart", "chart_type": "bar", "direction": "horizontal", "axes": {"y_title": "热轧扁平材 7208 默认值，tCO₂e/吨（加成前）"}, "reference": {"value": 1.37, "label": "欧盟基准 1.370"}, "series": [{"name": "热轧扁平材 7208 默认值", "data": [{"x": "印度", "y": 4.28}, {"x": "中国", "y": 3.187, "emphasis": true}, {"x": "乌克兰", "y": 2.483}, {"x": "土耳其", "y": 2.428}, {"x": "越南", "y": 2.35}, {"x": "韩国", "y": 2.118}]}]}, {"type": "kpi_cards", "items": [{"value": "**约 €63**", "label": "中国热轧卷 2026 年每吨比土耳其多付", "note": "€163.5 对 €100.6", "icon": "scale"}, {"value": "2.3 倍", "label": "中国默认值是欧盟基准 1.370 的倍数", "note": "韩国 1.5 倍，土耳其 1.8 倍", "icon": "trending-up"}]}, {"type": "callout", "variant": "info", "text": "比的是「大家都用默认值」时的差距。对手改报实际值后，差距会变。"}], "drawnBy": ["benchmark"]} as YearbookBoardPage,
  "p10-actual": {"kicker": "降费", "components": [{"type": "chart", "chart_type": "bar", "axes": {"y_title": "未锻轧铝每吨证书费用", "y_unit": "€"}, "tag": {"text": "演示 · 碳价冻结在 €75.36，不是预测", "basis": "estimate"}, "series": [{"name": "默认值路径", "data": [{"x": "2026", "y": 144}, {"x": "2027", "y": 169}, {"x": "2028", "y": 197}, {"x": "2030", "y": 239}, {"x": "2034", "y": 294}]}, {"name": "实际值情景 1.57", "emphasis": true, "data": [{"x": "2026", "y": 14}, {"x": "2027", "y": 16}, {"x": "2028", "y": 22}, {"x": "2030", "y": 63}, {"x": "2034", "y": 118}]}]}, {"type": "image", "asset_id": "ingots", "fit": "cover", "caption": "示意图：原铝锭（AI 生成）"}, {"type": "callout", "variant": "warn", "icon": "file-check", "title": "1.57 是据报道的行业协会口径", "text": "不是本企业实测。用实际值不加 10% 至 30% 的加成，但必须过欧盟认可的核查。", "tag": {"text": "本企业实测：待核查后填入", "basis": "pending"}}], "drawnBy": ["paired"]} as YearbookBoardPage,
  "p11-verify": {"kicker": "核查", "components": [{"type": "steps", "items": [{"icon": "calculator", "title": "按欧盟方法核算", "text": "实施条例 2025/2547 规定算法，钢铝只算直接排放"}, {"icon": "badge-check", "title": "找认可核查机构", "text": "由成员国认可机构认可，欧盟以外的机构也可申请"}, {"icon": "factory", "title": "**首年实地查厂**", "text": "首个核查年度必须现场核查，之后至少每两年一次"}, {"icon": "send", "title": "交给欧盟申报人", "text": "2027 年 9 月 30 日前随 2026 年申报一并提交"}]}, {"type": "comparison", "columns": ["默认值申报", "实际值申报"], "recommended": 1, "rows": [{"label": "核查", "cells": ["不需要", "必须由欧盟认可的机构核查"]}, {"label": "加成", "cells": ["2026 年 10%，2028 年起 30%", "不加"]}, {"label": "抵扣中国碳价", "cells": ["只能按年度默认碳价", "可扣实际已付碳价"]}]}], "drawnBy": ["procedure"]} as YearbookBoardPage,
  "p12-china-price": {"kicker": "抵扣", "components": [{"type": "kpi_cards", "items": [{"value": "**±3%**", "label": "2026 年度钢铝企业配额", "note": "配额基本按核查排放等量发放，企业最多为约 3% 的排放实际花钱。", "tag": {"text": "国环规气候〔2026〕1 号", "basis": "law"}}]}, {"type": "code", "language": "formula", "code": "A = E × (1 + α)，−3% ≤ α ≤ +3%"}, {"type": "chart", "chart_type": "bar", "direction": "horizontal", "axes": {"y_title": "2025 年碳价，€/吨 CO₂", "y_unit": "€"}, "series": [{"name": "2025 年均价", "data": [{"x": "欧盟 EUA", "y": 73.43}, {"x": "中国 CEA", "y": 7.68, "emphasis": true, "note": "62.36 元"}]}]}, {"type": "kpi_cards", "items": [{"value": "约 9.6 倍", "label": "欧中碳价差（2025 年均价，按欧洲央行汇率折算）", "note": "用默认值申报时，只能按欧盟公布的年度默认碳价扣减", "tag": {"text": "第 9 条抵扣细则：仍是草案", "evidence": "draft"}}]}], "drawnBy": ["magnitude"]} as YearbookBoardPage,
  "p13-green-power": {"kicker": "绿电", "components": [{"type": "image", "asset_id": "solar", "fit": "cover", "caption": "示意图：钢厂屋顶光伏（AI 生成）"}, {"type": "chart", "chart_type": "stacked", "direction": "horizontal", "axes": {"y_unit": "tCO₂"}, "emphasis_label": "CBAM 只算这段", "series": [{"name": "直接排放", "emphasis": true, "data": [{"x": "电解铝每吨排放的两段", "y": 3.0}]}, {"name": "电力间接排放（范围二）", "data": [{"x": "电解铝每吨排放的两段", "y": 7.0, "note": "绿电降的是这段，今天不进 CBAM 账单"}]}]}, {"type": "callout", "variant": "info", "text": "直接排放取欧盟默认值 3.000，间接 = 13,202 kWh × 0.5306 kgCO₂/kWh。Guidance No.3：不允许用绿证确定排放因子。"}, {"type": "kpi_cards", "items": [{"value": "**0**", "label": "买绿电、绿证今天能减的 CBAM 证书", "note": "钢铝只计直接排放", "icon": "scale"}, {"value": "25.2% 至 70%", "label": "2025 年各省电解铝绿电消费比例", "note": "国内考核，按绿证核算", "icon": "zap"}, {"value": "约 83 元", "label": "每吨电解铝对应的绿证", "note": "13.2 个 × 6.32 元，RE100 认可", "icon": "sun"}]}], "drawnBy": ["segments"]} as YearbookBoardPage,
  "p14-routes": {"kicker": "工艺", "components": [{"type": "image_grid", "items": [{"asset_id": "scrap", "caption": "废钢"}, {"asset_id": "eaf", "caption": "电炉"}, {"asset_id": "dri", "caption": "直接还原竖炉"}]}, {"type": "chart", "chart_type": "bar", "direction": "horizontal", "axes": {"y_title": "吨钢 CO₂，世界钢协全口径（不能直接代入 CBAM）"}, "series": [{"name": "吨钢 CO₂", "data": [{"x": "高炉转炉", "y": 2.34, "note": "基准线"}, {"x": "直接还原铁电炉", "y": 1.47, "note": "低约 37%"}, {"x": "废钢电炉", "y": 0.69, "note": "低约 70%"}]}]}, {"type": "callout", "variant": "info", "icon": "atom", "title": "氢冶金示范：减碳约 70%", "text": "河钢张宣科技 120 万吨项目自称，比同规模长流程。", "tag": {"text": "企业口径 · 据报道", "evidence": "company"}}], "drawnBy": ["survey"]} as YearbookBoardPage,
  "p15-rules": {"kicker": "规则", "components": [{"type": "timeline", "periods": [{"from": "2026", "to": "2034", "label": "现行法律：免费配额 2034 年清零", "basis": "law"}, {"from": "2034", "to": "2038", "label": "提案：延到 2038", "basis": "proposal"}], "milestones": [{"date": "2027", "title": "默认值最迟复审", "desc": "加成 2028 年起升到 30%", "icon": "file-text", "tag": {"text": "已定"}, "source": "实施条例 (EU) 2025/2621"}, {"date": "2028", "title": "下游扩围拟起适用", "desc": "更多钢铝制品纳入", "icon": "layers", "tag": {"text": "谈判中", "basis": "proposal"}, "source": "COM(2025) 989，三方谈判中"}, {"date": "2038", "title": "免费配额清零拟推迟", "desc": "热轧卷 2034 年约 €297（提案情景）", "icon": "hourglass", "tag": {"text": "提案", "basis": "proposal"}, "source": "COM(2026) 616（2026-07-17）"}]}, {"type": "callout", "variant": "info", "text": "两件提案都还不是法律，测算仍按现行法律。每季度跟踪一次，有变化再回委员会。"}], "drawnBy": ["outlook"]} as YearbookBoardPage,
  "p16-roadmap": {"kicker": "路线", "components": [{"type": "roadmap", "items": [{"title": "定方法、定机构", "period": "2026 年四季度", "rows": [{"label": "核算", "value": "按欧盟方法核算 2026 年直接排放"}, {"label": "核查", "value": "约定欧盟认可的核查机构"}, {"label": "合同", "value": "梳理欧盟客户的 CBAM 费用条款"}, {"label": "预算项", "value": "核算与核查费用：待定", "basis": "pending"}]}, {"title": "实地核查", "period": "2027 年上半年", "rows": [{"label": "核查", "value": "首个核查年度实地查厂"}, {"label": "绿电", "value": "按国内考核比例采购绿证"}, {"label": "披露", "value": "范围一、二排放与核查口径对齐"}, {"label": "预算项", "value": "绿证采购：待定", "basis": "pending"}]}, {"title": "首次清缴", "period": "2027 年 9 月 30 日", "emphasis": true, "rows": [{"label": "交付", "value": "向申报人提交经核查的排放"}, {"label": "清缴", "value": "申报人清缴 2026 年证书"}]}, {"title": "工艺可研", "period": "2028 年起", "rows": [{"label": "可研", "value": "电炉、直接还原铁路线比选"}, {"label": "预算项", "value": "可研费用：待定", "basis": "pending"}]}]}], "drawnBy": ["phases"]} as YearbookBoardPage,
}
