/**
 * Regenerates `evals/gallery/fixtures/images/screenshot-1.jpg`, the product
 * screenshot every `device_mockup` specimen in the gallery is framed around.
 *
 * The asset it replaces was generated by an image model with a prompt that
 * asked for the letters to be unreadable, so every mockup in the review
 * matrix was a soft blob and no reviewer could tell a crisp frame from a
 * blurry one. This renders a real dashboard page through this repo's own
 * render chain instead: same `validateIr` + `renderSlideSvg` pair the CLI
 * uses, then sharp at the fixture's exact 1280x720.
 *
 *   pnpm tsx scripts/make-screenshot-fixture.mts
 */

import { createHash } from "node:crypto"
import { mkdirSync, writeFileSync } from "node:fs"
import { dirname, resolve } from "node:path"
import { fileURLToPath } from "node:url"
import sharp from "sharp"
import type { PptxIR } from "../src/ir"
import { renderSlideSvg, validateIr } from "../src/api"
import { installNodePlatform } from "../src/platform/node"
import { getPlatform } from "../src/platform/registry"
import { CANVAS_H_PX, CANVAS_W_PX } from "../src/constants"

/** Fixture paths, relative to the repository root. */
export const FIXTURE_JPG = "evals/gallery/fixtures/images/screenshot-1.jpg"
export const FIXTURE_JSON = "evals/gallery/fixtures/images/screenshot-1.json"

/**
 * Every encoder setting that decides this file's bytes. Exported and recorded
 * in the provenance, because the fixture's contract is not only "which page"
 * but "written how": editing the quality and forgetting to regenerate used to
 * leave a JPEG nothing checked, and the pixel tolerance is deliberately wide
 * enough to absorb a re-encode down to quality 60.
 */
export const ENCODER = { quality: 88, chromaSubsampling: "4:4:4" } as const

/**
 * The screen contents: an analytics dashboard for a made-up product, in the
 * gallery's own zh register. Neutral product copy, no maintainer vocabulary,
 * no placeholder latin.
 */
export const SCREENSHOT_IR: PptxIR = {
  version: "5",
  filename: "screenshot-1",
  theme: { id: "enterprise" },
  meta: { organization: "云雀数据" },
  // The page draws itself — no picture on it, so no asset to declare.
  assets: { images: {} },
  slides: [
    {
      id: "board",
      type: "content",
      kind: "data",
      heading: "云雀增长看板",
      subheading: "近三十天核心指标",
      components: [
        {
          type: "kpi_cards",
          items: [
            { value: "18.4", unit: "万", label: "月活用户", delta: "up" },
            { value: "62.7", unit: "%", label: "次周留存", delta: "up" },
            { value: "4.9", unit: "分", label: "满意度", delta: "flat" },
            { value: "1.32", unit: "秒", label: "首屏耗时", delta: "down" },
          ],
        },
        {
          type: "chart",
          chart_type: "line",
          axes: { x_title: "周次", y_title: "活跃用户", y_unit: "万", show_grid: true },
          series: [
            {
              name: "移动端",
              data: [
                { x: "第一周", y: 9.2 },
                { x: "第二周", y: 10.4 },
                { x: "第三周", y: 11.1 },
                { x: "第四周", y: 12.6 },
              ],
            },
            {
              name: "网页端",
              data: [
                { x: "第一周", y: 4.8 },
                { x: "第二周", y: 5.1 },
                { x: "第三周", y: 5.6 },
                { x: "第四周", y: 5.8 },
              ],
            },
          ],
        },
      ],
    },
  ],
}

/**
 * The fixture's contract size. It is the canvas size on purpose: the page is
 * rendered at 1:1 and never resampled, which is where the crispness comes from.
 */
export const FIXTURE_W = CANVAS_W_PX
export const FIXTURE_H = CANVAS_H_PX

/**
 * Digest of the page this fixture is a picture of.
 *
 * Recorded instead of a generation date. A date changes on every run, so the
 * committed bundle was never twice the same bytes even when the picture was
 * identical, and it said nothing about whether the JPEG on disk still matches
 * the IR above it. The digest says exactly that, and the test compares it.
 */
export function screenshotIrDigest(): string {
  return createHash("sha256").update(JSON.stringify(SCREENSHOT_IR)).digest("hex")
}

/**
 * Digest of everything this repository decides about the committed bytes: the
 * page, the encoder settings and the size. The IR digest alone said which page
 * the JPEG shows, never how it was written, so a quality edit slipped past it.
 */
export function screenshotRecipeDigest(): string {
  return createHash("sha256")
    .update(JSON.stringify({ ir: SCREENSHOT_IR, encoder: ENCODER, width: FIXTURE_W, height: FIXTURE_H }))
    .digest("hex")
}

/**
 * The page as SVG, before any raster. Split out so the fixture test can read
 * the font stack the page actually asks for and decide whether this machine
 * resolves it the way the committed bytes did.
 */
export function renderScreenshotSvg(): string {
  installNodePlatform()
  // Validate through the public entry point, exactly as the CLI does — the
  // fixture must be a page the product itself would accept.
  const verdict = validateIr(SCREENSHOT_IR)
  if (!verdict.ok) {
    throw new Error(`SCREENSHOT_IR rejected: ${verdict.errors.map((e) => `${e.path}: ${e.message}`).join("; ")}`)
  }
  return renderSlideSvg(verdict.ir!, 0)
}

/**
 * The first real typeface in the page's own font stack that this machine can
 * actually draw with, or `"generic"` when none of them resolve and the
 * rasterizer falls back on its own default.
 *
 * Probed by drawing one line twice — once in the candidate face, once in a
 * name no system has — and looking for any difference. A face that is not
 * installed produces the same pixels as a name that cannot exist.
 */
export async function resolvedScreenshotFace(): Promise<string> {
  installNodePlatform()
  const rasterize = getPlatform().rasterizeSvg
  if (!rasterize) throw new Error("rasterizeSvg unavailable — installNodePlatform() did not run")
  const stack = renderScreenshotSvg().match(/font-family="([^"]+)"/)?.[1] ?? ""
  const named = stack
    .split(",")
    .map((f) => f.trim().replace(/^['"]|['"]$/g, ""))
    .filter((f) => f && !GENERIC_FAMILIES.has(f.toLowerCase()))
  for (const family of named) {
    if (await faceDrawsDistinctly(family)) return family
  }
  return "generic"
}

const GENERIC_FAMILIES = new Set(["sans-serif", "serif", "monospace", "cursive", "fantasy", "system-ui"])
/** A family name no machine has installed, so it always lands on the default. */
const SENTINEL_FAMILY = "PptwiseNoSuchFaceExists"

async function faceDrawsDistinctly(family: string): Promise<boolean> {
  const rasterize = getPlatform().rasterizeSvg
  if (!rasterize) throw new Error("rasterizeSvg unavailable — installNodePlatform() did not run")
  const draw = (f: string) =>
    `<svg xmlns="http://www.w3.org/2000/svg" width="260" height="64">` +
    `<text x="4" y="46" font-size="40" font-family="${f}">云雀 18.4</text></svg>`
  const bytes = async (f: string) => {
    const img = await rasterize(draw(f), 260, 64)
    return Buffer.from(img.data.buffer, img.data.byteOffset, img.data.byteLength)
  }
  const [target, sentinel] = await Promise.all([bytes(family), bytes(SENTINEL_FAMILY)])
  return !target.equals(sentinel)
}

export async function renderScreenshotJpeg(): Promise<Buffer> {
  installNodePlatform()
  const rasterize = getPlatform().rasterizeSvg
  if (!rasterize) throw new Error("rasterizeSvg unavailable — installNodePlatform() did not run")
  const svg = renderScreenshotSvg()
  const img = await rasterize(svg, FIXTURE_W, FIXTURE_H)
  const raw = Buffer.from(img.data.buffer, img.data.byteOffset, img.data.byteLength)
  return sharp(raw, { raw: { width: img.width, height: img.height, channels: 4 } })
    .flatten({ background: "#FFFFFF" })
    .jpeg({ ...ENCODER })
    .toBuffer()
}

async function main() {
  const root = resolve(fileURLToPath(new URL("..", import.meta.url)))
  const outJpg = resolve(root, FIXTURE_JPG)
  const outJson = resolve(root, FIXTURE_JSON)
  const jpeg = await renderScreenshotJpeg()
  mkdirSync(dirname(outJpg), { recursive: true })
  writeFileSync(outJpg, jpeg)
  writeFileSync(
    outJson,
    JSON.stringify(
      {
        generator: "pptwise renderer",
        script: "scripts/make-screenshot-fixture.mts",
        source: "SCREENSHOT_IR in that script, rendered through validateIr + renderSlideSvg",
        theme: SCREENSHOT_IR.theme.id,
        ir_sha256: screenshotIrDigest(),
        recipe_sha256: screenshotRecipeDigest(),
        encoder: ENCODER,
        // The one environment fact in here, and it is recorded rather than
        // asserted: the page names a stack of CJK faces and the machine that
        // wrote these bytes drew them with this one. A machine that resolves
        // the stack to a different face draws the same page in different
        // glyphs, so the fixture test compares its own probe against this and
        // skips the pixel comparison instead of failing over a font.
        rendered_with_face: await resolvedScreenshotFace(),
        width: FIXTURE_W,
        height: FIXTURE_H,
      },
      null,
      2,
    ) + "\n",
  )
  console.log(`screenshot fixture: ${outJpg} (${(jpeg.length / 1024).toFixed(1)} KB)`)
}

if (process.argv[1] && resolve(process.argv[1]) === resolve(fileURLToPath(import.meta.url))) {
  await main()
}
