/**
 * Regenerates `evals/gallery/fixtures/images/screenshot-1.jpg`, the product
 * screenshot every `device_mockup` specimen in the gallery is framed around.
 *
 * The asset it replaces was generated by an image model with a prompt that
 * asked for the letters to be unreadable, so every mockup in the review
 * matrix was a soft blob and no reviewer could tell a crisp frame from a
 * blurry one. This renders a real dashboard page through this repo's own
 * render chain instead: same `validateIr` + `renderSlideSvg` pair the CLI
 * uses, then sharp at the fixture's exact 1280x720.
 *
 *   pnpm tsx scripts/make-screenshot-fixture.mts
 */

import { createHash } from "node:crypto"
import { mkdirSync, writeFileSync } from "node:fs"
import { dirname, resolve } from "node:path"
import { fileURLToPath } from "node:url"
import sharp from "sharp"
import type { PptxIR } from "../src/ir"
import { renderSlideSvg, validateIr } from "../src/api"
import { installNodePlatform } from "../src/platform/node"
import { getPlatform } from "../src/platform/registry"
import { CANVAS_H_PX, CANVAS_W_PX } from "../src/constants"

/** Fixture paths, relative to the repository root. */
export const FIXTURE_JPG = "evals/gallery/fixtures/images/screenshot-1.jpg"
export const FIXTURE_JSON = "evals/gallery/fixtures/images/screenshot-1.json"

/** JPEG quality — the fixture stays well under the ~150KB the repo budgets. */
const QUALITY = 88

/**
 * The screen contents: an analytics dashboard for a made-up product, in the
 * gallery's own zh register. Neutral product copy, no maintainer vocabulary,
 * no placeholder latin.
 */
export const SCREENSHOT_IR: PptxIR = {
  version: "5",
  filename: "screenshot-1",
  theme: { id: "enterprise" },
  meta: { organization: "云雀数据" },
  // The page draws itself — no picture on it, so no asset to declare.
  assets: { images: {} },
  slides: [
    {
      id: "board",
      type: "content",
      kind: "data",
      heading: "云雀增长看板",
      subheading: "近三十天核心指标",
      components: [
        {
          type: "kpi_cards",
          items: [
            { value: "18.4", unit: "万", label: "月活用户", delta: "up" },
            { value: "62.7", unit: "%", label: "次周留存", delta: "up" },
            { value: "4.9", unit: "分", label: "满意度", delta: "flat" },
            { value: "1.32", unit: "秒", label: "首屏耗时", delta: "down" },
          ],
        },
        {
          type: "chart",
          chart_type: "line",
          axes: { x_title: "周次", y_title: "活跃用户", y_unit: "万", show_grid: true },
          series: [
            {
              name: "移动端",
              data: [
                { x: "第一周", y: 9.2 },
                { x: "第二周", y: 10.4 },
                { x: "第三周", y: 11.1 },
                { x: "第四周", y: 12.6 },
              ],
            },
            {
              name: "网页端",
              data: [
                { x: "第一周", y: 4.8 },
                { x: "第二周", y: 5.1 },
                { x: "第三周", y: 5.6 },
                { x: "第四周", y: 5.8 },
              ],
            },
          ],
        },
      ],
    },
  ],
}

/**
 * The fixture's contract size. It is the canvas size on purpose: the page is
 * rendered at 1:1 and never resampled, which is where the crispness comes from.
 */
export const FIXTURE_W = CANVAS_W_PX
export const FIXTURE_H = CANVAS_H_PX

/**
 * Digest of the page this fixture is a picture of.
 *
 * Recorded instead of a generation date. A date changes on every run, so the
 * committed bundle was never twice the same bytes even when the picture was
 * identical, and it said nothing about whether the JPEG on disk still matches
 * the IR above it. The digest says exactly that, and the test compares it.
 */
export function screenshotIrDigest(): string {
  return createHash("sha256").update(JSON.stringify(SCREENSHOT_IR)).digest("hex")
}

export async function renderScreenshotJpeg(): Promise<Buffer> {
  installNodePlatform()
  const rasterize = getPlatform().rasterizeSvg
  if (!rasterize) throw new Error("rasterizeSvg unavailable — installNodePlatform() did not run")
  // Validate through the public entry point, exactly as the CLI does — the
  // fixture must be a page the product itself would accept.
  const verdict = validateIr(SCREENSHOT_IR)
  if (!verdict.ok) {
    throw new Error(`SCREENSHOT_IR rejected: ${verdict.errors.map((e) => `${e.path}: ${e.message}`).join("; ")}`)
  }
  const svg = renderSlideSvg(verdict.ir!, 0)
  const img = await rasterize(svg, FIXTURE_W, FIXTURE_H)
  const raw = Buffer.from(img.data.buffer, img.data.byteOffset, img.data.byteLength)
  return sharp(raw, { raw: { width: img.width, height: img.height, channels: 4 } })
    .flatten({ background: "#FFFFFF" })
    .jpeg({ quality: QUALITY, chromaSubsampling: "4:4:4" })
    .toBuffer()
}

async function main() {
  const root = resolve(fileURLToPath(new URL("..", import.meta.url)))
  const outJpg = resolve(root, FIXTURE_JPG)
  const outJson = resolve(root, FIXTURE_JSON)
  const jpeg = await renderScreenshotJpeg()
  mkdirSync(dirname(outJpg), { recursive: true })
  writeFileSync(outJpg, jpeg)
  writeFileSync(
    outJson,
    JSON.stringify(
      {
        generator: "pptwise renderer",
        script: "scripts/make-screenshot-fixture.mts",
        source: "SCREENSHOT_IR in that script, rendered through validateIr + renderSlideSvg",
        theme: SCREENSHOT_IR.theme.id,
        ir_sha256: screenshotIrDigest(),
        quality: QUALITY,
        width: FIXTURE_W,
        height: FIXTURE_H,
      },
      null,
      2,
    ) + "\n",
  )
  console.log(`screenshot fixture: ${outJpg} (${(jpeg.length / 1024).toFixed(1)} KB)`)
}

if (process.argv[1] && resolve(process.argv[1]) === resolve(fileURLToPath(import.meta.url))) {
  await main()
}
