/**
 * Regenerates the two product screenshots the gallery's `device_mockup`
 * specimens are framed around:
 *
 *   screenshot-1.jpg        1280x720   a desktop dashboard, behind the browser
 *   screenshot-phone-1.jpg   720x1520  a mobile app, behind the phone
 *
 * The asset these replaced was generated by an image model with a prompt that
 * asked for the letters to be unreadable, so every mockup in the review matrix
 * was a soft blob and no reviewer could tell a crisp frame from a blurry one.
 * Both are drawn here by this repository's own renderers instead.
 *
 *   pnpm tsx scripts/make-screenshot-fixture.mts
 */

import { createHash } from "node:crypto"
import { createElement, type ReactElement, type ReactNode } from "react"
import { mkdirSync, writeFileSync } from "node:fs"
import { dirname, resolve } from "node:path"
import { fileURLToPath } from "node:url"
import sharp from "sharp"
import type { Component, PptxIR } from "../src/ir"
import { renderSlideSvg, validateIr } from "../src/api"
import { measureComponent, renderComponent } from "../src/components"
import { buildCtx } from "../src/render/full-slide-svg"
import { renderSvgMarkup } from "../src/render/serialize"
import { resolveStyle } from "../src/themes"
import { installNodePlatform } from "../src/platform/node"
import { getPlatform } from "../src/platform/registry"
import { CANVAS_H_PX, CANVAS_W_PX } from "../src/constants"

/**
 * Every sharp JPEG option that moves the encoded bytes, named explicitly
 * rather than left to a library default.
 *
 * Recording only quality and chroma left the rest of the recipe implicit, and
 * a default that changed under us — or a hand-added `progressive` — would have
 * rewritten the file with nothing saying what moved. Measured on this fixture:
 * progressive costs 5.7% of the size, turning off Huffman optimisation adds
 * 17.9%, mozjpeg defaults cut 26.2%. All of them are pinned and digested.
 */
export const RECIPE = {
  quality: 88,
  progressive: false,
  chromaSubsampling: "4:4:4",
  optimiseCoding: true,
  trellisQuantisation: false,
  overshootDeringing: false,
  optimiseScans: false,
  quantisationTable: 0,
  mozjpeg: false,
} as const

/** Both fixtures share one product, so the gallery reads as one company. */
const PRODUCT = "云雀增长看板"
const PRODUCT_SUB = "近三十天核心指标"

// ── the desktop dashboard ──────────────────────────────────────────────────

/**
 * The landscape screen's contents: an analytics dashboard for a made-up
 * product, in the gallery's own zh register. Neutral product copy, no
 * maintainer vocabulary, no placeholder latin.
 */
export const SCREENSHOT_IR: PptxIR = {
  version: "5",
  filename: "screenshot-1",
  theme: { id: "enterprise" },
  meta: { organization: "云雀数据" },
  // The page draws itself — no picture on it, so no asset to declare.
  assets: { images: {} },
  slides: [
    {
      id: "board",
      type: "content",
      kind: "data",
      heading: PRODUCT,
      subheading: PRODUCT_SUB,
      components: [
        {
          type: "kpi_cards",
          items: [
            { value: "18.4", unit: "万", label: "月活用户", delta: "up" },
            { value: "62.7", unit: "%", label: "次周留存", delta: "up" },
            { value: "4.9", unit: "分", label: "满意度", delta: "flat" },
            { value: "1.32", unit: "秒", label: "首屏耗时", delta: "down" },
          ],
        },
        {
          type: "chart",
          chart_type: "line",
          axes: { x_title: "周次", y_title: "活跃用户", y_unit: "万", show_grid: true },
          series: [
            {
              name: "移动端",
              data: [
                { x: "第一周", y: 9.2 },
                { x: "第二周", y: 10.4 },
                { x: "第三周", y: 11.1 },
                { x: "第四周", y: 12.6 },
              ],
            },
            {
              name: "网页端",
              data: [
                { x: "第一周", y: 4.8 },
                { x: "第二周", y: 5.1 },
                { x: "第三周", y: 5.6 },
                { x: "第四周", y: 5.8 },
              ],
            },
          ],
        },
      ],
    },
  ],
}

// ── the mobile app ─────────────────────────────────────────────────────────

/**
 * The portrait screen, as a stack of this repository's own components under a
 * phone's own chrome.
 *
 * Not a slide: a slide is `viewBox="0 0 1280 720"` by construction and no face
 * is 9:19, so `renderSlideSvg` cannot draw a phone screen at all. Feeding the
 * landscape dashboard to the phone frame instead produced a portrait slice of
 * a desktop layout — a cropped chart and half a KPI card — which read as a
 * browser someone had squeezed, not as an app. The components are the same
 * ones the desktop page uses, rendered by the same `renderComponent`; what
 * this adds is the phone-shaped column they stack in, and the status bar,
 * header and tab bar that say "app" rather than "page".
 */
export const PHONE_SCREEN = {
  theme: "enterprise",
  title: PRODUCT,
  subtitle: PRODUCT_SUB,
  /** Bottom tab bar labels, the current one first. */
  tabs: ["看板", "渠道", "留存", "我的"],
  blocks: [
    {
      component: {
        type: "kpi_cards",
        items: [
          { value: "18.4", unit: "万", label: "月活用户", delta: "up" },
          { value: "62.7", unit: "%", label: "次周留存", delta: "up" },
        ],
      } as Component,
    },
    {
      component: {
        type: "kpi_cards",
        items: [
          { value: "4.9", unit: "分", label: "满意度", delta: "flat" },
          { value: "1.32", unit: "秒", label: "首屏耗时", delta: "down" },
        ],
      } as Component,
    },
    {
      label: "活跃趋势",
      component: {
        type: "chart",
        chart_type: "line",
        axes: { x_title: "周次", y_title: "活跃用户", y_unit: "万", show_grid: true },
        series: [
          {
            name: "移动端",
            data: [
              { x: "第一周", y: 9.2 },
              { x: "第二周", y: 10.4 },
              { x: "第三周", y: 11.1 },
              { x: "第四周", y: 12.6 },
            ],
          },
        ],
      } as Component,
    },
    {
      label: "最近动态",
      component: {
        type: "row_cards",
        items: [
          { title: "移动端首屏耗时降到 1.32 秒", text: "灰度覆盖全量用户" },
          { title: "应用商店渠道留存回到 64%", text: "新引导流程上线两周" },
          { title: "满意度连续三周持平", text: "工单量同期下降 12%" },
        ],
      } as Component,
    },
    {
      label: "渠道明细",
      component: {
        type: "data_table",
        columns: [
          { key: "c", label: "渠道", align: "left" },
          { key: "u", label: "新增", align: "right" },
          { key: "r", label: "留存", align: "right" },
        ],
        rows: [
          { cells: { c: "应用商店", u: 4820, r: "64.2%" } },
          { cells: { c: "官网直访", u: 3110, r: "58.7%" } },
          { cells: { c: "合作渠道", u: 1960, r: "51.4%" } },
        ],
      } as Component,
    },
  ],
} as const

/** Phone canvas and its own chrome, in the screen's own pixels. */
const PHONE_W = 720
const PHONE_H = 1520
const PHONE_PAD_X = 28
const STATUS_H = 52
const HEADER_H = 156
const TABBAR_H = 96
const BLOCK_GAP = 30
/** Clear air between the last block and the tab bar. */
const CONTENT_BOTTOM_GAP = 24
const LABEL_GAP = 14

/** Shorthand for the phone chrome, which is plain SVG rather than components. */
const h = createElement

function phoneScreenSvg(): string {
  installNodePlatform()
  const tokens = resolveStyle(PHONE_SCREEN.theme)
  const { colors } = tokens
  const ctx = buildCtx(tokens, {}, undefined, colors.bg, 18)
  const bodyFont = ctx.fonts.body
  const headFont = ctx.fonts.heading
  const innerW = PHONE_W - PHONE_PAD_X * 2
  const kids: ReactNode[] = []

  kids.push(h("rect", { key: "bg", x: 0, y: 0, width: PHONE_W, height: PHONE_H, fill: colors.bg }))
  // Status bar and header are one primary field, the way an app paints them.
  kids.push(
    h("rect", { key: "chrome", x: 0, y: 0, width: PHONE_W, height: STATUS_H + HEADER_H, fill: colors.primary }),
  )
  kids.push(
    h(
      "text",
      { key: "clock", x: PHONE_PAD_X, y: 34, fontFamily: bodyFont, fontSize: 20, fill: colors.surface },
      "9:41",
    ),
  )
  // Signal, wifi and battery, as the three blocks a status bar reads as.
  for (const [i, w] of [18, 22, 30].entries()) {
    kids.push(
      h("rect", {
        key: `status-${i}`,
        x: PHONE_W - PHONE_PAD_X - 30 - i * 30,
        y: 18,
        width: Math.round(w * 0.7),
        height: 14,
        rx: 3,
        fill: colors.surface,
        fillOpacity: 0.85,
      }),
    )
  }
  kids.push(
    h(
      "text",
      {
        key: "title",
        x: PHONE_PAD_X,
        y: STATUS_H + 62,
        fontFamily: headFont,
        fontSize: 38,
        fontWeight: 700,
        fill: colors.surface,
      },
      PHONE_SCREEN.title,
    ),
  )
  kids.push(
    h(
      "text",
      {
        key: "subtitle",
        x: PHONE_PAD_X,
        y: STATUS_H + 104,
        fontFamily: bodyFont,
        fontSize: 20,
        fill: colors.surface,
        fillOpacity: 0.82,
      },
      PHONE_SCREEN.subtitle,
    ),
  )

  let cursor = STATUS_H + HEADER_H + BLOCK_GAP
  for (const [i, block] of PHONE_SCREEN.blocks.entries()) {
    if ("label" in block && block.label) {
      kids.push(
        h(
          "text",
          {
            key: `label-${i}`,
            x: PHONE_PAD_X,
            y: cursor + 20,
            fontFamily: headFont,
            fontSize: 22,
            fontWeight: 700,
            fill: colors.text,
          },
          block.label,
        ),
      )
      cursor += 20 + LABEL_GAP
    }
    const component = block.component as Component
    const height = measureComponent(component, innerW, ctx)
    kids.push(
      h("g", { key: `block-${i}` }, renderComponent(component, { x: PHONE_PAD_X, y: cursor, w: innerW, h: height }, ctx)),
    )
    cursor += height + BLOCK_GAP
  }

  // Tab bar, pinned to the bottom edge the way a real one is.
  const tabTop = PHONE_H - TABBAR_H
  // The stack has to end above it. A block list that overran used to slide
  // under the bar and lose its last table row to it, which is the one thing a
  // screenshot of a working app must never show.
  if (cursor - BLOCK_GAP > tabTop - CONTENT_BOTTOM_GAP) {
    throw new Error(
      `PHONE_SCREEN blocks run to ${cursor - BLOCK_GAP}px, past the ${tabTop - CONTENT_BOTTOM_GAP}px the tab bar leaves`,
    )
  }
  kids.push(h("rect", { key: "tabbar", x: 0, y: tabTop, width: PHONE_W, height: TABBAR_H, fill: colors.surface }))
  kids.push(h("rect", { key: "tabrule", x: 0, y: tabTop, width: PHONE_W, height: 1, fill: colors.border }))
  const tabW = PHONE_W / PHONE_SCREEN.tabs.length
  for (const [i, tab] of PHONE_SCREEN.tabs.entries()) {
    const cx = tabW * i + tabW / 2
    const active = i === 0
    const ink = active ? colors.primary : colors.muted
    kids.push(
      h("rect", {
        key: `tabicon-${i}`,
        x: cx - 13,
        y: tabTop + 22,
        width: 26,
        height: 26,
        rx: 7,
        fill: ink,
        fillOpacity: active ? 1 : 0.55,
      }),
    )
    kids.push(
      h(
        "text",
        {
          key: `tab-${i}`,
          x: cx,
          y: tabTop + 74,
          textAnchor: "middle",
          fontFamily: bodyFont,
          fontSize: 18,
          fill: ink,
        },
        tab,
      ),
    )
  }
  // Home indicator, so the screen ends the way a phone screen ends.
  kids.push(
    h("rect", {
      key: "home",
      x: PHONE_W / 2 - 70,
      y: PHONE_H - 12,
      width: 140,
      height: 5,
      rx: 2.5,
      fill: colors.text,
      fillOpacity: 0.35,
    }),
  )

  // One React tree, serialized once: rendering each component on its own put
  // React in HTML mode, where it warns about `<linearGradient>` and would be
  // free to lowercase an SVG tag name the chart depends on.
  return renderSvgMarkup(
    h(
      "svg",
      { width: PHONE_W, height: PHONE_H, viewBox: `0 0 ${PHONE_W} ${PHONE_H}` },
      kids,
    ) as ReactElement,
  )
}

// ── the two fixtures ───────────────────────────────────────────────────────

export interface FixtureSpec {
  /** Asset id, and the basename of both files. */
  readonly id: string
  /** Path to the JPEG, relative to the repository root. */
  readonly jpg: string
  /** Path to the provenance JSON, relative to the repository root. */
  readonly json: string
  readonly width: number
  readonly height: number
  /** What the digest covers: the page this file is a picture of. */
  readonly source: unknown
  /** One line for the provenance, saying where the picture comes from. */
  readonly sourceNote: string
  readonly svg: () => string
}

export const FIXTURES: Record<"landscape" | "phone", FixtureSpec> = {
  landscape: {
    id: "screenshot-1",
    jpg: "evals/gallery/fixtures/images/screenshot-1.jpg",
    json: "evals/gallery/fixtures/images/screenshot-1.json",
    width: CANVAS_W_PX,
    height: CANVAS_H_PX,
    source: SCREENSHOT_IR,
    sourceNote: "SCREENSHOT_IR in that script, rendered through validateIr + renderSlideSvg",
    svg: renderScreenshotSvg,
  },
  phone: {
    id: "screenshot-phone-1",
    jpg: "evals/gallery/fixtures/images/screenshot-phone-1.jpg",
    json: "evals/gallery/fixtures/images/screenshot-phone-1.json",
    width: PHONE_W,
    height: PHONE_H,
    source: PHONE_SCREEN,
    sourceNote:
      "PHONE_SCREEN in that script, its components rendered through renderComponent into a 9:19 phone canvas",
    svg: phoneScreenSvg,
  },
}

/**
 * The landscape page as SVG, before any raster. Split out so the fixture test
 * can read the font stack the page actually asks for and decide whether this
 * machine resolves it the way the committed bytes did.
 */
export function renderScreenshotSvg(): string {
  installNodePlatform()
  // Validate through the public entry point, exactly as the CLI does — the
  // fixture must be a page the product itself would accept.
  const verdict = validateIr(SCREENSHOT_IR)
  if (!verdict.ok) {
    throw new Error(`SCREENSHOT_IR rejected: ${verdict.errors.map((e) => `${e.path}: ${e.message}`).join("; ")}`)
  }
  return renderSlideSvg(verdict.ir!, 0)
}

/** Digest of the page a fixture is a picture of. */
export function fixtureSourceDigest(spec: FixtureSpec): string {
  return createHash("sha256").update(JSON.stringify(spec.source)).digest("hex")
}

/**
 * Digest of everything this repository decides about the committed bytes: the
 * page, the whole encoder recipe and the size. The source digest alone said
 * which page the JPEG shows, never how it was written, so a quality edit
 * slipped past it.
 */
export function fixtureRecipeDigest(spec: FixtureSpec): string {
  return createHash("sha256")
    .update(JSON.stringify({ source: spec.source, recipe: RECIPE, width: spec.width, height: spec.height }))
    .digest("hex")
}

export async function renderFixtureJpeg(spec: FixtureSpec): Promise<Buffer> {
  installNodePlatform()
  const rasterize = getPlatform().rasterizeSvg
  if (!rasterize) throw new Error("rasterizeSvg unavailable — installNodePlatform() did not run")
  const img = await rasterize(spec.svg(), spec.width, spec.height)
  const raw = Buffer.from(img.data.buffer, img.data.byteOffset, img.data.byteLength)
  return sharp(raw, { raw: { width: img.width, height: img.height, channels: 4 } })
    .flatten({ background: "#FFFFFF" })
    .jpeg({ ...RECIPE })
    .toBuffer()
}

/**
 * The first real typeface in a fixture's own font stack that this machine can
 * actually draw with, or `"generic"` when none of them resolve and the
 * rasterizer falls back on its own default.
 *
 * Probed by drawing one line twice — once in the candidate face, once in a
 * name no system has — and looking for any difference. A face that is not
 * installed produces the same pixels as a name that cannot exist.
 */
export async function resolvedFixtureFace(spec: FixtureSpec): Promise<string> {
  installNodePlatform()
  const stack = spec.svg().match(/font-family="([^"]+)"/)?.[1] ?? ""
  const named = stack
    .split(",")
    .map((f) => f.trim().replace(/^['"]|['"]$/g, ""))
    .filter((f) => f && !GENERIC_FAMILIES.has(f.toLowerCase()))
  for (const family of named) {
    if (await faceDrawsDistinctly(family)) return family
  }
  return "generic"
}

const GENERIC_FAMILIES = new Set(["sans-serif", "serif", "monospace", "cursive", "fantasy", "system-ui"])
/** A family name no machine has installed, so it always lands on the default. */
const SENTINEL_FAMILY = "PptwiseNoSuchFaceExists"

async function faceDrawsDistinctly(family: string): Promise<boolean> {
  const rasterize = getPlatform().rasterizeSvg
  if (!rasterize) throw new Error("rasterizeSvg unavailable — installNodePlatform() did not run")
  const draw = (f: string) =>
    `<svg xmlns="http://www.w3.org/2000/svg" width="260" height="64">` +
    `<text x="4" y="46" font-size="40" font-family="${f}">云雀 18.4</text></svg>`
  const bytes = async (f: string) => {
    const img = await rasterize(draw(f), 260, 64)
    return Buffer.from(img.data.buffer, img.data.byteOffset, img.data.byteLength)
  }
  const [target, sentinel] = await Promise.all([bytes(family), bytes(SENTINEL_FAMILY)])
  return !target.equals(sentinel)
}

async function writeFixture(root: string, spec: FixtureSpec): Promise<void> {
  const jpeg = await renderFixtureJpeg(spec)
  const outJpg = resolve(root, spec.jpg)
  mkdirSync(dirname(outJpg), { recursive: true })
  writeFileSync(outJpg, jpeg)
  writeFileSync(
    resolve(root, spec.json),
    JSON.stringify(
      {
        generator: "pptwise renderer",
        script: "scripts/make-screenshot-fixture.mts",
        source: spec.sourceNote,
        source_sha256: fixtureSourceDigest(spec),
        recipe_sha256: fixtureRecipeDigest(spec),
        recipe: RECIPE,
        // The one environment fact in here, and it is recorded rather than
        // asserted: the page names a stack of CJK faces and the machine that
        // wrote these bytes drew them with this one. A machine that resolves
        // the stack to a different face draws the same page in different
        // glyphs, so the fixture test compares its own probe against this and
        // skips the pixel comparison instead of failing over a font.
        rendered_with_face: await resolvedFixtureFace(spec),
        width: spec.width,
        height: spec.height,
      },
      null,
      2,
    ) + "\n",
  )
  console.log(`${spec.id}: ${outJpg} (${(jpeg.length / 1024).toFixed(1)} KB)`)
}

async function main() {
  const root = resolve(fileURLToPath(new URL("..", import.meta.url)))
  for (const spec of Object.values(FIXTURES)) await writeFixture(root, spec)
}

if (process.argv[1] && resolve(process.argv[1]) === resolve(fileURLToPath(import.meta.url))) {
  await main()
}
